// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gs_ingest.proto

package gsingestv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/ppusapati/space/services/gs-ingest/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IngestServiceName is the fully-qualified name of the IngestService service.
	IngestServiceName = "p9e.space.gsingest.v1.IngestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IngestServiceStartIngestSessionProcedure is the fully-qualified name of the IngestService's
	// StartIngestSession RPC.
	IngestServiceStartIngestSessionProcedure = "/p9e.space.gsingest.v1.IngestService/StartIngestSession"
	// IngestServiceGetIngestSessionProcedure is the fully-qualified name of the IngestService's
	// GetIngestSession RPC.
	IngestServiceGetIngestSessionProcedure = "/p9e.space.gsingest.v1.IngestService/GetIngestSession"
	// IngestServiceListIngestSessionsProcedure is the fully-qualified name of the IngestService's
	// ListIngestSessions RPC.
	IngestServiceListIngestSessionsProcedure = "/p9e.space.gsingest.v1.IngestService/ListIngestSessions"
	// IngestServiceUpdateIngestStatusProcedure is the fully-qualified name of the IngestService's
	// UpdateIngestStatus RPC.
	IngestServiceUpdateIngestStatusProcedure = "/p9e.space.gsingest.v1.IngestService/UpdateIngestStatus"
	// IngestServiceRecordDownlinkFrameProcedure is the fully-qualified name of the IngestService's
	// RecordDownlinkFrame RPC.
	IngestServiceRecordDownlinkFrameProcedure = "/p9e.space.gsingest.v1.IngestService/RecordDownlinkFrame"
	// IngestServiceGetDownlinkFrameProcedure is the fully-qualified name of the IngestService's
	// GetDownlinkFrame RPC.
	IngestServiceGetDownlinkFrameProcedure = "/p9e.space.gsingest.v1.IngestService/GetDownlinkFrame"
	// IngestServiceListDownlinkFramesProcedure is the fully-qualified name of the IngestService's
	// ListDownlinkFrames RPC.
	IngestServiceListDownlinkFramesProcedure = "/p9e.space.gsingest.v1.IngestService/ListDownlinkFrames"
)

// IngestServiceClient is a client for the p9e.space.gsingest.v1.IngestService service.
type IngestServiceClient interface {
	StartIngestSession(context.Context, *connect.Request[api.StartIngestSessionRequest]) (*connect.Response[api.StartIngestSessionResponse], error)
	GetIngestSession(context.Context, *connect.Request[api.GetIngestSessionRequest]) (*connect.Response[api.GetIngestSessionResponse], error)
	ListIngestSessions(context.Context, *connect.Request[api.ListIngestSessionsRequest]) (*connect.Response[api.ListIngestSessionsResponse], error)
	UpdateIngestStatus(context.Context, *connect.Request[api.UpdateIngestStatusRequest]) (*connect.Response[api.UpdateIngestStatusResponse], error)
	RecordDownlinkFrame(context.Context, *connect.Request[api.RecordDownlinkFrameRequest]) (*connect.Response[api.RecordDownlinkFrameResponse], error)
	GetDownlinkFrame(context.Context, *connect.Request[api.GetDownlinkFrameRequest]) (*connect.Response[api.GetDownlinkFrameResponse], error)
	ListDownlinkFrames(context.Context, *connect.Request[api.ListDownlinkFramesRequest]) (*connect.Response[api.ListDownlinkFramesResponse], error)
}

// NewIngestServiceClient constructs a client for the p9e.space.gsingest.v1.IngestService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIngestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IngestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ingestServiceMethods := api.File_gs_ingest_proto.Services().ByName("IngestService").Methods()
	return &ingestServiceClient{
		startIngestSession: connect.NewClient[api.StartIngestSessionRequest, api.StartIngestSessionResponse](
			httpClient,
			baseURL+IngestServiceStartIngestSessionProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("StartIngestSession")),
			connect.WithClientOptions(opts...),
		),
		getIngestSession: connect.NewClient[api.GetIngestSessionRequest, api.GetIngestSessionResponse](
			httpClient,
			baseURL+IngestServiceGetIngestSessionProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("GetIngestSession")),
			connect.WithClientOptions(opts...),
		),
		listIngestSessions: connect.NewClient[api.ListIngestSessionsRequest, api.ListIngestSessionsResponse](
			httpClient,
			baseURL+IngestServiceListIngestSessionsProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("ListIngestSessions")),
			connect.WithClientOptions(opts...),
		),
		updateIngestStatus: connect.NewClient[api.UpdateIngestStatusRequest, api.UpdateIngestStatusResponse](
			httpClient,
			baseURL+IngestServiceUpdateIngestStatusProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("UpdateIngestStatus")),
			connect.WithClientOptions(opts...),
		),
		recordDownlinkFrame: connect.NewClient[api.RecordDownlinkFrameRequest, api.RecordDownlinkFrameResponse](
			httpClient,
			baseURL+IngestServiceRecordDownlinkFrameProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("RecordDownlinkFrame")),
			connect.WithClientOptions(opts...),
		),
		getDownlinkFrame: connect.NewClient[api.GetDownlinkFrameRequest, api.GetDownlinkFrameResponse](
			httpClient,
			baseURL+IngestServiceGetDownlinkFrameProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("GetDownlinkFrame")),
			connect.WithClientOptions(opts...),
		),
		listDownlinkFrames: connect.NewClient[api.ListDownlinkFramesRequest, api.ListDownlinkFramesResponse](
			httpClient,
			baseURL+IngestServiceListDownlinkFramesProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("ListDownlinkFrames")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ingestServiceClient implements IngestServiceClient.
type ingestServiceClient struct {
	startIngestSession  *connect.Client[api.StartIngestSessionRequest, api.StartIngestSessionResponse]
	getIngestSession    *connect.Client[api.GetIngestSessionRequest, api.GetIngestSessionResponse]
	listIngestSessions  *connect.Client[api.ListIngestSessionsRequest, api.ListIngestSessionsResponse]
	updateIngestStatus  *connect.Client[api.UpdateIngestStatusRequest, api.UpdateIngestStatusResponse]
	recordDownlinkFrame *connect.Client[api.RecordDownlinkFrameRequest, api.RecordDownlinkFrameResponse]
	getDownlinkFrame    *connect.Client[api.GetDownlinkFrameRequest, api.GetDownlinkFrameResponse]
	listDownlinkFrames  *connect.Client[api.ListDownlinkFramesRequest, api.ListDownlinkFramesResponse]
}

// StartIngestSession calls p9e.space.gsingest.v1.IngestService.StartIngestSession.
func (c *ingestServiceClient) StartIngestSession(ctx context.Context, req *connect.Request[api.StartIngestSessionRequest]) (*connect.Response[api.StartIngestSessionResponse], error) {
	return c.startIngestSession.CallUnary(ctx, req)
}

// GetIngestSession calls p9e.space.gsingest.v1.IngestService.GetIngestSession.
func (c *ingestServiceClient) GetIngestSession(ctx context.Context, req *connect.Request[api.GetIngestSessionRequest]) (*connect.Response[api.GetIngestSessionResponse], error) {
	return c.getIngestSession.CallUnary(ctx, req)
}

// ListIngestSessions calls p9e.space.gsingest.v1.IngestService.ListIngestSessions.
func (c *ingestServiceClient) ListIngestSessions(ctx context.Context, req *connect.Request[api.ListIngestSessionsRequest]) (*connect.Response[api.ListIngestSessionsResponse], error) {
	return c.listIngestSessions.CallUnary(ctx, req)
}

// UpdateIngestStatus calls p9e.space.gsingest.v1.IngestService.UpdateIngestStatus.
func (c *ingestServiceClient) UpdateIngestStatus(ctx context.Context, req *connect.Request[api.UpdateIngestStatusRequest]) (*connect.Response[api.UpdateIngestStatusResponse], error) {
	return c.updateIngestStatus.CallUnary(ctx, req)
}

// RecordDownlinkFrame calls p9e.space.gsingest.v1.IngestService.RecordDownlinkFrame.
func (c *ingestServiceClient) RecordDownlinkFrame(ctx context.Context, req *connect.Request[api.RecordDownlinkFrameRequest]) (*connect.Response[api.RecordDownlinkFrameResponse], error) {
	return c.recordDownlinkFrame.CallUnary(ctx, req)
}

// GetDownlinkFrame calls p9e.space.gsingest.v1.IngestService.GetDownlinkFrame.
func (c *ingestServiceClient) GetDownlinkFrame(ctx context.Context, req *connect.Request[api.GetDownlinkFrameRequest]) (*connect.Response[api.GetDownlinkFrameResponse], error) {
	return c.getDownlinkFrame.CallUnary(ctx, req)
}

// ListDownlinkFrames calls p9e.space.gsingest.v1.IngestService.ListDownlinkFrames.
func (c *ingestServiceClient) ListDownlinkFrames(ctx context.Context, req *connect.Request[api.ListDownlinkFramesRequest]) (*connect.Response[api.ListDownlinkFramesResponse], error) {
	return c.listDownlinkFrames.CallUnary(ctx, req)
}

// IngestServiceHandler is an implementation of the p9e.space.gsingest.v1.IngestService service.
type IngestServiceHandler interface {
	StartIngestSession(context.Context, *connect.Request[api.StartIngestSessionRequest]) (*connect.Response[api.StartIngestSessionResponse], error)
	GetIngestSession(context.Context, *connect.Request[api.GetIngestSessionRequest]) (*connect.Response[api.GetIngestSessionResponse], error)
	ListIngestSessions(context.Context, *connect.Request[api.ListIngestSessionsRequest]) (*connect.Response[api.ListIngestSessionsResponse], error)
	UpdateIngestStatus(context.Context, *connect.Request[api.UpdateIngestStatusRequest]) (*connect.Response[api.UpdateIngestStatusResponse], error)
	RecordDownlinkFrame(context.Context, *connect.Request[api.RecordDownlinkFrameRequest]) (*connect.Response[api.RecordDownlinkFrameResponse], error)
	GetDownlinkFrame(context.Context, *connect.Request[api.GetDownlinkFrameRequest]) (*connect.Response[api.GetDownlinkFrameResponse], error)
	ListDownlinkFrames(context.Context, *connect.Request[api.ListDownlinkFramesRequest]) (*connect.Response[api.ListDownlinkFramesResponse], error)
}

// NewIngestServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIngestServiceHandler(svc IngestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ingestServiceMethods := api.File_gs_ingest_proto.Services().ByName("IngestService").Methods()
	ingestServiceStartIngestSessionHandler := connect.NewUnaryHandler(
		IngestServiceStartIngestSessionProcedure,
		svc.StartIngestSession,
		connect.WithSchema(ingestServiceMethods.ByName("StartIngestSession")),
		connect.WithHandlerOptions(opts...),
	)
	ingestServiceGetIngestSessionHandler := connect.NewUnaryHandler(
		IngestServiceGetIngestSessionProcedure,
		svc.GetIngestSession,
		connect.WithSchema(ingestServiceMethods.ByName("GetIngestSession")),
		connect.WithHandlerOptions(opts...),
	)
	ingestServiceListIngestSessionsHandler := connect.NewUnaryHandler(
		IngestServiceListIngestSessionsProcedure,
		svc.ListIngestSessions,
		connect.WithSchema(ingestServiceMethods.ByName("ListIngestSessions")),
		connect.WithHandlerOptions(opts...),
	)
	ingestServiceUpdateIngestStatusHandler := connect.NewUnaryHandler(
		IngestServiceUpdateIngestStatusProcedure,
		svc.UpdateIngestStatus,
		connect.WithSchema(ingestServiceMethods.ByName("UpdateIngestStatus")),
		connect.WithHandlerOptions(opts...),
	)
	ingestServiceRecordDownlinkFrameHandler := connect.NewUnaryHandler(
		IngestServiceRecordDownlinkFrameProcedure,
		svc.RecordDownlinkFrame,
		connect.WithSchema(ingestServiceMethods.ByName("RecordDownlinkFrame")),
		connect.WithHandlerOptions(opts...),
	)
	ingestServiceGetDownlinkFrameHandler := connect.NewUnaryHandler(
		IngestServiceGetDownlinkFrameProcedure,
		svc.GetDownlinkFrame,
		connect.WithSchema(ingestServiceMethods.ByName("GetDownlinkFrame")),
		connect.WithHandlerOptions(opts...),
	)
	ingestServiceListDownlinkFramesHandler := connect.NewUnaryHandler(
		IngestServiceListDownlinkFramesProcedure,
		svc.ListDownlinkFrames,
		connect.WithSchema(ingestServiceMethods.ByName("ListDownlinkFrames")),
		connect.WithHandlerOptions(opts...),
	)
	return "/p9e.space.gsingest.v1.IngestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IngestServiceStartIngestSessionProcedure:
			ingestServiceStartIngestSessionHandler.ServeHTTP(w, r)
		case IngestServiceGetIngestSessionProcedure:
			ingestServiceGetIngestSessionHandler.ServeHTTP(w, r)
		case IngestServiceListIngestSessionsProcedure:
			ingestServiceListIngestSessionsHandler.ServeHTTP(w, r)
		case IngestServiceUpdateIngestStatusProcedure:
			ingestServiceUpdateIngestStatusHandler.ServeHTTP(w, r)
		case IngestServiceRecordDownlinkFrameProcedure:
			ingestServiceRecordDownlinkFrameHandler.ServeHTTP(w, r)
		case IngestServiceGetDownlinkFrameProcedure:
			ingestServiceGetDownlinkFrameHandler.ServeHTTP(w, r)
		case IngestServiceListDownlinkFramesProcedure:
			ingestServiceListDownlinkFramesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIngestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIngestServiceHandler struct{}

func (UnimplementedIngestServiceHandler) StartIngestSession(context.Context, *connect.Request[api.StartIngestSessionRequest]) (*connect.Response[api.StartIngestSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gsingest.v1.IngestService.StartIngestSession is not implemented"))
}

func (UnimplementedIngestServiceHandler) GetIngestSession(context.Context, *connect.Request[api.GetIngestSessionRequest]) (*connect.Response[api.GetIngestSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gsingest.v1.IngestService.GetIngestSession is not implemented"))
}

func (UnimplementedIngestServiceHandler) ListIngestSessions(context.Context, *connect.Request[api.ListIngestSessionsRequest]) (*connect.Response[api.ListIngestSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gsingest.v1.IngestService.ListIngestSessions is not implemented"))
}

func (UnimplementedIngestServiceHandler) UpdateIngestStatus(context.Context, *connect.Request[api.UpdateIngestStatusRequest]) (*connect.Response[api.UpdateIngestStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gsingest.v1.IngestService.UpdateIngestStatus is not implemented"))
}

func (UnimplementedIngestServiceHandler) RecordDownlinkFrame(context.Context, *connect.Request[api.RecordDownlinkFrameRequest]) (*connect.Response[api.RecordDownlinkFrameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gsingest.v1.IngestService.RecordDownlinkFrame is not implemented"))
}

func (UnimplementedIngestServiceHandler) GetDownlinkFrame(context.Context, *connect.Request[api.GetDownlinkFrameRequest]) (*connect.Response[api.GetDownlinkFrameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gsingest.v1.IngestService.GetDownlinkFrame is not implemented"))
}

func (UnimplementedIngestServiceHandler) ListDownlinkFrames(context.Context, *connect.Request[api.ListDownlinkFramesRequest]) (*connect.Response[api.ListDownlinkFramesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gsingest.v1.IngestService.ListDownlinkFrames is not implemented"))
}
