// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: packages/proto/blob.proto

package blob

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlobConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	BasePath      string                 `protobuf:"bytes,2,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	RegexFilter   string                 `protobuf:"bytes,4,opt,name=regex_filter,json=regexFilter,proto3" json:"regex_filter,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,5,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	InternalUrl   string                 `protobuf:"bytes,6,opt,name=internal_url,json=internalUrl,proto3" json:"internal_url,omitempty"`
	S3            *BlobProviderS3        `protobuf:"bytes,100,opt,name=s3,proto3" json:"s3,omitempty"`
	Os            *BlobProviderOs        `protobuf:"bytes,101,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobConfig) Reset() {
	*x = BlobConfig{}
	mi := &file_packages_proto_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobConfig) ProtoMessage() {}

func (x *BlobConfig) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobConfig.ProtoReflect.Descriptor instead.
func (*BlobConfig) Descriptor() ([]byte, []int) {
	return file_packages_proto_blob_proto_rawDescGZIP(), []int{0}
}

func (x *BlobConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *BlobConfig) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *BlobConfig) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *BlobConfig) GetRegexFilter() string {
	if x != nil {
		return x.RegexFilter
	}
	return ""
}

func (x *BlobConfig) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *BlobConfig) GetInternalUrl() string {
	if x != nil {
		return x.InternalUrl
	}
	return ""
}

func (x *BlobConfig) GetS3() *BlobProviderS3 {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *BlobConfig) GetOs() *BlobProviderOs {
	if x != nil {
		return x.Os
	}
	return nil
}

type BlobProviderS3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobProviderS3) Reset() {
	*x = BlobProviderS3{}
	mi := &file_packages_proto_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobProviderS3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobProviderS3) ProtoMessage() {}

func (x *BlobProviderS3) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobProviderS3.ProtoReflect.Descriptor instead.
func (*BlobProviderS3) Descriptor() ([]byte, []int) {
	return file_packages_proto_blob_proto_rawDescGZIP(), []int{1}
}

func (x *BlobProviderS3) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *BlobProviderS3) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BlobProviderS3) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *BlobProviderS3) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type BlobProviderOs struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Dir           *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=dir,proto3,oneof" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobProviderOs) Reset() {
	*x = BlobProviderOs{}
	mi := &file_packages_proto_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobProviderOs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobProviderOs) ProtoMessage() {}

func (x *BlobProviderOs) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobProviderOs.ProtoReflect.Descriptor instead.
func (*BlobProviderOs) Descriptor() ([]byte, []int) {
	return file_packages_proto_blob_proto_rawDescGZIP(), []int{2}
}

func (x *BlobProviderOs) GetDir() *wrapperspb.StringValue {
	if x != nil {
		return x.Dir
	}
	return nil
}

type BlobFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mime          string                 `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobFile) Reset() {
	*x = BlobFile{}
	mi := &file_packages_proto_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobFile) ProtoMessage() {}

func (x *BlobFile) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobFile.ProtoReflect.Descriptor instead.
func (*BlobFile) Descriptor() ([]byte, []int) {
	return file_packages_proto_blob_proto_rawDescGZIP(), []int{3}
}

func (x *BlobFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlobFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlobFile) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *BlobFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlobFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BlobFile) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_packages_proto_blob_proto protoreflect.FileDescriptor

const file_packages_proto_blob_proto_rawDesc = "" +
	"\n" +
	"\x19packages/proto/blob.proto\x12\x14packages.api.v1.blob\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb3\x02\n" +
	"\n" +
	"BlobConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1b\n" +
	"\tbase_path\x18\x02 \x01(\tR\bbasePath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\x12!\n" +
	"\fregex_filter\x18\x04 \x01(\tR\vregexFilter\x12\x1d\n" +
	"\n" +
	"public_url\x18\x05 \x01(\tR\tpublicUrl\x12!\n" +
	"\finternal_url\x18\x06 \x01(\tR\vinternalUrl\x124\n" +
	"\x02s3\x18d \x01(\v2$.packages.api.v1.blob.BlobProviderS3R\x02s3\x124\n" +
	"\x02os\x18e \x01(\v2$.packages.api.v1.blob.BlobProviderOsR\x02os\"j\n" +
	"\x0eBlobProviderS3\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\"M\n" +
	"\x0eBlobProviderOs\x123\n" +
	"\x03dir\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\x03dir\x88\x01\x01B\x06\n" +
	"\x04_dir\"\x9d\x01\n" +
	"\bBlobFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadataB+Z)p9e.in/chetana/packages/api/v1/blob;blobb\x06proto3"

var (
	file_packages_proto_blob_proto_rawDescOnce sync.Once
	file_packages_proto_blob_proto_rawDescData []byte
)

func file_packages_proto_blob_proto_rawDescGZIP() []byte {
	file_packages_proto_blob_proto_rawDescOnce.Do(func() {
		file_packages_proto_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_proto_blob_proto_rawDesc), len(file_packages_proto_blob_proto_rawDesc)))
	})
	return file_packages_proto_blob_proto_rawDescData
}

var file_packages_proto_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_packages_proto_blob_proto_goTypes = []any{
	(*BlobConfig)(nil),             // 0: packages.api.v1.blob.BlobConfig
	(*BlobProviderS3)(nil),         // 1: packages.api.v1.blob.BlobProviderS3
	(*BlobProviderOs)(nil),         // 2: packages.api.v1.blob.BlobProviderOs
	(*BlobFile)(nil),               // 3: packages.api.v1.blob.BlobFile
	(*wrapperspb.StringValue)(nil), // 4: google.protobuf.StringValue
	(*structpb.Struct)(nil),        // 5: google.protobuf.Struct
}
var file_packages_proto_blob_proto_depIdxs = []int32{
	1, // 0: packages.api.v1.blob.BlobConfig.s3:type_name -> packages.api.v1.blob.BlobProviderS3
	2, // 1: packages.api.v1.blob.BlobConfig.os:type_name -> packages.api.v1.blob.BlobProviderOs
	4, // 2: packages.api.v1.blob.BlobProviderOs.dir:type_name -> google.protobuf.StringValue
	5, // 3: packages.api.v1.blob.BlobFile.metadata:type_name -> google.protobuf.Struct
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_packages_proto_blob_proto_init() }
func file_packages_proto_blob_proto_init() {
	if File_packages_proto_blob_proto != nil {
		return
	}
	file_packages_proto_blob_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_proto_blob_proto_rawDesc), len(file_packages_proto_blob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_proto_blob_proto_goTypes,
		DependencyIndexes: file_packages_proto_blob_proto_depIdxs,
		MessageInfos:      file_packages_proto_blob_proto_msgTypes,
	}.Build()
	File_packages_proto_blob_proto = out.File
	file_packages_proto_blob_proto_goTypes = nil
	file_packages_proto_blob_proto_depIdxs = nil
}
