// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: packages/proto/fields.proto

package fields

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fields struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid          string                  `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	IsActive      bool                    `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedBy     *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedBy     *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedBy     *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	DeletedAt     *timestamppb.Timestamp  `protobuf:"bytes,16,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fields) Reset() {
	*x = Fields{}
	mi := &file_packages_proto_fields_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fields) ProtoMessage() {}

func (x *Fields) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_fields_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fields.ProtoReflect.Descriptor instead.
func (*Fields) Descriptor() ([]byte, []int) {
	return file_packages_proto_fields_proto_rawDescGZIP(), []int{0}
}

func (x *Fields) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Fields) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Fields) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Fields) GetCreatedBy() *wrapperspb.StringValue {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Fields) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Fields) GetUpdatedBy() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

func (x *Fields) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Fields) GetDeletedBy() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedBy
	}
	return nil
}

func (x *Fields) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_packages_proto_fields_proto protoreflect.FileDescriptor

const file_packages_proto_fields_proto_rawDesc = "" +
	"\n" +
	"\x1bpackages/proto/fields.proto\x12\x16packages.api.v1.fields\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb1\x03\n" +
	"\x06Fields\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12;\n" +
	"\n" +
	"created_by\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\n" +
	"updated_by\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\tupdatedBy\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_by\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedBy\x129\n" +
	"\n" +
	"deleted_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAtB/Z-p9e.in/samavaya/packages/api/v1/fields;fieldsb\x06proto3"

var (
	file_packages_proto_fields_proto_rawDescOnce sync.Once
	file_packages_proto_fields_proto_rawDescData []byte
)

func file_packages_proto_fields_proto_rawDescGZIP() []byte {
	file_packages_proto_fields_proto_rawDescOnce.Do(func() {
		file_packages_proto_fields_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_proto_fields_proto_rawDesc), len(file_packages_proto_fields_proto_rawDesc)))
	})
	return file_packages_proto_fields_proto_rawDescData
}

var file_packages_proto_fields_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packages_proto_fields_proto_goTypes = []any{
	(*Fields)(nil),                 // 0: packages.api.v1.fields.Fields
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
}
var file_packages_proto_fields_proto_depIdxs = []int32{
	1, // 0: packages.api.v1.fields.Fields.created_by:type_name -> google.protobuf.StringValue
	2, // 1: packages.api.v1.fields.Fields.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: packages.api.v1.fields.Fields.updated_by:type_name -> google.protobuf.StringValue
	2, // 3: packages.api.v1.fields.Fields.updated_at:type_name -> google.protobuf.Timestamp
	1, // 4: packages.api.v1.fields.Fields.deleted_by:type_name -> google.protobuf.StringValue
	2, // 5: packages.api.v1.fields.Fields.deleted_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_packages_proto_fields_proto_init() }
func file_packages_proto_fields_proto_init() {
	if File_packages_proto_fields_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_proto_fields_proto_rawDesc), len(file_packages_proto_fields_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_proto_fields_proto_goTypes,
		DependencyIndexes: file_packages_proto_fields_proto_depIdxs,
		MessageInfos:      file_packages_proto_fields_proto_msgTypes,
	}.Build()
	File_packages_proto_fields_proto = out.File
	file_packages_proto_fields_proto_goTypes = nil
	file_packages_proto_fields_proto_depIdxs = nil
}
