// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gi_predict.proto

package gipredictv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	fields "p9e.in/samavaya/packages/api/v1/fields"
	pagination "p9e.in/samavaya/packages/api/v1/pagination"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForecastType int32

const (
	ForecastType_FORECAST_TYPE_UNSPECIFIED      ForecastType = 0
	ForecastType_FORECAST_TYPE_NDVI_TREND       ForecastType = 1
	ForecastType_FORECAST_TYPE_FLOOD_RISK       ForecastType = 2
	ForecastType_FORECAST_TYPE_DROUGHT_INDEX    ForecastType = 3
	ForecastType_FORECAST_TYPE_LANDCOVER_CHANGE ForecastType = 4
	ForecastType_FORECAST_TYPE_WEATHER          ForecastType = 5
	ForecastType_FORECAST_TYPE_CUSTOM           ForecastType = 6
)

// Enum value maps for ForecastType.
var (
	ForecastType_name = map[int32]string{
		0: "FORECAST_TYPE_UNSPECIFIED",
		1: "FORECAST_TYPE_NDVI_TREND",
		2: "FORECAST_TYPE_FLOOD_RISK",
		3: "FORECAST_TYPE_DROUGHT_INDEX",
		4: "FORECAST_TYPE_LANDCOVER_CHANGE",
		5: "FORECAST_TYPE_WEATHER",
		6: "FORECAST_TYPE_CUSTOM",
	}
	ForecastType_value = map[string]int32{
		"FORECAST_TYPE_UNSPECIFIED":      0,
		"FORECAST_TYPE_NDVI_TREND":       1,
		"FORECAST_TYPE_FLOOD_RISK":       2,
		"FORECAST_TYPE_DROUGHT_INDEX":    3,
		"FORECAST_TYPE_LANDCOVER_CHANGE": 4,
		"FORECAST_TYPE_WEATHER":          5,
		"FORECAST_TYPE_CUSTOM":           6,
	}
)

func (x ForecastType) Enum() *ForecastType {
	p := new(ForecastType)
	*p = x
	return p
}

func (x ForecastType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForecastType) Descriptor() protoreflect.EnumDescriptor {
	return file_gi_predict_proto_enumTypes[0].Descriptor()
}

func (ForecastType) Type() protoreflect.EnumType {
	return &file_gi_predict_proto_enumTypes[0]
}

func (x ForecastType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForecastType.Descriptor instead.
func (ForecastType) EnumDescriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{0}
}

type ForecastStatus int32

const (
	ForecastStatus_FORECAST_STATUS_UNSPECIFIED ForecastStatus = 0
	ForecastStatus_FORECAST_STATUS_QUEUED      ForecastStatus = 1
	ForecastStatus_FORECAST_STATUS_RUNNING     ForecastStatus = 2
	ForecastStatus_FORECAST_STATUS_COMPLETED   ForecastStatus = 3
	ForecastStatus_FORECAST_STATUS_FAILED      ForecastStatus = 4
	ForecastStatus_FORECAST_STATUS_CANCELED    ForecastStatus = 5
)

// Enum value maps for ForecastStatus.
var (
	ForecastStatus_name = map[int32]string{
		0: "FORECAST_STATUS_UNSPECIFIED",
		1: "FORECAST_STATUS_QUEUED",
		2: "FORECAST_STATUS_RUNNING",
		3: "FORECAST_STATUS_COMPLETED",
		4: "FORECAST_STATUS_FAILED",
		5: "FORECAST_STATUS_CANCELED",
	}
	ForecastStatus_value = map[string]int32{
		"FORECAST_STATUS_UNSPECIFIED": 0,
		"FORECAST_STATUS_QUEUED":      1,
		"FORECAST_STATUS_RUNNING":     2,
		"FORECAST_STATUS_COMPLETED":   3,
		"FORECAST_STATUS_FAILED":      4,
		"FORECAST_STATUS_CANCELED":    5,
	}
)

func (x ForecastStatus) Enum() *ForecastStatus {
	p := new(ForecastStatus)
	*p = x
	return p
}

func (x ForecastStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForecastStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gi_predict_proto_enumTypes[1].Descriptor()
}

func (ForecastStatus) Type() protoreflect.EnumType {
	return &file_gi_predict_proto_enumTypes[1]
}

func (x ForecastStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForecastStatus.Descriptor instead.
func (ForecastStatus) EnumDescriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{1}
}

type ForecastJob struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type               ForecastType           `protobuf:"varint,3,opt,name=type,proto3,enum=p9e.space.gipredict.v1.ForecastType" json:"type,omitempty"`
	Status             ForecastStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=p9e.space.gipredict.v1.ForecastStatus" json:"status,omitempty"`
	ModelId            string                 `protobuf:"bytes,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // optional ML model ULID
	InputUris          []string               `protobuf:"bytes,6,rep,name=input_uris,json=inputUris,proto3" json:"input_uris,omitempty"`
	HorizonDays        int32                  `protobuf:"varint,7,opt,name=horizon_days,json=horizonDays,proto3" json:"horizon_days,omitempty"`
	ParametersJson     string                 `protobuf:"bytes,8,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	OutputUri          string                 `protobuf:"bytes,9,opt,name=output_uri,json=outputUri,proto3" json:"output_uri,omitempty"`
	ResultsSummaryJson string                 `protobuf:"bytes,10,opt,name=results_summary_json,json=resultsSummaryJson,proto3" json:"results_summary_json,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Fields             *fields.Fields         `protobuf:"bytes,14,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ForecastJob) Reset() {
	*x = ForecastJob{}
	mi := &file_gi_predict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastJob) ProtoMessage() {}

func (x *ForecastJob) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastJob.ProtoReflect.Descriptor instead.
func (*ForecastJob) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{0}
}

func (x *ForecastJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ForecastJob) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ForecastJob) GetType() ForecastType {
	if x != nil {
		return x.Type
	}
	return ForecastType_FORECAST_TYPE_UNSPECIFIED
}

func (x *ForecastJob) GetStatus() ForecastStatus {
	if x != nil {
		return x.Status
	}
	return ForecastStatus_FORECAST_STATUS_UNSPECIFIED
}

func (x *ForecastJob) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ForecastJob) GetInputUris() []string {
	if x != nil {
		return x.InputUris
	}
	return nil
}

func (x *ForecastJob) GetHorizonDays() int32 {
	if x != nil {
		return x.HorizonDays
	}
	return 0
}

func (x *ForecastJob) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

func (x *ForecastJob) GetOutputUri() string {
	if x != nil {
		return x.OutputUri
	}
	return ""
}

func (x *ForecastJob) GetResultsSummaryJson() string {
	if x != nil {
		return x.ResultsSummaryJson
	}
	return ""
}

func (x *ForecastJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ForecastJob) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ForecastJob) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *ForecastJob) GetFields() *fields.Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type SubmitForecastJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type           ForecastType           `protobuf:"varint,2,opt,name=type,proto3,enum=p9e.space.gipredict.v1.ForecastType" json:"type,omitempty"`
	ModelId        string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // optional
	InputUris      []string               `protobuf:"bytes,4,rep,name=input_uris,json=inputUris,proto3" json:"input_uris,omitempty"`
	HorizonDays    int32                  `protobuf:"varint,5,opt,name=horizon_days,json=horizonDays,proto3" json:"horizon_days,omitempty"`
	ParametersJson string                 `protobuf:"bytes,6,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitForecastJobRequest) Reset() {
	*x = SubmitForecastJobRequest{}
	mi := &file_gi_predict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitForecastJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitForecastJobRequest) ProtoMessage() {}

func (x *SubmitForecastJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitForecastJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitForecastJobRequest) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitForecastJobRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubmitForecastJobRequest) GetType() ForecastType {
	if x != nil {
		return x.Type
	}
	return ForecastType_FORECAST_TYPE_UNSPECIFIED
}

func (x *SubmitForecastJobRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SubmitForecastJobRequest) GetInputUris() []string {
	if x != nil {
		return x.InputUris
	}
	return nil
}

func (x *SubmitForecastJobRequest) GetHorizonDays() int32 {
	if x != nil {
		return x.HorizonDays
	}
	return 0
}

func (x *SubmitForecastJobRequest) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

type SubmitForecastJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *ForecastJob           `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitForecastJobResponse) Reset() {
	*x = SubmitForecastJobResponse{}
	mi := &file_gi_predict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitForecastJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitForecastJobResponse) ProtoMessage() {}

func (x *SubmitForecastJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitForecastJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitForecastJobResponse) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitForecastJobResponse) GetJob() *ForecastJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetForecastJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastJobRequest) Reset() {
	*x = GetForecastJobRequest{}
	mi := &file_gi_predict_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastJobRequest) ProtoMessage() {}

func (x *GetForecastJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastJobRequest.ProtoReflect.Descriptor instead.
func (*GetForecastJobRequest) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{3}
}

func (x *GetForecastJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetForecastJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *ForecastJob           `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastJobResponse) Reset() {
	*x = GetForecastJobResponse{}
	mi := &file_gi_predict_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastJobResponse) ProtoMessage() {}

func (x *GetForecastJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastJobResponse.ProtoReflect.Descriptor instead.
func (*GetForecastJobResponse) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{4}
}

func (x *GetForecastJobResponse) GetJob() *ForecastJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListForecastJobsRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	TenantId      string                        `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        *ForecastStatus               `protobuf:"varint,2,opt,name=status,proto3,enum=p9e.space.gipredict.v1.ForecastStatus,oneof" json:"status,omitempty"`
	Type          *ForecastType                 `protobuf:"varint,3,opt,name=type,proto3,enum=p9e.space.gipredict.v1.ForecastType,oneof" json:"type,omitempty"`
	Page          *pagination.PaginationRequest `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListForecastJobsRequest) Reset() {
	*x = ListForecastJobsRequest{}
	mi := &file_gi_predict_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListForecastJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListForecastJobsRequest) ProtoMessage() {}

func (x *ListForecastJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListForecastJobsRequest.ProtoReflect.Descriptor instead.
func (*ListForecastJobsRequest) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{5}
}

func (x *ListForecastJobsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListForecastJobsRequest) GetStatus() ForecastStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ForecastStatus_FORECAST_STATUS_UNSPECIFIED
}

func (x *ListForecastJobsRequest) GetType() ForecastType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ForecastType_FORECAST_TYPE_UNSPECIFIED
}

func (x *ListForecastJobsRequest) GetPage() *pagination.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListForecastJobsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Jobs          []*ForecastJob                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Page          *pagination.PaginationResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListForecastJobsResponse) Reset() {
	*x = ListForecastJobsResponse{}
	mi := &file_gi_predict_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListForecastJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListForecastJobsResponse) ProtoMessage() {}

func (x *ListForecastJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListForecastJobsResponse.ProtoReflect.Descriptor instead.
func (*ListForecastJobsResponse) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{6}
}

func (x *ListForecastJobsResponse) GetJobs() []*ForecastJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListForecastJobsResponse) GetPage() *pagination.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdateForecastJobStatusRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status             ForecastStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=p9e.space.gipredict.v1.ForecastStatus" json:"status,omitempty"`
	OutputUri          string                 `protobuf:"bytes,3,opt,name=output_uri,json=outputUri,proto3" json:"output_uri,omitempty"`
	ResultsSummaryJson string                 `protobuf:"bytes,4,opt,name=results_summary_json,json=resultsSummaryJson,proto3" json:"results_summary_json,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateForecastJobStatusRequest) Reset() {
	*x = UpdateForecastJobStatusRequest{}
	mi := &file_gi_predict_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateForecastJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateForecastJobStatusRequest) ProtoMessage() {}

func (x *UpdateForecastJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateForecastJobStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateForecastJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateForecastJobStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateForecastJobStatusRequest) GetStatus() ForecastStatus {
	if x != nil {
		return x.Status
	}
	return ForecastStatus_FORECAST_STATUS_UNSPECIFIED
}

func (x *UpdateForecastJobStatusRequest) GetOutputUri() string {
	if x != nil {
		return x.OutputUri
	}
	return ""
}

func (x *UpdateForecastJobStatusRequest) GetResultsSummaryJson() string {
	if x != nil {
		return x.ResultsSummaryJson
	}
	return ""
}

func (x *UpdateForecastJobStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateForecastJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *ForecastJob           `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateForecastJobStatusResponse) Reset() {
	*x = UpdateForecastJobStatusResponse{}
	mi := &file_gi_predict_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateForecastJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateForecastJobStatusResponse) ProtoMessage() {}

func (x *UpdateForecastJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateForecastJobStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateForecastJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateForecastJobStatusResponse) GetJob() *ForecastJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type CancelForecastJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelForecastJobRequest) Reset() {
	*x = CancelForecastJobRequest{}
	mi := &file_gi_predict_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelForecastJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelForecastJobRequest) ProtoMessage() {}

func (x *CancelForecastJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelForecastJobRequest.ProtoReflect.Descriptor instead.
func (*CancelForecastJobRequest) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{9}
}

func (x *CancelForecastJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelForecastJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *ForecastJob           `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelForecastJobResponse) Reset() {
	*x = CancelForecastJobResponse{}
	mi := &file_gi_predict_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelForecastJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelForecastJobResponse) ProtoMessage() {}

func (x *CancelForecastJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gi_predict_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelForecastJobResponse.ProtoReflect.Descriptor instead.
func (*CancelForecastJobResponse) Descriptor() ([]byte, []int) {
	return file_gi_predict_proto_rawDescGZIP(), []int{10}
}

func (x *CancelForecastJobResponse) GetJob() *ForecastJob {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_gi_predict_proto protoreflect.FileDescriptor

const file_gi_predict_proto_rawDesc = "" +
	"\n" +
	"\x10gi_predict.proto\x12\x16p9e.space.gipredict.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\ffields.proto\x1a\x10pagination.proto\"\xe0\x04\n" +
	"\vForecastJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x128\n" +
	"\x04type\x18\x03 \x01(\x0e2$.p9e.space.gipredict.v1.ForecastTypeR\x04type\x12>\n" +
	"\x06status\x18\x04 \x01(\x0e2&.p9e.space.gipredict.v1.ForecastStatusR\x06status\x12\x19\n" +
	"\bmodel_id\x18\x05 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"input_uris\x18\x06 \x03(\tR\tinputUris\x12!\n" +
	"\fhorizon_days\x18\a \x01(\x05R\vhorizonDays\x12'\n" +
	"\x0fparameters_json\x18\b \x01(\tR\x0eparametersJson\x12\x1d\n" +
	"\n" +
	"output_uri\x18\t \x01(\tR\toutputUri\x120\n" +
	"\x14results_summary_json\x18\n" +
	" \x01(\tR\x12resultsSummaryJson\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x126\n" +
	"\x06fields\x18\x0e \x01(\v2\x1e.packages.api.v1.fields.FieldsR\x06fields\"\x99\x02\n" +
	"\x18SubmitForecastJobRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12D\n" +
	"\x04type\x18\x02 \x01(\x0e2$.p9e.space.gipredict.v1.ForecastTypeB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04type\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"input_uris\x18\x04 \x03(\tR\tinputUris\x12-\n" +
	"\fhorizon_days\x18\x05 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xc2\x1c \x00R\vhorizonDays\x12'\n" +
	"\x0fparameters_json\x18\x06 \x01(\tR\x0eparametersJson\"R\n" +
	"\x19SubmitForecastJobResponse\x125\n" +
	"\x03job\x18\x01 \x01(\v2#.p9e.space.gipredict.v1.ForecastJobR\x03job\"1\n" +
	"\x15GetForecastJobRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\"O\n" +
	"\x16GetForecastJobResponse\x125\n" +
	"\x03job\x18\x01 \x01(\v2#.p9e.space.gipredict.v1.ForecastJobR\x03job\"\x9b\x02\n" +
	"\x17ListForecastJobsRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12C\n" +
	"\x06status\x18\x02 \x01(\x0e2&.p9e.space.gipredict.v1.ForecastStatusH\x00R\x06status\x88\x01\x01\x12=\n" +
	"\x04type\x18\x03 \x01(\x0e2$.p9e.space.gipredict.v1.ForecastTypeH\x01R\x04type\x88\x01\x01\x12A\n" +
	"\x04page\x18\x04 \x01(\v2-.packages.api.v1.pagination.PaginationRequestR\x04pageB\t\n" +
	"\a_statusB\a\n" +
	"\x05_type\"\x97\x01\n" +
	"\x18ListForecastJobsResponse\x127\n" +
	"\x04jobs\x18\x01 \x03(\v2#.p9e.space.gipredict.v1.ForecastJobR\x04jobs\x12B\n" +
	"\x04page\x18\x02 \x01(\v2..packages.api.v1.pagination.PaginationResponseR\x04page\"\xfc\x01\n" +
	"\x1eUpdateForecastJobStatusRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\x12J\n" +
	"\x06status\x18\x02 \x01(\x0e2&.p9e.space.gipredict.v1.ForecastStatusB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06status\x12\x1d\n" +
	"\n" +
	"output_uri\x18\x03 \x01(\tR\toutputUri\x120\n" +
	"\x14results_summary_json\x18\x04 \x01(\tR\x12resultsSummaryJson\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"X\n" +
	"\x1fUpdateForecastJobStatusResponse\x125\n" +
	"\x03job\x18\x01 \x01(\v2#.p9e.space.gipredict.v1.ForecastJobR\x03job\"4\n" +
	"\x18CancelForecastJobRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\"R\n" +
	"\x19CancelForecastJobResponse\x125\n" +
	"\x03job\x18\x01 \x01(\v2#.p9e.space.gipredict.v1.ForecastJobR\x03job*\xe3\x01\n" +
	"\fForecastType\x12\x1d\n" +
	"\x19FORECAST_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FORECAST_TYPE_NDVI_TREND\x10\x01\x12\x1c\n" +
	"\x18FORECAST_TYPE_FLOOD_RISK\x10\x02\x12\x1f\n" +
	"\x1bFORECAST_TYPE_DROUGHT_INDEX\x10\x03\x12\"\n" +
	"\x1eFORECAST_TYPE_LANDCOVER_CHANGE\x10\x04\x12\x19\n" +
	"\x15FORECAST_TYPE_WEATHER\x10\x05\x12\x18\n" +
	"\x14FORECAST_TYPE_CUSTOM\x10\x06*\xc3\x01\n" +
	"\x0eForecastStatus\x12\x1f\n" +
	"\x1bFORECAST_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FORECAST_STATUS_QUEUED\x10\x01\x12\x1b\n" +
	"\x17FORECAST_STATUS_RUNNING\x10\x02\x12\x1d\n" +
	"\x19FORECAST_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16FORECAST_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18FORECAST_STATUS_CANCELED\x10\x052\xfa\x04\n" +
	"\x0fForecastService\x12x\n" +
	"\x11SubmitForecastJob\x120.p9e.space.gipredict.v1.SubmitForecastJobRequest\x1a1.p9e.space.gipredict.v1.SubmitForecastJobResponse\x12o\n" +
	"\x0eGetForecastJob\x12-.p9e.space.gipredict.v1.GetForecastJobRequest\x1a..p9e.space.gipredict.v1.GetForecastJobResponse\x12u\n" +
	"\x10ListForecastJobs\x12/.p9e.space.gipredict.v1.ListForecastJobsRequest\x1a0.p9e.space.gipredict.v1.ListForecastJobsResponse\x12\x8a\x01\n" +
	"\x17UpdateForecastJobStatus\x126.p9e.space.gipredict.v1.UpdateForecastJobStatusRequest\x1a7.p9e.space.gipredict.v1.UpdateForecastJobStatusResponse\x12x\n" +
	"\x11CancelForecastJob\x120.p9e.space.gipredict.v1.CancelForecastJobRequest\x1a1.p9e.space.gipredict.v1.CancelForecastJobResponseB\xe7\x01\n" +
	"\x1acom.p9e.space.gipredict.v1B\x0eGiPredictProtoP\x01Z>github.com/ppusapati/space/services/gi-predict/api;gipredictv1\xa2\x02\x03PSG\xaa\x02\x16P9e.Space.Gipredict.V1\xca\x02\x16P9e\\Space\\Gipredict\\V1\xe2\x02\"P9e\\Space\\Gipredict\\V1\\GPBMetadata\xea\x02\x19P9e::Space::Gipredict::V1b\x06proto3"

var (
	file_gi_predict_proto_rawDescOnce sync.Once
	file_gi_predict_proto_rawDescData []byte
)

func file_gi_predict_proto_rawDescGZIP() []byte {
	file_gi_predict_proto_rawDescOnce.Do(func() {
		file_gi_predict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gi_predict_proto_rawDesc), len(file_gi_predict_proto_rawDesc)))
	})
	return file_gi_predict_proto_rawDescData
}

var file_gi_predict_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gi_predict_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gi_predict_proto_goTypes = []any{
	(ForecastType)(0),                       // 0: p9e.space.gipredict.v1.ForecastType
	(ForecastStatus)(0),                     // 1: p9e.space.gipredict.v1.ForecastStatus
	(*ForecastJob)(nil),                     // 2: p9e.space.gipredict.v1.ForecastJob
	(*SubmitForecastJobRequest)(nil),        // 3: p9e.space.gipredict.v1.SubmitForecastJobRequest
	(*SubmitForecastJobResponse)(nil),       // 4: p9e.space.gipredict.v1.SubmitForecastJobResponse
	(*GetForecastJobRequest)(nil),           // 5: p9e.space.gipredict.v1.GetForecastJobRequest
	(*GetForecastJobResponse)(nil),          // 6: p9e.space.gipredict.v1.GetForecastJobResponse
	(*ListForecastJobsRequest)(nil),         // 7: p9e.space.gipredict.v1.ListForecastJobsRequest
	(*ListForecastJobsResponse)(nil),        // 8: p9e.space.gipredict.v1.ListForecastJobsResponse
	(*UpdateForecastJobStatusRequest)(nil),  // 9: p9e.space.gipredict.v1.UpdateForecastJobStatusRequest
	(*UpdateForecastJobStatusResponse)(nil), // 10: p9e.space.gipredict.v1.UpdateForecastJobStatusResponse
	(*CancelForecastJobRequest)(nil),        // 11: p9e.space.gipredict.v1.CancelForecastJobRequest
	(*CancelForecastJobResponse)(nil),       // 12: p9e.space.gipredict.v1.CancelForecastJobResponse
	(*timestamppb.Timestamp)(nil),           // 13: google.protobuf.Timestamp
	(*fields.Fields)(nil),                   // 14: packages.api.v1.fields.Fields
	(*pagination.PaginationRequest)(nil),    // 15: packages.api.v1.pagination.PaginationRequest
	(*pagination.PaginationResponse)(nil),   // 16: packages.api.v1.pagination.PaginationResponse
}
var file_gi_predict_proto_depIdxs = []int32{
	0,  // 0: p9e.space.gipredict.v1.ForecastJob.type:type_name -> p9e.space.gipredict.v1.ForecastType
	1,  // 1: p9e.space.gipredict.v1.ForecastJob.status:type_name -> p9e.space.gipredict.v1.ForecastStatus
	13, // 2: p9e.space.gipredict.v1.ForecastJob.started_at:type_name -> google.protobuf.Timestamp
	13, // 3: p9e.space.gipredict.v1.ForecastJob.finished_at:type_name -> google.protobuf.Timestamp
	14, // 4: p9e.space.gipredict.v1.ForecastJob.fields:type_name -> packages.api.v1.fields.Fields
	0,  // 5: p9e.space.gipredict.v1.SubmitForecastJobRequest.type:type_name -> p9e.space.gipredict.v1.ForecastType
	2,  // 6: p9e.space.gipredict.v1.SubmitForecastJobResponse.job:type_name -> p9e.space.gipredict.v1.ForecastJob
	2,  // 7: p9e.space.gipredict.v1.GetForecastJobResponse.job:type_name -> p9e.space.gipredict.v1.ForecastJob
	1,  // 8: p9e.space.gipredict.v1.ListForecastJobsRequest.status:type_name -> p9e.space.gipredict.v1.ForecastStatus
	0,  // 9: p9e.space.gipredict.v1.ListForecastJobsRequest.type:type_name -> p9e.space.gipredict.v1.ForecastType
	15, // 10: p9e.space.gipredict.v1.ListForecastJobsRequest.page:type_name -> packages.api.v1.pagination.PaginationRequest
	2,  // 11: p9e.space.gipredict.v1.ListForecastJobsResponse.jobs:type_name -> p9e.space.gipredict.v1.ForecastJob
	16, // 12: p9e.space.gipredict.v1.ListForecastJobsResponse.page:type_name -> packages.api.v1.pagination.PaginationResponse
	1,  // 13: p9e.space.gipredict.v1.UpdateForecastJobStatusRequest.status:type_name -> p9e.space.gipredict.v1.ForecastStatus
	2,  // 14: p9e.space.gipredict.v1.UpdateForecastJobStatusResponse.job:type_name -> p9e.space.gipredict.v1.ForecastJob
	2,  // 15: p9e.space.gipredict.v1.CancelForecastJobResponse.job:type_name -> p9e.space.gipredict.v1.ForecastJob
	3,  // 16: p9e.space.gipredict.v1.ForecastService.SubmitForecastJob:input_type -> p9e.space.gipredict.v1.SubmitForecastJobRequest
	5,  // 17: p9e.space.gipredict.v1.ForecastService.GetForecastJob:input_type -> p9e.space.gipredict.v1.GetForecastJobRequest
	7,  // 18: p9e.space.gipredict.v1.ForecastService.ListForecastJobs:input_type -> p9e.space.gipredict.v1.ListForecastJobsRequest
	9,  // 19: p9e.space.gipredict.v1.ForecastService.UpdateForecastJobStatus:input_type -> p9e.space.gipredict.v1.UpdateForecastJobStatusRequest
	11, // 20: p9e.space.gipredict.v1.ForecastService.CancelForecastJob:input_type -> p9e.space.gipredict.v1.CancelForecastJobRequest
	4,  // 21: p9e.space.gipredict.v1.ForecastService.SubmitForecastJob:output_type -> p9e.space.gipredict.v1.SubmitForecastJobResponse
	6,  // 22: p9e.space.gipredict.v1.ForecastService.GetForecastJob:output_type -> p9e.space.gipredict.v1.GetForecastJobResponse
	8,  // 23: p9e.space.gipredict.v1.ForecastService.ListForecastJobs:output_type -> p9e.space.gipredict.v1.ListForecastJobsResponse
	10, // 24: p9e.space.gipredict.v1.ForecastService.UpdateForecastJobStatus:output_type -> p9e.space.gipredict.v1.UpdateForecastJobStatusResponse
	12, // 25: p9e.space.gipredict.v1.ForecastService.CancelForecastJob:output_type -> p9e.space.gipredict.v1.CancelForecastJobResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_gi_predict_proto_init() }
func file_gi_predict_proto_init() {
	if File_gi_predict_proto != nil {
		return
	}
	file_gi_predict_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gi_predict_proto_rawDesc), len(file_gi_predict_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gi_predict_proto_goTypes,
		DependencyIndexes: file_gi_predict_proto_depIdxs,
		EnumInfos:         file_gi_predict_proto_enumTypes,
		MessageInfos:      file_gi_predict_proto_msgTypes,
	}.Build()
	File_gi_predict_proto = out.File
	file_gi_predict_proto_goTypes = nil
	file_gi_predict_proto_depIdxs = nil
}
