// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gi_analytics.proto

package gianalyticsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/ppusapati/space/services/gi-analytics/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AnalyticsServiceName is the fully-qualified name of the AnalyticsService service.
	AnalyticsServiceName = "p9e.space.gianalytics.v1.AnalyticsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AnalyticsServiceSubmitAnalysisJobProcedure is the fully-qualified name of the AnalyticsService's
	// SubmitAnalysisJob RPC.
	AnalyticsServiceSubmitAnalysisJobProcedure = "/p9e.space.gianalytics.v1.AnalyticsService/SubmitAnalysisJob"
	// AnalyticsServiceGetAnalysisJobProcedure is the fully-qualified name of the AnalyticsService's
	// GetAnalysisJob RPC.
	AnalyticsServiceGetAnalysisJobProcedure = "/p9e.space.gianalytics.v1.AnalyticsService/GetAnalysisJob"
	// AnalyticsServiceListAnalysisJobsProcedure is the fully-qualified name of the AnalyticsService's
	// ListAnalysisJobs RPC.
	AnalyticsServiceListAnalysisJobsProcedure = "/p9e.space.gianalytics.v1.AnalyticsService/ListAnalysisJobs"
	// AnalyticsServiceUpdateAnalysisJobStatusProcedure is the fully-qualified name of the
	// AnalyticsService's UpdateAnalysisJobStatus RPC.
	AnalyticsServiceUpdateAnalysisJobStatusProcedure = "/p9e.space.gianalytics.v1.AnalyticsService/UpdateAnalysisJobStatus"
	// AnalyticsServiceCancelAnalysisJobProcedure is the fully-qualified name of the AnalyticsService's
	// CancelAnalysisJob RPC.
	AnalyticsServiceCancelAnalysisJobProcedure = "/p9e.space.gianalytics.v1.AnalyticsService/CancelAnalysisJob"
)

// AnalyticsServiceClient is a client for the p9e.space.gianalytics.v1.AnalyticsService service.
type AnalyticsServiceClient interface {
	SubmitAnalysisJob(context.Context, *connect.Request[api.SubmitAnalysisJobRequest]) (*connect.Response[api.SubmitAnalysisJobResponse], error)
	GetAnalysisJob(context.Context, *connect.Request[api.GetAnalysisJobRequest]) (*connect.Response[api.GetAnalysisJobResponse], error)
	ListAnalysisJobs(context.Context, *connect.Request[api.ListAnalysisJobsRequest]) (*connect.Response[api.ListAnalysisJobsResponse], error)
	UpdateAnalysisJobStatus(context.Context, *connect.Request[api.UpdateAnalysisJobStatusRequest]) (*connect.Response[api.UpdateAnalysisJobStatusResponse], error)
	CancelAnalysisJob(context.Context, *connect.Request[api.CancelAnalysisJobRequest]) (*connect.Response[api.CancelAnalysisJobResponse], error)
}

// NewAnalyticsServiceClient constructs a client for the p9e.space.gianalytics.v1.AnalyticsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnalyticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AnalyticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	analyticsServiceMethods := api.File_gi_analytics_proto.Services().ByName("AnalyticsService").Methods()
	return &analyticsServiceClient{
		submitAnalysisJob: connect.NewClient[api.SubmitAnalysisJobRequest, api.SubmitAnalysisJobResponse](
			httpClient,
			baseURL+AnalyticsServiceSubmitAnalysisJobProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("SubmitAnalysisJob")),
			connect.WithClientOptions(opts...),
		),
		getAnalysisJob: connect.NewClient[api.GetAnalysisJobRequest, api.GetAnalysisJobResponse](
			httpClient,
			baseURL+AnalyticsServiceGetAnalysisJobProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetAnalysisJob")),
			connect.WithClientOptions(opts...),
		),
		listAnalysisJobs: connect.NewClient[api.ListAnalysisJobsRequest, api.ListAnalysisJobsResponse](
			httpClient,
			baseURL+AnalyticsServiceListAnalysisJobsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("ListAnalysisJobs")),
			connect.WithClientOptions(opts...),
		),
		updateAnalysisJobStatus: connect.NewClient[api.UpdateAnalysisJobStatusRequest, api.UpdateAnalysisJobStatusResponse](
			httpClient,
			baseURL+AnalyticsServiceUpdateAnalysisJobStatusProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("UpdateAnalysisJobStatus")),
			connect.WithClientOptions(opts...),
		),
		cancelAnalysisJob: connect.NewClient[api.CancelAnalysisJobRequest, api.CancelAnalysisJobResponse](
			httpClient,
			baseURL+AnalyticsServiceCancelAnalysisJobProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("CancelAnalysisJob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// analyticsServiceClient implements AnalyticsServiceClient.
type analyticsServiceClient struct {
	submitAnalysisJob       *connect.Client[api.SubmitAnalysisJobRequest, api.SubmitAnalysisJobResponse]
	getAnalysisJob          *connect.Client[api.GetAnalysisJobRequest, api.GetAnalysisJobResponse]
	listAnalysisJobs        *connect.Client[api.ListAnalysisJobsRequest, api.ListAnalysisJobsResponse]
	updateAnalysisJobStatus *connect.Client[api.UpdateAnalysisJobStatusRequest, api.UpdateAnalysisJobStatusResponse]
	cancelAnalysisJob       *connect.Client[api.CancelAnalysisJobRequest, api.CancelAnalysisJobResponse]
}

// SubmitAnalysisJob calls p9e.space.gianalytics.v1.AnalyticsService.SubmitAnalysisJob.
func (c *analyticsServiceClient) SubmitAnalysisJob(ctx context.Context, req *connect.Request[api.SubmitAnalysisJobRequest]) (*connect.Response[api.SubmitAnalysisJobResponse], error) {
	return c.submitAnalysisJob.CallUnary(ctx, req)
}

// GetAnalysisJob calls p9e.space.gianalytics.v1.AnalyticsService.GetAnalysisJob.
func (c *analyticsServiceClient) GetAnalysisJob(ctx context.Context, req *connect.Request[api.GetAnalysisJobRequest]) (*connect.Response[api.GetAnalysisJobResponse], error) {
	return c.getAnalysisJob.CallUnary(ctx, req)
}

// ListAnalysisJobs calls p9e.space.gianalytics.v1.AnalyticsService.ListAnalysisJobs.
func (c *analyticsServiceClient) ListAnalysisJobs(ctx context.Context, req *connect.Request[api.ListAnalysisJobsRequest]) (*connect.Response[api.ListAnalysisJobsResponse], error) {
	return c.listAnalysisJobs.CallUnary(ctx, req)
}

// UpdateAnalysisJobStatus calls p9e.space.gianalytics.v1.AnalyticsService.UpdateAnalysisJobStatus.
func (c *analyticsServiceClient) UpdateAnalysisJobStatus(ctx context.Context, req *connect.Request[api.UpdateAnalysisJobStatusRequest]) (*connect.Response[api.UpdateAnalysisJobStatusResponse], error) {
	return c.updateAnalysisJobStatus.CallUnary(ctx, req)
}

// CancelAnalysisJob calls p9e.space.gianalytics.v1.AnalyticsService.CancelAnalysisJob.
func (c *analyticsServiceClient) CancelAnalysisJob(ctx context.Context, req *connect.Request[api.CancelAnalysisJobRequest]) (*connect.Response[api.CancelAnalysisJobResponse], error) {
	return c.cancelAnalysisJob.CallUnary(ctx, req)
}

// AnalyticsServiceHandler is an implementation of the p9e.space.gianalytics.v1.AnalyticsService
// service.
type AnalyticsServiceHandler interface {
	SubmitAnalysisJob(context.Context, *connect.Request[api.SubmitAnalysisJobRequest]) (*connect.Response[api.SubmitAnalysisJobResponse], error)
	GetAnalysisJob(context.Context, *connect.Request[api.GetAnalysisJobRequest]) (*connect.Response[api.GetAnalysisJobResponse], error)
	ListAnalysisJobs(context.Context, *connect.Request[api.ListAnalysisJobsRequest]) (*connect.Response[api.ListAnalysisJobsResponse], error)
	UpdateAnalysisJobStatus(context.Context, *connect.Request[api.UpdateAnalysisJobStatusRequest]) (*connect.Response[api.UpdateAnalysisJobStatusResponse], error)
	CancelAnalysisJob(context.Context, *connect.Request[api.CancelAnalysisJobRequest]) (*connect.Response[api.CancelAnalysisJobResponse], error)
}

// NewAnalyticsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnalyticsServiceHandler(svc AnalyticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	analyticsServiceMethods := api.File_gi_analytics_proto.Services().ByName("AnalyticsService").Methods()
	analyticsServiceSubmitAnalysisJobHandler := connect.NewUnaryHandler(
		AnalyticsServiceSubmitAnalysisJobProcedure,
		svc.SubmitAnalysisJob,
		connect.WithSchema(analyticsServiceMethods.ByName("SubmitAnalysisJob")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetAnalysisJobHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetAnalysisJobProcedure,
		svc.GetAnalysisJob,
		connect.WithSchema(analyticsServiceMethods.ByName("GetAnalysisJob")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceListAnalysisJobsHandler := connect.NewUnaryHandler(
		AnalyticsServiceListAnalysisJobsProcedure,
		svc.ListAnalysisJobs,
		connect.WithSchema(analyticsServiceMethods.ByName("ListAnalysisJobs")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceUpdateAnalysisJobStatusHandler := connect.NewUnaryHandler(
		AnalyticsServiceUpdateAnalysisJobStatusProcedure,
		svc.UpdateAnalysisJobStatus,
		connect.WithSchema(analyticsServiceMethods.ByName("UpdateAnalysisJobStatus")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceCancelAnalysisJobHandler := connect.NewUnaryHandler(
		AnalyticsServiceCancelAnalysisJobProcedure,
		svc.CancelAnalysisJob,
		connect.WithSchema(analyticsServiceMethods.ByName("CancelAnalysisJob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/p9e.space.gianalytics.v1.AnalyticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnalyticsServiceSubmitAnalysisJobProcedure:
			analyticsServiceSubmitAnalysisJobHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetAnalysisJobProcedure:
			analyticsServiceGetAnalysisJobHandler.ServeHTTP(w, r)
		case AnalyticsServiceListAnalysisJobsProcedure:
			analyticsServiceListAnalysisJobsHandler.ServeHTTP(w, r)
		case AnalyticsServiceUpdateAnalysisJobStatusProcedure:
			analyticsServiceUpdateAnalysisJobStatusHandler.ServeHTTP(w, r)
		case AnalyticsServiceCancelAnalysisJobProcedure:
			analyticsServiceCancelAnalysisJobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnalyticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAnalyticsServiceHandler struct{}

func (UnimplementedAnalyticsServiceHandler) SubmitAnalysisJob(context.Context, *connect.Request[api.SubmitAnalysisJobRequest]) (*connect.Response[api.SubmitAnalysisJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gianalytics.v1.AnalyticsService.SubmitAnalysisJob is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetAnalysisJob(context.Context, *connect.Request[api.GetAnalysisJobRequest]) (*connect.Response[api.GetAnalysisJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gianalytics.v1.AnalyticsService.GetAnalysisJob is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) ListAnalysisJobs(context.Context, *connect.Request[api.ListAnalysisJobsRequest]) (*connect.Response[api.ListAnalysisJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gianalytics.v1.AnalyticsService.ListAnalysisJobs is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) UpdateAnalysisJobStatus(context.Context, *connect.Request[api.UpdateAnalysisJobStatusRequest]) (*connect.Response[api.UpdateAnalysisJobStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gianalytics.v1.AnalyticsService.UpdateAnalysisJobStatus is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) CancelAnalysisJob(context.Context, *connect.Request[api.CancelAnalysisJobRequest]) (*connect.Response[api.CancelAnalysisJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gianalytics.v1.AnalyticsService.CancelAnalysisJob is not implemented"))
}
