// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gi_predict.proto

package gipredictv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/ppusapati/space/services/gi-predict/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ForecastServiceName is the fully-qualified name of the ForecastService service.
	ForecastServiceName = "p9e.space.gipredict.v1.ForecastService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ForecastServiceSubmitForecastJobProcedure is the fully-qualified name of the ForecastService's
	// SubmitForecastJob RPC.
	ForecastServiceSubmitForecastJobProcedure = "/p9e.space.gipredict.v1.ForecastService/SubmitForecastJob"
	// ForecastServiceGetForecastJobProcedure is the fully-qualified name of the ForecastService's
	// GetForecastJob RPC.
	ForecastServiceGetForecastJobProcedure = "/p9e.space.gipredict.v1.ForecastService/GetForecastJob"
	// ForecastServiceListForecastJobsProcedure is the fully-qualified name of the ForecastService's
	// ListForecastJobs RPC.
	ForecastServiceListForecastJobsProcedure = "/p9e.space.gipredict.v1.ForecastService/ListForecastJobs"
	// ForecastServiceUpdateForecastJobStatusProcedure is the fully-qualified name of the
	// ForecastService's UpdateForecastJobStatus RPC.
	ForecastServiceUpdateForecastJobStatusProcedure = "/p9e.space.gipredict.v1.ForecastService/UpdateForecastJobStatus"
	// ForecastServiceCancelForecastJobProcedure is the fully-qualified name of the ForecastService's
	// CancelForecastJob RPC.
	ForecastServiceCancelForecastJobProcedure = "/p9e.space.gipredict.v1.ForecastService/CancelForecastJob"
)

// ForecastServiceClient is a client for the p9e.space.gipredict.v1.ForecastService service.
type ForecastServiceClient interface {
	SubmitForecastJob(context.Context, *connect.Request[api.SubmitForecastJobRequest]) (*connect.Response[api.SubmitForecastJobResponse], error)
	GetForecastJob(context.Context, *connect.Request[api.GetForecastJobRequest]) (*connect.Response[api.GetForecastJobResponse], error)
	ListForecastJobs(context.Context, *connect.Request[api.ListForecastJobsRequest]) (*connect.Response[api.ListForecastJobsResponse], error)
	UpdateForecastJobStatus(context.Context, *connect.Request[api.UpdateForecastJobStatusRequest]) (*connect.Response[api.UpdateForecastJobStatusResponse], error)
	CancelForecastJob(context.Context, *connect.Request[api.CancelForecastJobRequest]) (*connect.Response[api.CancelForecastJobResponse], error)
}

// NewForecastServiceClient constructs a client for the p9e.space.gipredict.v1.ForecastService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewForecastServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ForecastServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	forecastServiceMethods := api.File_gi_predict_proto.Services().ByName("ForecastService").Methods()
	return &forecastServiceClient{
		submitForecastJob: connect.NewClient[api.SubmitForecastJobRequest, api.SubmitForecastJobResponse](
			httpClient,
			baseURL+ForecastServiceSubmitForecastJobProcedure,
			connect.WithSchema(forecastServiceMethods.ByName("SubmitForecastJob")),
			connect.WithClientOptions(opts...),
		),
		getForecastJob: connect.NewClient[api.GetForecastJobRequest, api.GetForecastJobResponse](
			httpClient,
			baseURL+ForecastServiceGetForecastJobProcedure,
			connect.WithSchema(forecastServiceMethods.ByName("GetForecastJob")),
			connect.WithClientOptions(opts...),
		),
		listForecastJobs: connect.NewClient[api.ListForecastJobsRequest, api.ListForecastJobsResponse](
			httpClient,
			baseURL+ForecastServiceListForecastJobsProcedure,
			connect.WithSchema(forecastServiceMethods.ByName("ListForecastJobs")),
			connect.WithClientOptions(opts...),
		),
		updateForecastJobStatus: connect.NewClient[api.UpdateForecastJobStatusRequest, api.UpdateForecastJobStatusResponse](
			httpClient,
			baseURL+ForecastServiceUpdateForecastJobStatusProcedure,
			connect.WithSchema(forecastServiceMethods.ByName("UpdateForecastJobStatus")),
			connect.WithClientOptions(opts...),
		),
		cancelForecastJob: connect.NewClient[api.CancelForecastJobRequest, api.CancelForecastJobResponse](
			httpClient,
			baseURL+ForecastServiceCancelForecastJobProcedure,
			connect.WithSchema(forecastServiceMethods.ByName("CancelForecastJob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// forecastServiceClient implements ForecastServiceClient.
type forecastServiceClient struct {
	submitForecastJob       *connect.Client[api.SubmitForecastJobRequest, api.SubmitForecastJobResponse]
	getForecastJob          *connect.Client[api.GetForecastJobRequest, api.GetForecastJobResponse]
	listForecastJobs        *connect.Client[api.ListForecastJobsRequest, api.ListForecastJobsResponse]
	updateForecastJobStatus *connect.Client[api.UpdateForecastJobStatusRequest, api.UpdateForecastJobStatusResponse]
	cancelForecastJob       *connect.Client[api.CancelForecastJobRequest, api.CancelForecastJobResponse]
}

// SubmitForecastJob calls p9e.space.gipredict.v1.ForecastService.SubmitForecastJob.
func (c *forecastServiceClient) SubmitForecastJob(ctx context.Context, req *connect.Request[api.SubmitForecastJobRequest]) (*connect.Response[api.SubmitForecastJobResponse], error) {
	return c.submitForecastJob.CallUnary(ctx, req)
}

// GetForecastJob calls p9e.space.gipredict.v1.ForecastService.GetForecastJob.
func (c *forecastServiceClient) GetForecastJob(ctx context.Context, req *connect.Request[api.GetForecastJobRequest]) (*connect.Response[api.GetForecastJobResponse], error) {
	return c.getForecastJob.CallUnary(ctx, req)
}

// ListForecastJobs calls p9e.space.gipredict.v1.ForecastService.ListForecastJobs.
func (c *forecastServiceClient) ListForecastJobs(ctx context.Context, req *connect.Request[api.ListForecastJobsRequest]) (*connect.Response[api.ListForecastJobsResponse], error) {
	return c.listForecastJobs.CallUnary(ctx, req)
}

// UpdateForecastJobStatus calls p9e.space.gipredict.v1.ForecastService.UpdateForecastJobStatus.
func (c *forecastServiceClient) UpdateForecastJobStatus(ctx context.Context, req *connect.Request[api.UpdateForecastJobStatusRequest]) (*connect.Response[api.UpdateForecastJobStatusResponse], error) {
	return c.updateForecastJobStatus.CallUnary(ctx, req)
}

// CancelForecastJob calls p9e.space.gipredict.v1.ForecastService.CancelForecastJob.
func (c *forecastServiceClient) CancelForecastJob(ctx context.Context, req *connect.Request[api.CancelForecastJobRequest]) (*connect.Response[api.CancelForecastJobResponse], error) {
	return c.cancelForecastJob.CallUnary(ctx, req)
}

// ForecastServiceHandler is an implementation of the p9e.space.gipredict.v1.ForecastService
// service.
type ForecastServiceHandler interface {
	SubmitForecastJob(context.Context, *connect.Request[api.SubmitForecastJobRequest]) (*connect.Response[api.SubmitForecastJobResponse], error)
	GetForecastJob(context.Context, *connect.Request[api.GetForecastJobRequest]) (*connect.Response[api.GetForecastJobResponse], error)
	ListForecastJobs(context.Context, *connect.Request[api.ListForecastJobsRequest]) (*connect.Response[api.ListForecastJobsResponse], error)
	UpdateForecastJobStatus(context.Context, *connect.Request[api.UpdateForecastJobStatusRequest]) (*connect.Response[api.UpdateForecastJobStatusResponse], error)
	CancelForecastJob(context.Context, *connect.Request[api.CancelForecastJobRequest]) (*connect.Response[api.CancelForecastJobResponse], error)
}

// NewForecastServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewForecastServiceHandler(svc ForecastServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	forecastServiceMethods := api.File_gi_predict_proto.Services().ByName("ForecastService").Methods()
	forecastServiceSubmitForecastJobHandler := connect.NewUnaryHandler(
		ForecastServiceSubmitForecastJobProcedure,
		svc.SubmitForecastJob,
		connect.WithSchema(forecastServiceMethods.ByName("SubmitForecastJob")),
		connect.WithHandlerOptions(opts...),
	)
	forecastServiceGetForecastJobHandler := connect.NewUnaryHandler(
		ForecastServiceGetForecastJobProcedure,
		svc.GetForecastJob,
		connect.WithSchema(forecastServiceMethods.ByName("GetForecastJob")),
		connect.WithHandlerOptions(opts...),
	)
	forecastServiceListForecastJobsHandler := connect.NewUnaryHandler(
		ForecastServiceListForecastJobsProcedure,
		svc.ListForecastJobs,
		connect.WithSchema(forecastServiceMethods.ByName("ListForecastJobs")),
		connect.WithHandlerOptions(opts...),
	)
	forecastServiceUpdateForecastJobStatusHandler := connect.NewUnaryHandler(
		ForecastServiceUpdateForecastJobStatusProcedure,
		svc.UpdateForecastJobStatus,
		connect.WithSchema(forecastServiceMethods.ByName("UpdateForecastJobStatus")),
		connect.WithHandlerOptions(opts...),
	)
	forecastServiceCancelForecastJobHandler := connect.NewUnaryHandler(
		ForecastServiceCancelForecastJobProcedure,
		svc.CancelForecastJob,
		connect.WithSchema(forecastServiceMethods.ByName("CancelForecastJob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/p9e.space.gipredict.v1.ForecastService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ForecastServiceSubmitForecastJobProcedure:
			forecastServiceSubmitForecastJobHandler.ServeHTTP(w, r)
		case ForecastServiceGetForecastJobProcedure:
			forecastServiceGetForecastJobHandler.ServeHTTP(w, r)
		case ForecastServiceListForecastJobsProcedure:
			forecastServiceListForecastJobsHandler.ServeHTTP(w, r)
		case ForecastServiceUpdateForecastJobStatusProcedure:
			forecastServiceUpdateForecastJobStatusHandler.ServeHTTP(w, r)
		case ForecastServiceCancelForecastJobProcedure:
			forecastServiceCancelForecastJobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedForecastServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedForecastServiceHandler struct{}

func (UnimplementedForecastServiceHandler) SubmitForecastJob(context.Context, *connect.Request[api.SubmitForecastJobRequest]) (*connect.Response[api.SubmitForecastJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gipredict.v1.ForecastService.SubmitForecastJob is not implemented"))
}

func (UnimplementedForecastServiceHandler) GetForecastJob(context.Context, *connect.Request[api.GetForecastJobRequest]) (*connect.Response[api.GetForecastJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gipredict.v1.ForecastService.GetForecastJob is not implemented"))
}

func (UnimplementedForecastServiceHandler) ListForecastJobs(context.Context, *connect.Request[api.ListForecastJobsRequest]) (*connect.Response[api.ListForecastJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gipredict.v1.ForecastService.ListForecastJobs is not implemented"))
}

func (UnimplementedForecastServiceHandler) UpdateForecastJobStatus(context.Context, *connect.Request[api.UpdateForecastJobStatusRequest]) (*connect.Response[api.UpdateForecastJobStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gipredict.v1.ForecastService.UpdateForecastJobStatus is not implemented"))
}

func (UnimplementedForecastServiceHandler) CancelForecastJob(context.Context, *connect.Request[api.CancelForecastJobRequest]) (*connect.Response[api.CancelForecastJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.gipredict.v1.ForecastService.CancelForecastJob is not implemented"))
}
