// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eo_catalog.proto

package eocatalogv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	fields "p9e.in/samavaya/packages/api/v1/fields"
	pagination "p9e.in/samavaya/packages/api/v1/pagination"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bounding box (lon_min, lat_min, lon_max, lat_max).
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LonMin        float64                `protobuf:"fixed64,1,opt,name=lon_min,json=lonMin,proto3" json:"lon_min,omitempty"`
	LatMin        float64                `protobuf:"fixed64,2,opt,name=lat_min,json=latMin,proto3" json:"lat_min,omitempty"`
	LonMax        float64                `protobuf:"fixed64,3,opt,name=lon_max,json=lonMax,proto3" json:"lon_max,omitempty"`
	LatMax        float64                `protobuf:"fixed64,4,opt,name=lat_max,json=latMax,proto3" json:"lat_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_eo_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *BoundingBox) GetLonMin() float64 {
	if x != nil {
		return x.LonMin
	}
	return 0
}

func (x *BoundingBox) GetLatMin() float64 {
	if x != nil {
		return x.LatMin
	}
	return 0
}

func (x *BoundingBox) GetLonMax() float64 {
	if x != nil {
		return x.LonMax
	}
	return 0
}

func (x *BoundingBox) GetLatMax() float64 {
	if x != nil {
		return x.LatMax
	}
	return 0
}

// A STAC Collection.
type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                             // ULID
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // ULID
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`                         // url-safe stable id
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	License       string                 `protobuf:"bytes,6,opt,name=license,proto3" json:"license,omitempty"`
	SpatialExtent *BoundingBox           `protobuf:"bytes,7,opt,name=spatial_extent,json=spatialExtent,proto3" json:"spatial_extent,omitempty"`
	TemporalStart *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=temporal_start,json=temporalStart,proto3" json:"temporal_start,omitempty"`
	TemporalEnd   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=temporal_end,json=temporalEnd,proto3" json:"temporal_end,omitempty"`
	Fields        *fields.Fields         `protobuf:"bytes,10,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_eo_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Collection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collection) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Collection) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Collection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Collection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Collection) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *Collection) GetSpatialExtent() *BoundingBox {
	if x != nil {
		return x.SpatialExtent
	}
	return nil
}

func (x *Collection) GetTemporalStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TemporalStart
	}
	return nil
}

func (x *Collection) GetTemporalEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TemporalEnd
	}
	return nil
}

func (x *Collection) GetFields() *fields.Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

// One asset inside an Item — a single COG band on object storage.
type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                              // band id, e.g. "B04"
	Href          string                 `protobuf:"bytes,2,opt,name=href,proto3" json:"href,omitempty"`                            // s3:// or https:// URI
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"` // e.g. "image/tiff; application=geotiff; profile=cloud-optimized"
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_eo_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Asset) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Asset) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *Asset) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Asset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Asset) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// A STAC Item — one scene.
type Item struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectionId    string                 `protobuf:"bytes,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Mission         string                 `protobuf:"bytes,4,opt,name=mission,proto3" json:"mission,omitempty"`
	Platform        string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Instrument      string                 `protobuf:"bytes,6,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Datetime        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Bbox            *BoundingBox           `protobuf:"bytes,8,opt,name=bbox,proto3" json:"bbox,omitempty"`
	GeometryGeojson string                 `protobuf:"bytes,9,opt,name=geometry_geojson,json=geometryGeojson,proto3" json:"geometry_geojson,omitempty"`
	CloudCover      float64                `protobuf:"fixed64,10,opt,name=cloud_cover,json=cloudCover,proto3" json:"cloud_cover,omitempty"`
	PropertiesJson  string                 `protobuf:"bytes,11,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"`
	Assets          []*Asset               `protobuf:"bytes,12,rep,name=assets,proto3" json:"assets,omitempty"`
	Fields          *fields.Fields         `protobuf:"bytes,13,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_eo_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Item) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *Item) GetMission() string {
	if x != nil {
		return x.Mission
	}
	return ""
}

func (x *Item) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Item) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *Item) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *Item) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Item) GetGeometryGeojson() string {
	if x != nil {
		return x.GeometryGeojson
	}
	return ""
}

func (x *Item) GetCloudCover() float64 {
	if x != nil {
		return x.CloudCover
	}
	return 0
}

func (x *Item) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

func (x *Item) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *Item) GetFields() *fields.Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Quality assessment result emitted by the QA stage.
type QualityResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId             string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	CloudCover         float64                `protobuf:"fixed64,3,opt,name=cloud_cover,json=cloudCover,proto3" json:"cloud_cover,omitempty"` // 0..1 fraction
	RadiometricRmse    float64                `protobuf:"fixed64,4,opt,name=radiometric_rmse,json=radiometricRmse,proto3" json:"radiometric_rmse,omitempty"`
	GeometricAccuracyM float64                `protobuf:"fixed64,5,opt,name=geometric_accuracy_m,json=geometricAccuracyM,proto3" json:"geometric_accuracy_m,omitempty"`
	Notes              string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	ComputedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QualityResult) Reset() {
	*x = QualityResult{}
	mi := &file_eo_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityResult) ProtoMessage() {}

func (x *QualityResult) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityResult.ProtoReflect.Descriptor instead.
func (*QualityResult) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *QualityResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QualityResult) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *QualityResult) GetCloudCover() float64 {
	if x != nil {
		return x.CloudCover
	}
	return 0
}

func (x *QualityResult) GetRadiometricRmse() float64 {
	if x != nil {
		return x.RadiometricRmse
	}
	return 0
}

func (x *QualityResult) GetGeometricAccuracyM() float64 {
	if x != nil {
		return x.GeometricAccuracyM
	}
	return 0
}

func (x *QualityResult) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *QualityResult) GetComputedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ComputedAt
	}
	return nil
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	License       string                 `protobuf:"bytes,5,opt,name=license,proto3" json:"license,omitempty"`
	SpatialExtent *BoundingBox           `protobuf:"bytes,6,opt,name=spatial_extent,json=spatialExtent,proto3" json:"spatial_extent,omitempty"`
	TemporalStart *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=temporal_start,json=temporalStart,proto3" json:"temporal_start,omitempty"`
	TemporalEnd   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=temporal_end,json=temporalEnd,proto3" json:"temporal_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_eo_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCollectionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateCollectionRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateCollectionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCollectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCollectionRequest) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *CreateCollectionRequest) GetSpatialExtent() *BoundingBox {
	if x != nil {
		return x.SpatialExtent
	}
	return nil
}

func (x *CreateCollectionRequest) GetTemporalStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TemporalStart
	}
	return nil
}

func (x *CreateCollectionRequest) GetTemporalEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TemporalEnd
	}
	return nil
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_eo_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_eo_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	mi := &file_eo_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *GetCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	TenantId      string                        `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          *pagination.PaginationRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_eo_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *ListCollectionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListCollectionsRequest) GetPage() *pagination.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Collections   []*Collection                  `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	Page          *pagination.PaginationResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_eo_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *ListCollectionsResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *ListCollectionsResponse) GetPage() *pagination.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_eo_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionResponse) Reset() {
	*x = DeleteCollectionResponse{}
	mi := &file_eo_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionResponse) ProtoMessage() {}

func (x *DeleteCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCollectionResponse) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{12}
}

type CreateItemRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectionId    string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Mission         string                 `protobuf:"bytes,3,opt,name=mission,proto3" json:"mission,omitempty"`
	Platform        string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Instrument      string                 `protobuf:"bytes,5,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Datetime        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Bbox            *BoundingBox           `protobuf:"bytes,7,opt,name=bbox,proto3" json:"bbox,omitempty"`
	GeometryGeojson string                 `protobuf:"bytes,8,opt,name=geometry_geojson,json=geometryGeojson,proto3" json:"geometry_geojson,omitempty"`
	CloudCover      float64                `protobuf:"fixed64,9,opt,name=cloud_cover,json=cloudCover,proto3" json:"cloud_cover,omitempty"`
	PropertiesJson  string                 `protobuf:"bytes,10,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_eo_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *CreateItemRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateItemRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CreateItemRequest) GetMission() string {
	if x != nil {
		return x.Mission
	}
	return ""
}

func (x *CreateItemRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateItemRequest) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *CreateItemRequest) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *CreateItemRequest) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *CreateItemRequest) GetGeometryGeojson() string {
	if x != nil {
		return x.GeometryGeojson
	}
	return ""
}

func (x *CreateItemRequest) GetCloudCover() float64 {
	if x != nil {
		return x.CloudCover
	}
	return 0
}

func (x *CreateItemRequest) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_eo_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *CreateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_eo_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_eo_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListItemsRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	TenantId      string                        `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectionId  string                        `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // optional
	Page          *pagination.PaginationRequest `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_eo_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *ListItemsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListItemsRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ListItemsRequest) GetPage() *pagination.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListItemsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Items         []*Item                        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          *pagination.PaginationResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_eo_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListItemsResponse) GetPage() *pagination.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type AddAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Asset         *Asset                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAssetRequest) Reset() {
	*x = AddAssetRequest{}
	mi := &file_eo_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAssetRequest) ProtoMessage() {}

func (x *AddAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAssetRequest.ProtoReflect.Descriptor instead.
func (*AddAssetRequest) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *AddAssetRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AddAssetRequest) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type AddAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAssetResponse) Reset() {
	*x = AddAssetResponse{}
	mi := &file_eo_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAssetResponse) ProtoMessage() {}

func (x *AddAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAssetResponse.ProtoReflect.Descriptor instead.
func (*AddAssetResponse) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *AddAssetResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type RecordQualityResultRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ItemId             string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	CloudCover         float64                `protobuf:"fixed64,2,opt,name=cloud_cover,json=cloudCover,proto3" json:"cloud_cover,omitempty"`
	RadiometricRmse    float64                `protobuf:"fixed64,3,opt,name=radiometric_rmse,json=radiometricRmse,proto3" json:"radiometric_rmse,omitempty"`
	GeometricAccuracyM float64                `protobuf:"fixed64,4,opt,name=geometric_accuracy_m,json=geometricAccuracyM,proto3" json:"geometric_accuracy_m,omitempty"`
	Notes              string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordQualityResultRequest) Reset() {
	*x = RecordQualityResultRequest{}
	mi := &file_eo_catalog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordQualityResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordQualityResultRequest) ProtoMessage() {}

func (x *RecordQualityResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordQualityResultRequest.ProtoReflect.Descriptor instead.
func (*RecordQualityResultRequest) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{21}
}

func (x *RecordQualityResultRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RecordQualityResultRequest) GetCloudCover() float64 {
	if x != nil {
		return x.CloudCover
	}
	return 0
}

func (x *RecordQualityResultRequest) GetRadiometricRmse() float64 {
	if x != nil {
		return x.RadiometricRmse
	}
	return 0
}

func (x *RecordQualityResultRequest) GetGeometricAccuracyM() float64 {
	if x != nil {
		return x.GeometricAccuracyM
	}
	return 0
}

func (x *RecordQualityResultRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type RecordQualityResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *QualityResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordQualityResultResponse) Reset() {
	*x = RecordQualityResultResponse{}
	mi := &file_eo_catalog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordQualityResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordQualityResultResponse) ProtoMessage() {}

func (x *RecordQualityResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eo_catalog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordQualityResultResponse.ProtoReflect.Descriptor instead.
func (*RecordQualityResultResponse) Descriptor() ([]byte, []int) {
	return file_eo_catalog_proto_rawDescGZIP(), []int{22}
}

func (x *RecordQualityResultResponse) GetResult() *QualityResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_eo_catalog_proto protoreflect.FileDescriptor

const file_eo_catalog_proto_rawDesc = "" +
	"\n" +
	"\x10eo_catalog.proto\x12\x16p9e.space.eocatalog.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\ffields.proto\x1a\x10pagination.proto\"q\n" +
	"\vBoundingBox\x12\x17\n" +
	"\alon_min\x18\x01 \x01(\x01R\x06lonMin\x12\x17\n" +
	"\alat_min\x18\x02 \x01(\x01R\x06latMin\x12\x17\n" +
	"\alon_max\x18\x03 \x01(\x01R\x06lonMax\x12\x17\n" +
	"\alat_max\x18\x04 \x01(\x01R\x06latMax\"\xa5\x03\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\alicense\x18\x06 \x01(\tR\alicense\x12J\n" +
	"\x0espatial_extent\x18\a \x01(\v2#.p9e.space.eocatalog.v1.BoundingBoxR\rspatialExtent\x12A\n" +
	"\x0etemporal_start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rtemporalStart\x12=\n" +
	"\ftemporal_end\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vtemporalEnd\x126\n" +
	"\x06fields\x18\n" +
	" \x01(\v2\x1e.packages.api.v1.fields.FieldsR\x06fields\"x\n" +
	"\x05Asset\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04href\x18\x02 \x01(\tR\x04href\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\"\x83\x04\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12#\n" +
	"\rcollection_id\x18\x03 \x01(\tR\fcollectionId\x12\x18\n" +
	"\amission\x18\x04 \x01(\tR\amission\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x1e\n" +
	"\n" +
	"instrument\x18\x06 \x01(\tR\n" +
	"instrument\x126\n" +
	"\bdatetime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x127\n" +
	"\x04bbox\x18\b \x01(\v2#.p9e.space.eocatalog.v1.BoundingBoxR\x04bbox\x12)\n" +
	"\x10geometry_geojson\x18\t \x01(\tR\x0fgeometryGeojson\x12\x1f\n" +
	"\vcloud_cover\x18\n" +
	" \x01(\x01R\n" +
	"cloudCover\x12'\n" +
	"\x0fproperties_json\x18\v \x01(\tR\x0epropertiesJson\x125\n" +
	"\x06assets\x18\f \x03(\v2\x1d.p9e.space.eocatalog.v1.AssetR\x06assets\x126\n" +
	"\x06fields\x18\r \x01(\v2\x1e.packages.api.v1.fields.FieldsR\x06fields\"\x89\x02\n" +
	"\rQualityResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1f\n" +
	"\vcloud_cover\x18\x03 \x01(\x01R\n" +
	"cloudCover\x12)\n" +
	"\x10radiometric_rmse\x18\x04 \x01(\x01R\x0fradiometricRmse\x120\n" +
	"\x14geometric_accuracy_m\x18\x05 \x01(\x01R\x12geometricAccuracyM\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x12;\n" +
	"\vcomputed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"computedAt\"\xaa\x03\n" +
	"\x17CreateCollectionRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12<\n" +
	"\x04slug\x18\x02 \x01(\tB(\xbaH%r#2!^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$R\x04slug\x12 \n" +
	"\x05title\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01R\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\alicense\x18\x05 \x01(\tR\alicense\x12J\n" +
	"\x0espatial_extent\x18\x06 \x01(\v2#.p9e.space.eocatalog.v1.BoundingBoxR\rspatialExtent\x12A\n" +
	"\x0etemporal_start\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rtemporalStart\x12=\n" +
	"\ftemporal_end\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vtemporalEnd\"^\n" +
	"\x18CreateCollectionResponse\x12B\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\".p9e.space.eocatalog.v1.CollectionR\n" +
	"collection\"0\n" +
	"\x14GetCollectionRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\"[\n" +
	"\x15GetCollectionResponse\x12B\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\".p9e.space.eocatalog.v1.CollectionR\n" +
	"collection\"\x82\x01\n" +
	"\x16ListCollectionsRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12A\n" +
	"\x04page\x18\x02 \x01(\v2-.packages.api.v1.pagination.PaginationRequestR\x04page\"\xa3\x01\n" +
	"\x17ListCollectionsResponse\x12D\n" +
	"\vcollections\x18\x01 \x03(\v2\".p9e.space.eocatalog.v1.CollectionR\vcollections\x12B\n" +
	"\x04page\x18\x02 \x01(\v2..packages.api.v1.pagination.PaginationResponseR\x04page\"3\n" +
	"\x17DeleteCollectionRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\"\x1a\n" +
	"\x18DeleteCollectionResponse\"\xc9\x03\n" +
	"\x11CreateItemRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12-\n" +
	"\rcollection_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\fcollectionId\x12#\n" +
	"\amission\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\amission\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1e\n" +
	"\n" +
	"instrument\x18\x05 \x01(\tR\n" +
	"instrument\x126\n" +
	"\bdatetime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x127\n" +
	"\x04bbox\x18\a \x01(\v2#.p9e.space.eocatalog.v1.BoundingBoxR\x04bbox\x12)\n" +
	"\x10geometry_geojson\x18\b \x01(\tR\x0fgeometryGeojson\x128\n" +
	"\vcloud_cover\x18\t \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00Y@)\x00\x00\x00\x00\x00\x00\x00\x00R\n" +
	"cloudCover\x12'\n" +
	"\x0fproperties_json\x18\n" +
	" \x01(\tR\x0epropertiesJson\"F\n" +
	"\x12CreateItemResponse\x120\n" +
	"\x04item\x18\x01 \x01(\v2\x1c.p9e.space.eocatalog.v1.ItemR\x04item\"*\n" +
	"\x0eGetItemRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\"C\n" +
	"\x0fGetItemResponse\x120\n" +
	"\x04item\x18\x01 \x01(\v2\x1c.p9e.space.eocatalog.v1.ItemR\x04item\"\xa1\x01\n" +
	"\x10ListItemsRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12A\n" +
	"\x04page\x18\x03 \x01(\v2-.packages.api.v1.pagination.PaginationRequestR\x04page\"\x8b\x01\n" +
	"\x11ListItemsResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.p9e.space.eocatalog.v1.ItemR\x05items\x12B\n" +
	"\x04page\x18\x02 \x01(\v2..packages.api.v1.pagination.PaginationResponseR\x04page\"i\n" +
	"\x0fAddAssetRequest\x12!\n" +
	"\aitem_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x06itemId\x123\n" +
	"\x05asset\x18\x02 \x01(\v2\x1d.p9e.space.eocatalog.v1.AssetR\x05asset\"D\n" +
	"\x10AddAssetResponse\x120\n" +
	"\x04item\x18\x01 \x01(\v2\x1c.p9e.space.eocatalog.v1.ItemR\x04item\"\xec\x01\n" +
	"\x1aRecordQualityResultRequest\x12!\n" +
	"\aitem_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x06itemId\x128\n" +
	"\vcloud_cover\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00R\n" +
	"cloudCover\x12)\n" +
	"\x10radiometric_rmse\x18\x03 \x01(\x01R\x0fradiometricRmse\x120\n" +
	"\x14geometric_accuracy_m\x18\x04 \x01(\x01R\x12geometricAccuracyM\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\\\n" +
	"\x1bRecordQualityResultResponse\x12=\n" +
	"\x06result\x18\x01 \x01(\v2%.p9e.space.eocatalog.v1.QualityResultR\x06result2\xe2\a\n" +
	"\x0eCatalogService\x12u\n" +
	"\x10CreateCollection\x12/.p9e.space.eocatalog.v1.CreateCollectionRequest\x1a0.p9e.space.eocatalog.v1.CreateCollectionResponse\x12l\n" +
	"\rGetCollection\x12,.p9e.space.eocatalog.v1.GetCollectionRequest\x1a-.p9e.space.eocatalog.v1.GetCollectionResponse\x12r\n" +
	"\x0fListCollections\x12..p9e.space.eocatalog.v1.ListCollectionsRequest\x1a/.p9e.space.eocatalog.v1.ListCollectionsResponse\x12u\n" +
	"\x10DeleteCollection\x12/.p9e.space.eocatalog.v1.DeleteCollectionRequest\x1a0.p9e.space.eocatalog.v1.DeleteCollectionResponse\x12c\n" +
	"\n" +
	"CreateItem\x12).p9e.space.eocatalog.v1.CreateItemRequest\x1a*.p9e.space.eocatalog.v1.CreateItemResponse\x12Z\n" +
	"\aGetItem\x12&.p9e.space.eocatalog.v1.GetItemRequest\x1a'.p9e.space.eocatalog.v1.GetItemResponse\x12`\n" +
	"\tListItems\x12(.p9e.space.eocatalog.v1.ListItemsRequest\x1a).p9e.space.eocatalog.v1.ListItemsResponse\x12]\n" +
	"\bAddAsset\x12'.p9e.space.eocatalog.v1.AddAssetRequest\x1a(.p9e.space.eocatalog.v1.AddAssetResponse\x12~\n" +
	"\x13RecordQualityResult\x122.p9e.space.eocatalog.v1.RecordQualityResultRequest\x1a3.p9e.space.eocatalog.v1.RecordQualityResultResponseB\xe7\x01\n" +
	"\x1acom.p9e.space.eocatalog.v1B\x0eEoCatalogProtoP\x01Z>github.com/ppusapati/space/services/eo-catalog/api;eocatalogv1\xa2\x02\x03PSE\xaa\x02\x16P9e.Space.Eocatalog.V1\xca\x02\x16P9e\\Space\\Eocatalog\\V1\xe2\x02\"P9e\\Space\\Eocatalog\\V1\\GPBMetadata\xea\x02\x19P9e::Space::Eocatalog::V1b\x06proto3"

var (
	file_eo_catalog_proto_rawDescOnce sync.Once
	file_eo_catalog_proto_rawDescData []byte
)

func file_eo_catalog_proto_rawDescGZIP() []byte {
	file_eo_catalog_proto_rawDescOnce.Do(func() {
		file_eo_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eo_catalog_proto_rawDesc), len(file_eo_catalog_proto_rawDesc)))
	})
	return file_eo_catalog_proto_rawDescData
}

var file_eo_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_eo_catalog_proto_goTypes = []any{
	(*BoundingBox)(nil),                   // 0: p9e.space.eocatalog.v1.BoundingBox
	(*Collection)(nil),                    // 1: p9e.space.eocatalog.v1.Collection
	(*Asset)(nil),                         // 2: p9e.space.eocatalog.v1.Asset
	(*Item)(nil),                          // 3: p9e.space.eocatalog.v1.Item
	(*QualityResult)(nil),                 // 4: p9e.space.eocatalog.v1.QualityResult
	(*CreateCollectionRequest)(nil),       // 5: p9e.space.eocatalog.v1.CreateCollectionRequest
	(*CreateCollectionResponse)(nil),      // 6: p9e.space.eocatalog.v1.CreateCollectionResponse
	(*GetCollectionRequest)(nil),          // 7: p9e.space.eocatalog.v1.GetCollectionRequest
	(*GetCollectionResponse)(nil),         // 8: p9e.space.eocatalog.v1.GetCollectionResponse
	(*ListCollectionsRequest)(nil),        // 9: p9e.space.eocatalog.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),       // 10: p9e.space.eocatalog.v1.ListCollectionsResponse
	(*DeleteCollectionRequest)(nil),       // 11: p9e.space.eocatalog.v1.DeleteCollectionRequest
	(*DeleteCollectionResponse)(nil),      // 12: p9e.space.eocatalog.v1.DeleteCollectionResponse
	(*CreateItemRequest)(nil),             // 13: p9e.space.eocatalog.v1.CreateItemRequest
	(*CreateItemResponse)(nil),            // 14: p9e.space.eocatalog.v1.CreateItemResponse
	(*GetItemRequest)(nil),                // 15: p9e.space.eocatalog.v1.GetItemRequest
	(*GetItemResponse)(nil),               // 16: p9e.space.eocatalog.v1.GetItemResponse
	(*ListItemsRequest)(nil),              // 17: p9e.space.eocatalog.v1.ListItemsRequest
	(*ListItemsResponse)(nil),             // 18: p9e.space.eocatalog.v1.ListItemsResponse
	(*AddAssetRequest)(nil),               // 19: p9e.space.eocatalog.v1.AddAssetRequest
	(*AddAssetResponse)(nil),              // 20: p9e.space.eocatalog.v1.AddAssetResponse
	(*RecordQualityResultRequest)(nil),    // 21: p9e.space.eocatalog.v1.RecordQualityResultRequest
	(*RecordQualityResultResponse)(nil),   // 22: p9e.space.eocatalog.v1.RecordQualityResultResponse
	(*timestamppb.Timestamp)(nil),         // 23: google.protobuf.Timestamp
	(*fields.Fields)(nil),                 // 24: packages.api.v1.fields.Fields
	(*pagination.PaginationRequest)(nil),  // 25: packages.api.v1.pagination.PaginationRequest
	(*pagination.PaginationResponse)(nil), // 26: packages.api.v1.pagination.PaginationResponse
}
var file_eo_catalog_proto_depIdxs = []int32{
	0,  // 0: p9e.space.eocatalog.v1.Collection.spatial_extent:type_name -> p9e.space.eocatalog.v1.BoundingBox
	23, // 1: p9e.space.eocatalog.v1.Collection.temporal_start:type_name -> google.protobuf.Timestamp
	23, // 2: p9e.space.eocatalog.v1.Collection.temporal_end:type_name -> google.protobuf.Timestamp
	24, // 3: p9e.space.eocatalog.v1.Collection.fields:type_name -> packages.api.v1.fields.Fields
	23, // 4: p9e.space.eocatalog.v1.Item.datetime:type_name -> google.protobuf.Timestamp
	0,  // 5: p9e.space.eocatalog.v1.Item.bbox:type_name -> p9e.space.eocatalog.v1.BoundingBox
	2,  // 6: p9e.space.eocatalog.v1.Item.assets:type_name -> p9e.space.eocatalog.v1.Asset
	24, // 7: p9e.space.eocatalog.v1.Item.fields:type_name -> packages.api.v1.fields.Fields
	23, // 8: p9e.space.eocatalog.v1.QualityResult.computed_at:type_name -> google.protobuf.Timestamp
	0,  // 9: p9e.space.eocatalog.v1.CreateCollectionRequest.spatial_extent:type_name -> p9e.space.eocatalog.v1.BoundingBox
	23, // 10: p9e.space.eocatalog.v1.CreateCollectionRequest.temporal_start:type_name -> google.protobuf.Timestamp
	23, // 11: p9e.space.eocatalog.v1.CreateCollectionRequest.temporal_end:type_name -> google.protobuf.Timestamp
	1,  // 12: p9e.space.eocatalog.v1.CreateCollectionResponse.collection:type_name -> p9e.space.eocatalog.v1.Collection
	1,  // 13: p9e.space.eocatalog.v1.GetCollectionResponse.collection:type_name -> p9e.space.eocatalog.v1.Collection
	25, // 14: p9e.space.eocatalog.v1.ListCollectionsRequest.page:type_name -> packages.api.v1.pagination.PaginationRequest
	1,  // 15: p9e.space.eocatalog.v1.ListCollectionsResponse.collections:type_name -> p9e.space.eocatalog.v1.Collection
	26, // 16: p9e.space.eocatalog.v1.ListCollectionsResponse.page:type_name -> packages.api.v1.pagination.PaginationResponse
	23, // 17: p9e.space.eocatalog.v1.CreateItemRequest.datetime:type_name -> google.protobuf.Timestamp
	0,  // 18: p9e.space.eocatalog.v1.CreateItemRequest.bbox:type_name -> p9e.space.eocatalog.v1.BoundingBox
	3,  // 19: p9e.space.eocatalog.v1.CreateItemResponse.item:type_name -> p9e.space.eocatalog.v1.Item
	3,  // 20: p9e.space.eocatalog.v1.GetItemResponse.item:type_name -> p9e.space.eocatalog.v1.Item
	25, // 21: p9e.space.eocatalog.v1.ListItemsRequest.page:type_name -> packages.api.v1.pagination.PaginationRequest
	3,  // 22: p9e.space.eocatalog.v1.ListItemsResponse.items:type_name -> p9e.space.eocatalog.v1.Item
	26, // 23: p9e.space.eocatalog.v1.ListItemsResponse.page:type_name -> packages.api.v1.pagination.PaginationResponse
	2,  // 24: p9e.space.eocatalog.v1.AddAssetRequest.asset:type_name -> p9e.space.eocatalog.v1.Asset
	3,  // 25: p9e.space.eocatalog.v1.AddAssetResponse.item:type_name -> p9e.space.eocatalog.v1.Item
	4,  // 26: p9e.space.eocatalog.v1.RecordQualityResultResponse.result:type_name -> p9e.space.eocatalog.v1.QualityResult
	5,  // 27: p9e.space.eocatalog.v1.CatalogService.CreateCollection:input_type -> p9e.space.eocatalog.v1.CreateCollectionRequest
	7,  // 28: p9e.space.eocatalog.v1.CatalogService.GetCollection:input_type -> p9e.space.eocatalog.v1.GetCollectionRequest
	9,  // 29: p9e.space.eocatalog.v1.CatalogService.ListCollections:input_type -> p9e.space.eocatalog.v1.ListCollectionsRequest
	11, // 30: p9e.space.eocatalog.v1.CatalogService.DeleteCollection:input_type -> p9e.space.eocatalog.v1.DeleteCollectionRequest
	13, // 31: p9e.space.eocatalog.v1.CatalogService.CreateItem:input_type -> p9e.space.eocatalog.v1.CreateItemRequest
	15, // 32: p9e.space.eocatalog.v1.CatalogService.GetItem:input_type -> p9e.space.eocatalog.v1.GetItemRequest
	17, // 33: p9e.space.eocatalog.v1.CatalogService.ListItems:input_type -> p9e.space.eocatalog.v1.ListItemsRequest
	19, // 34: p9e.space.eocatalog.v1.CatalogService.AddAsset:input_type -> p9e.space.eocatalog.v1.AddAssetRequest
	21, // 35: p9e.space.eocatalog.v1.CatalogService.RecordQualityResult:input_type -> p9e.space.eocatalog.v1.RecordQualityResultRequest
	6,  // 36: p9e.space.eocatalog.v1.CatalogService.CreateCollection:output_type -> p9e.space.eocatalog.v1.CreateCollectionResponse
	8,  // 37: p9e.space.eocatalog.v1.CatalogService.GetCollection:output_type -> p9e.space.eocatalog.v1.GetCollectionResponse
	10, // 38: p9e.space.eocatalog.v1.CatalogService.ListCollections:output_type -> p9e.space.eocatalog.v1.ListCollectionsResponse
	12, // 39: p9e.space.eocatalog.v1.CatalogService.DeleteCollection:output_type -> p9e.space.eocatalog.v1.DeleteCollectionResponse
	14, // 40: p9e.space.eocatalog.v1.CatalogService.CreateItem:output_type -> p9e.space.eocatalog.v1.CreateItemResponse
	16, // 41: p9e.space.eocatalog.v1.CatalogService.GetItem:output_type -> p9e.space.eocatalog.v1.GetItemResponse
	18, // 42: p9e.space.eocatalog.v1.CatalogService.ListItems:output_type -> p9e.space.eocatalog.v1.ListItemsResponse
	20, // 43: p9e.space.eocatalog.v1.CatalogService.AddAsset:output_type -> p9e.space.eocatalog.v1.AddAssetResponse
	22, // 44: p9e.space.eocatalog.v1.CatalogService.RecordQualityResult:output_type -> p9e.space.eocatalog.v1.RecordQualityResultResponse
	36, // [36:45] is the sub-list for method output_type
	27, // [27:36] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_eo_catalog_proto_init() }
func file_eo_catalog_proto_init() {
	if File_eo_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eo_catalog_proto_rawDesc), len(file_eo_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eo_catalog_proto_goTypes,
		DependencyIndexes: file_eo_catalog_proto_depIdxs,
		MessageInfos:      file_eo_catalog_proto_msgTypes,
	}.Build()
	File_eo_catalog_proto = out.File
	file_eo_catalog_proto_goTypes = nil
	file_eo_catalog_proto_depIdxs = nil
}
