// Wire types for the class registry — the shared engine behind every
// consolidated business domain in Samavāya (see
// docs/GENERIC_INDUSTRY_IMPLEMENTATION.md).
//
// Two surfaces are defined here:
//
//   1. AttributeValue — the discriminated-union value type carried in
//      entity attribute maps on every generic domain service's
//      request/response. Every `map<string, AttributeValue>` on a
//      workcenter/asset/journal/etc. proto uses this type.
//
//   2. ClassRegistryService — the introspection RPCs the frontend
//      calls to render class-aware forms without shipping YAML to the
//      browser. ListClasses + GetClassSchema cover the whole need.
//
// What this file does NOT do: define per-domain entity services.
// Those live in each consolidated domain's own proto
// (business/<module>/<domain>/proto/<domain>.proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: packages/classregistry/proto/classregistry.proto

package classregistryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	pagination "p9e.in/samavaya/packages/api/v1/pagination"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttributeKind mirrors packages/classregistry/types.go AttributeKind.
// The set is closed — adding a kind requires coordinated change to
// the Go type, the proto, and the validator.
type AttributeKind int32

const (
	AttributeKind_ATTRIBUTE_KIND_UNSPECIFIED   AttributeKind = 0
	AttributeKind_ATTRIBUTE_KIND_STRING        AttributeKind = 1
	AttributeKind_ATTRIBUTE_KIND_INT           AttributeKind = 2
	AttributeKind_ATTRIBUTE_KIND_DECIMAL       AttributeKind = 3
	AttributeKind_ATTRIBUTE_KIND_BOOL          AttributeKind = 4
	AttributeKind_ATTRIBUTE_KIND_DATE          AttributeKind = 5
	AttributeKind_ATTRIBUTE_KIND_TIMESTAMP     AttributeKind = 6
	AttributeKind_ATTRIBUTE_KIND_DURATION      AttributeKind = 7
	AttributeKind_ATTRIBUTE_KIND_MONEY         AttributeKind = 8
	AttributeKind_ATTRIBUTE_KIND_GEO_POINT     AttributeKind = 9
	AttributeKind_ATTRIBUTE_KIND_STRING_ARRAY  AttributeKind = 10
	AttributeKind_ATTRIBUTE_KIND_INT_ARRAY     AttributeKind = 11
	AttributeKind_ATTRIBUTE_KIND_DECIMAL_ARRAY AttributeKind = 12
	AttributeKind_ATTRIBUTE_KIND_ENUM          AttributeKind = 13
	AttributeKind_ATTRIBUTE_KIND_REFERENCE     AttributeKind = 14
	AttributeKind_ATTRIBUTE_KIND_OBJECT        AttributeKind = 15
	AttributeKind_ATTRIBUTE_KIND_FILE          AttributeKind = 16
)

// Enum value maps for AttributeKind.
var (
	AttributeKind_name = map[int32]string{
		0:  "ATTRIBUTE_KIND_UNSPECIFIED",
		1:  "ATTRIBUTE_KIND_STRING",
		2:  "ATTRIBUTE_KIND_INT",
		3:  "ATTRIBUTE_KIND_DECIMAL",
		4:  "ATTRIBUTE_KIND_BOOL",
		5:  "ATTRIBUTE_KIND_DATE",
		6:  "ATTRIBUTE_KIND_TIMESTAMP",
		7:  "ATTRIBUTE_KIND_DURATION",
		8:  "ATTRIBUTE_KIND_MONEY",
		9:  "ATTRIBUTE_KIND_GEO_POINT",
		10: "ATTRIBUTE_KIND_STRING_ARRAY",
		11: "ATTRIBUTE_KIND_INT_ARRAY",
		12: "ATTRIBUTE_KIND_DECIMAL_ARRAY",
		13: "ATTRIBUTE_KIND_ENUM",
		14: "ATTRIBUTE_KIND_REFERENCE",
		15: "ATTRIBUTE_KIND_OBJECT",
		16: "ATTRIBUTE_KIND_FILE",
	}
	AttributeKind_value = map[string]int32{
		"ATTRIBUTE_KIND_UNSPECIFIED":   0,
		"ATTRIBUTE_KIND_STRING":        1,
		"ATTRIBUTE_KIND_INT":           2,
		"ATTRIBUTE_KIND_DECIMAL":       3,
		"ATTRIBUTE_KIND_BOOL":          4,
		"ATTRIBUTE_KIND_DATE":          5,
		"ATTRIBUTE_KIND_TIMESTAMP":     6,
		"ATTRIBUTE_KIND_DURATION":      7,
		"ATTRIBUTE_KIND_MONEY":         8,
		"ATTRIBUTE_KIND_GEO_POINT":     9,
		"ATTRIBUTE_KIND_STRING_ARRAY":  10,
		"ATTRIBUTE_KIND_INT_ARRAY":     11,
		"ATTRIBUTE_KIND_DECIMAL_ARRAY": 12,
		"ATTRIBUTE_KIND_ENUM":          13,
		"ATTRIBUTE_KIND_REFERENCE":     14,
		"ATTRIBUTE_KIND_OBJECT":        15,
		"ATTRIBUTE_KIND_FILE":          16,
	}
)

func (x AttributeKind) Enum() *AttributeKind {
	p := new(AttributeKind)
	*p = x
	return p
}

func (x AttributeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_packages_classregistry_proto_classregistry_proto_enumTypes[0].Descriptor()
}

func (AttributeKind) Type() protoreflect.EnumType {
	return &file_packages_classregistry_proto_classregistry_proto_enumTypes[0]
}

func (x AttributeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttributeKind.Descriptor instead.
func (AttributeKind) EnumDescriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{0}
}

// AttributeValue is the typed-union carrier for class-scoped attribute
// values. Entity payloads for generic domain services use
// map<string, AttributeValue> so the wire contract stays typed at the
// RPC level while attribute shape is validated against the class's
// YAML-declared schema at runtime.
//
// Exactly one of the oneof fields is populated per value. The Kind
// enum is a redundant discriminator so consumers that cannot read
// oneof state (legacy wire codecs) still know which variant to decode.
type AttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  AttributeKind          `protobuf:"varint,1,opt,name=kind,proto3,enum=packages.classregistry.v1.AttributeKind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*AttributeValue_StringValue
	//	*AttributeValue_IntValue
	//	*AttributeValue_DecimalValue
	//	*AttributeValue_BoolValue
	//	*AttributeValue_DateValue
	//	*AttributeValue_TimestampValue
	//	*AttributeValue_DurationValue
	//	*AttributeValue_MoneyValue
	//	*AttributeValue_GeoPointValue
	//	*AttributeValue_StringArray
	//	*AttributeValue_IntArray
	//	*AttributeValue_DecimalArray
	//	*AttributeValue_ObjectValue
	//	*AttributeValue_FileValue
	Value         isAttributeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValue) Reset() {
	*x = AttributeValue{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValue) ProtoMessage() {}

func (x *AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValue.ProtoReflect.Descriptor instead.
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeValue) GetKind() AttributeKind {
	if x != nil {
		return x.Kind
	}
	return AttributeKind_ATTRIBUTE_KIND_UNSPECIFIED
}

func (x *AttributeValue) GetValue() isAttributeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AttributeValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AttributeValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AttributeValue) GetDecimalValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DecimalValue); ok {
			return x.DecimalValue
		}
	}
	return ""
}

func (x *AttributeValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AttributeValue) GetDateValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DateValue); ok {
			return x.DateValue
		}
	}
	return ""
}

func (x *AttributeValue) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *AttributeValue) GetDurationValue() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DurationValue); ok {
			return x.DurationValue
		}
	}
	return nil
}

func (x *AttributeValue) GetMoneyValue() *MoneyValue {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_MoneyValue); ok {
			return x.MoneyValue
		}
	}
	return nil
}

func (x *AttributeValue) GetGeoPointValue() *GeoPointValue {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_GeoPointValue); ok {
			return x.GeoPointValue
		}
	}
	return nil
}

func (x *AttributeValue) GetStringArray() *StringArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_StringArray); ok {
			return x.StringArray
		}
	}
	return nil
}

func (x *AttributeValue) GetIntArray() *IntArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_IntArray); ok {
			return x.IntArray
		}
	}
	return nil
}

func (x *AttributeValue) GetDecimalArray() *DecimalArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DecimalArray); ok {
			return x.DecimalArray
		}
	}
	return nil
}

func (x *AttributeValue) GetObjectValue() *AttributeObject {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_ObjectValue); ok {
			return x.ObjectValue
		}
	}
	return nil
}

func (x *AttributeValue) GetFileValue() *FileRef {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_FileValue); ok {
			return x.FileValue
		}
	}
	return nil
}

type isAttributeValue_Value interface {
	isAttributeValue_Value()
}

type AttributeValue_StringValue struct {
	StringValue string `protobuf:"bytes,10,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AttributeValue_IntValue struct {
	IntValue int64 `protobuf:"varint,11,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AttributeValue_DecimalValue struct {
	// Decimal-safe string representation. Repositories persist as
	// NUMERIC; evaluators parse on demand to avoid float drift.
	DecimalValue string `protobuf:"bytes,12,opt,name=decimal_value,json=decimalValue,proto3,oneof"`
}

type AttributeValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,13,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AttributeValue_DateValue struct {
	// Date without time-of-day. Serialized as ISO-8601 Y-M-D.
	DateValue string `protobuf:"bytes,14,opt,name=date_value,json=dateValue,proto3,oneof"`
}

type AttributeValue_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type AttributeValue_DurationValue struct {
	DurationValue *durationpb.Duration `protobuf:"bytes,16,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

type AttributeValue_MoneyValue struct {
	MoneyValue *MoneyValue `protobuf:"bytes,17,opt,name=money_value,json=moneyValue,proto3,oneof"`
}

type AttributeValue_GeoPointValue struct {
	GeoPointValue *GeoPointValue `protobuf:"bytes,18,opt,name=geo_point_value,json=geoPointValue,proto3,oneof"`
}

type AttributeValue_StringArray struct {
	StringArray *StringArray `protobuf:"bytes,20,opt,name=string_array,json=stringArray,proto3,oneof"`
}

type AttributeValue_IntArray struct {
	IntArray *IntArray `protobuf:"bytes,21,opt,name=int_array,json=intArray,proto3,oneof"`
}

type AttributeValue_DecimalArray struct {
	DecimalArray *DecimalArray `protobuf:"bytes,22,opt,name=decimal_array,json=decimalArray,proto3,oneof"`
}

type AttributeValue_ObjectValue struct {
	// Used for both reference (lookup FK) and enum kinds — both carry
	// a single string identifier on the wire.
	ObjectValue *AttributeObject `protobuf:"bytes,30,opt,name=object_value,json=objectValue,proto3,oneof"`
}

type AttributeValue_FileValue struct {
	FileValue *FileRef `protobuf:"bytes,31,opt,name=file_value,json=fileValue,proto3,oneof"`
}

func (*AttributeValue_StringValue) isAttributeValue_Value() {}

func (*AttributeValue_IntValue) isAttributeValue_Value() {}

func (*AttributeValue_DecimalValue) isAttributeValue_Value() {}

func (*AttributeValue_BoolValue) isAttributeValue_Value() {}

func (*AttributeValue_DateValue) isAttributeValue_Value() {}

func (*AttributeValue_TimestampValue) isAttributeValue_Value() {}

func (*AttributeValue_DurationValue) isAttributeValue_Value() {}

func (*AttributeValue_MoneyValue) isAttributeValue_Value() {}

func (*AttributeValue_GeoPointValue) isAttributeValue_Value() {}

func (*AttributeValue_StringArray) isAttributeValue_Value() {}

func (*AttributeValue_IntArray) isAttributeValue_Value() {}

func (*AttributeValue_DecimalArray) isAttributeValue_Value() {}

func (*AttributeValue_ObjectValue) isAttributeValue_Value() {}

func (*AttributeValue_FileValue) isAttributeValue_Value() {}

type MoneyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Decimal-safe string. Repositories convert to NUMERIC on write.
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// ISO-4217, e.g. "INR", "USD", "EUR".
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyValue) Reset() {
	*x = MoneyValue{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyValue) ProtoMessage() {}

func (x *MoneyValue) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyValue.ProtoReflect.Descriptor instead.
func (*MoneyValue) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{1}
}

func (x *MoneyValue) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MoneyValue) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GeoPointValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoPointValue) Reset() {
	*x = GeoPointValue{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoPointValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPointValue) ProtoMessage() {}

func (x *GeoPointValue) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPointValue.ProtoReflect.Descriptor instead.
func (*GeoPointValue) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{2}
}

func (x *GeoPointValue) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoPointValue) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type StringArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringArray) Reset() {
	*x = StringArray{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArray) ProtoMessage() {}

func (x *StringArray) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArray.ProtoReflect.Descriptor instead.
func (*StringArray) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{3}
}

func (x *StringArray) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type IntArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntArray) Reset() {
	*x = IntArray{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntArray) ProtoMessage() {}

func (x *IntArray) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntArray.ProtoReflect.Descriptor instead.
func (*IntArray) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{4}
}

func (x *IntArray) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type DecimalArray struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each element is a decimal-safe string.
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecimalArray) Reset() {
	*x = DecimalArray{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecimalArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecimalArray) ProtoMessage() {}

func (x *DecimalArray) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecimalArray.ProtoReflect.Descriptor instead.
func (*DecimalArray) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{5}
}

func (x *DecimalArray) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// AttributeObject is a nested map used for object-kind attributes. Its
// schema is defined in the class registry's object spec; values are
// validated against that schema at write time.
type AttributeObject struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Fields        map[string]*AttributeValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeObject) Reset() {
	*x = AttributeObject{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeObject) ProtoMessage() {}

func (x *AttributeObject) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeObject.ProtoReflect.Descriptor instead.
func (*AttributeObject) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{6}
}

func (x *AttributeObject) GetFields() map[string]*AttributeValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// FileRef points to a blob stored via packages/filestorage. The
// BlobRef is the authoritative identifier; filename + content_type +
// size_bytes are cached metadata for display.
type FileRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobRef       string                 `protobuf:"bytes,1,opt,name=blob_ref,json=blobRef,proto3" json:"blob_ref,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRef) Reset() {
	*x = FileRef{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef) ProtoMessage() {}

func (x *FileRef) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef.ProtoReflect.Descriptor instead.
func (*FileRef) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{7}
}

func (x *FileRef) GetBlobRef() string {
	if x != nil {
		return x.BlobRef
	}
	return ""
}

func (x *FileRef) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileRef) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ListClassesRequest struct {
	state   protoimpl.MessageState    `protogen:"open.v1"`
	Context *pagination.TenantContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Required. The domain (e.g. "workcenter", "asset", "bom") whose
	// classes should be listed.
	Domain        string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClassesRequest) Reset() {
	*x = ListClassesRequest{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassesRequest) ProtoMessage() {}

func (x *ListClassesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassesRequest.ProtoReflect.Descriptor instead.
func (*ListClassesRequest) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{8}
}

func (x *ListClassesRequest) GetContext() *pagination.TenantContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListClassesRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ListClassesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []*ClassSummary        `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClassesResponse) Reset() {
	*x = ListClassesResponse{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassesResponse) ProtoMessage() {}

func (x *ListClassesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassesResponse.ProtoReflect.Descriptor instead.
func (*ListClassesResponse) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{9}
}

func (x *ListClassesResponse) GetClasses() []*ClassSummary {
	if x != nil {
		return x.Classes
	}
	return nil
}

// ClassSummary is the compact listing form — enough to render a
// class picker without fetching every attribute.
type ClassSummary struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label       string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Industries (profile names) that pre-enable this class at
	// onboarding time. Frontend can filter classes to just those
	// matching the tenant's industry.
	Industries []string `protobuf:"bytes,4,rep,name=industries,proto3" json:"industries,omitempty"`
	// True if the class declares at least one process (Layer 3
	// calculation). UIs that surface process-specific actions read
	// this.
	HasProcesses  bool `protobuf:"varint,5,opt,name=has_processes,json=hasProcesses,proto3" json:"has_processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassSummary) Reset() {
	*x = ClassSummary{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassSummary) ProtoMessage() {}

func (x *ClassSummary) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassSummary.ProtoReflect.Descriptor instead.
func (*ClassSummary) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{10}
}

func (x *ClassSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassSummary) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ClassSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ClassSummary) GetIndustries() []string {
	if x != nil {
		return x.Industries
	}
	return nil
}

func (x *ClassSummary) GetHasProcesses() bool {
	if x != nil {
		return x.HasProcesses
	}
	return false
}

type GetClassSchemaRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Context       *pagination.TenantContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Domain        string                    `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Class         string                    `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassSchemaRequest) Reset() {
	*x = GetClassSchemaRequest{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassSchemaRequest) ProtoMessage() {}

func (x *GetClassSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetClassSchemaRequest) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{11}
}

func (x *GetClassSchemaRequest) GetContext() *pagination.TenantContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetClassSchemaRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetClassSchemaRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

type GetClassSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *ClassDefinition       `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassSchemaResponse) Reset() {
	*x = GetClassSchemaResponse{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassSchemaResponse) ProtoMessage() {}

func (x *GetClassSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetClassSchemaResponse) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{12}
}

func (x *GetClassSchemaResponse) GetClass() *ClassDefinition {
	if x != nil {
		return x.Class
	}
	return nil
}

// ClassDefinition is the wire version of classregistry.ClassDef —
// same shape, proto types. Consumed by the form renderer.
type ClassDefinition struct {
	state             protoimpl.MessageState                 `protogen:"open.v1"`
	Domain            string                                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name              string                                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Label             string                                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Description       string                                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Industries        []string                               `protobuf:"bytes,5,rep,name=industries,proto3" json:"industries,omitempty"`
	Attributes        map[string]*AttributeDefinition        `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ComplianceChecks  []string                               `protobuf:"bytes,7,rep,name=compliance_checks,json=complianceChecks,proto3" json:"compliance_checks,omitempty"`
	CapacityMetrics   []string                               `protobuf:"bytes,8,rep,name=capacity_metrics,json=capacityMetrics,proto3" json:"capacity_metrics,omitempty"`
	Processes         []string                               `protobuf:"bytes,9,rep,name=processes,proto3" json:"processes,omitempty"`
	DerivedAttributes map[string]*DerivedAttributeDefinition `protobuf:"bytes,10,rep,name=derived_attributes,json=derivedAttributes,proto3" json:"derived_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CustomExtensions  []*CustomExtensionDefinition           `protobuf:"bytes,11,rep,name=custom_extensions,json=customExtensions,proto3" json:"custom_extensions,omitempty"`
	Workflow          string                                 `protobuf:"bytes,12,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Audit             *AuditPolicy                           `protobuf:"bytes,13,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClassDefinition) Reset() {
	*x = ClassDefinition{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassDefinition) ProtoMessage() {}

func (x *ClassDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassDefinition.ProtoReflect.Descriptor instead.
func (*ClassDefinition) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{13}
}

func (x *ClassDefinition) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ClassDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassDefinition) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ClassDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ClassDefinition) GetIndustries() []string {
	if x != nil {
		return x.Industries
	}
	return nil
}

func (x *ClassDefinition) GetAttributes() map[string]*AttributeDefinition {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ClassDefinition) GetComplianceChecks() []string {
	if x != nil {
		return x.ComplianceChecks
	}
	return nil
}

func (x *ClassDefinition) GetCapacityMetrics() []string {
	if x != nil {
		return x.CapacityMetrics
	}
	return nil
}

func (x *ClassDefinition) GetProcesses() []string {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *ClassDefinition) GetDerivedAttributes() map[string]*DerivedAttributeDefinition {
	if x != nil {
		return x.DerivedAttributes
	}
	return nil
}

func (x *ClassDefinition) GetCustomExtensions() []*CustomExtensionDefinition {
	if x != nil {
		return x.CustomExtensions
	}
	return nil
}

func (x *ClassDefinition) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *ClassDefinition) GetAudit() *AuditPolicy {
	if x != nil {
		return x.Audit
	}
	return nil
}

type AttributeDefinition struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Kind         AttributeKind          `protobuf:"varint,1,opt,name=kind,proto3,enum=packages.classregistry.v1.AttributeKind" json:"kind,omitempty"`
	Required     bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue *AttributeValue        `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"` // optional; present only if declared
	// Numeric bounds for int / decimal / money / duration; zero-valued
	// doubles are distinguishable from "unset" via the has_* flags.
	HasMin bool    `protobuf:"varint,4,opt,name=has_min,json=hasMin,proto3" json:"has_min,omitempty"`
	Min    float64 `protobuf:"fixed64,5,opt,name=min,proto3" json:"min,omitempty"`
	HasMax bool    `protobuf:"varint,6,opt,name=has_max,json=hasMax,proto3" json:"has_max,omitempty"`
	Max    float64 `protobuf:"fixed64,7,opt,name=max,proto3" json:"max,omitempty"`
	// Enum values — populated only for kind=ENUM.
	Values []string `protobuf:"bytes,8,rep,name=values,proto3" json:"values,omitempty"`
	// For kind=REFERENCE — the lookup table name the FK targets.
	Lookup string `protobuf:"bytes,9,opt,name=lookup,proto3" json:"lookup,omitempty"`
	// For kind=STRING — regex pattern the value must match.
	Pattern string `protobuf:"bytes,10,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// Storage hint for the domain's repository. "attributes_jsonb" by
	// default; "typed_column:<col>" for audit-critical fields that live
	// in a dedicated SQL column.
	Storage     string `protobuf:"bytes,11,opt,name=storage,proto3" json:"storage,omitempty"`
	Description string `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	// If non-empty, the attribute is deprecated since this version.
	// Validator emits a warning; callers see the value in form UIs for
	// the deprecation notice.
	DeprecatedSince string `protobuf:"bytes,13,opt,name=deprecated_since,json=deprecatedSince,proto3" json:"deprecated_since,omitempty"`
	// For kind=OBJECT — the nested schema.
	ObjectSchema map[string]*AttributeDefinition `protobuf:"bytes,14,rep,name=object_schema,json=objectSchema,proto3" json:"object_schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// For kind=*_ARRAY — the element kind.
	ArrayElementKind AttributeKind `protobuf:"varint,15,opt,name=array_element_kind,json=arrayElementKind,proto3,enum=packages.classregistry.v1.AttributeKind" json:"array_element_kind,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AttributeDefinition) Reset() {
	*x = AttributeDefinition{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDefinition) ProtoMessage() {}

func (x *AttributeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDefinition.ProtoReflect.Descriptor instead.
func (*AttributeDefinition) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{14}
}

func (x *AttributeDefinition) GetKind() AttributeKind {
	if x != nil {
		return x.Kind
	}
	return AttributeKind_ATTRIBUTE_KIND_UNSPECIFIED
}

func (x *AttributeDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AttributeDefinition) GetDefaultValue() *AttributeValue {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *AttributeDefinition) GetHasMin() bool {
	if x != nil {
		return x.HasMin
	}
	return false
}

func (x *AttributeDefinition) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *AttributeDefinition) GetHasMax() bool {
	if x != nil {
		return x.HasMax
	}
	return false
}

func (x *AttributeDefinition) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *AttributeDefinition) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *AttributeDefinition) GetLookup() string {
	if x != nil {
		return x.Lookup
	}
	return ""
}

func (x *AttributeDefinition) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *AttributeDefinition) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *AttributeDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AttributeDefinition) GetDeprecatedSince() string {
	if x != nil {
		return x.DeprecatedSince
	}
	return ""
}

func (x *AttributeDefinition) GetObjectSchema() map[string]*AttributeDefinition {
	if x != nil {
		return x.ObjectSchema
	}
	return nil
}

func (x *AttributeDefinition) GetArrayElementKind() AttributeKind {
	if x != nil {
		return x.ArrayElementKind
	}
	return AttributeKind_ATTRIBUTE_KIND_UNSPECIFIED
}

type DerivedAttributeDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Original formula text. The frontend can surface this in tooltips;
	// the backend already parsed + validated it at load time.
	Formula string `protobuf:"bytes,2,opt,name=formula,proto3" json:"formula,omitempty"`
	Unit    string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	// Attribute keys the formula reads. Frontend uses this to decide
	// when to recompute a preview value as the user edits the form.
	DependsOn     []string `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DerivedAttributeDefinition) Reset() {
	*x = DerivedAttributeDefinition{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DerivedAttributeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DerivedAttributeDefinition) ProtoMessage() {}

func (x *DerivedAttributeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DerivedAttributeDefinition.ProtoReflect.Descriptor instead.
func (*DerivedAttributeDefinition) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{15}
}

func (x *DerivedAttributeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DerivedAttributeDefinition) GetFormula() string {
	if x != nil {
		return x.Formula
	}
	return ""
}

func (x *DerivedAttributeDefinition) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *DerivedAttributeDefinition) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

type CustomExtensionDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServicePath   string                 `protobuf:"bytes,2,opt,name=service_path,json=servicePath,proto3" json:"service_path,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomExtensionDefinition) Reset() {
	*x = CustomExtensionDefinition{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomExtensionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomExtensionDefinition) ProtoMessage() {}

func (x *CustomExtensionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomExtensionDefinition.ProtoReflect.Descriptor instead.
func (*CustomExtensionDefinition) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{16}
}

func (x *CustomExtensionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomExtensionDefinition) GetServicePath() string {
	if x != nil {
		return x.ServicePath
	}
	return ""
}

func (x *CustomExtensionDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CustomExtensionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AuditPolicy struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TrackChanges         bool                   `protobuf:"varint,1,opt,name=track_changes,json=trackChanges,proto3" json:"track_changes,omitempty"`
	RetainDays           int32                  `protobuf:"varint,2,opt,name=retain_days,json=retainDays,proto3" json:"retain_days,omitempty"`
	RegulatoryFrameworks []string               `protobuf:"bytes,3,rep,name=regulatory_frameworks,json=regulatoryFrameworks,proto3" json:"regulatory_frameworks,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuditPolicy) Reset() {
	*x = AuditPolicy{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditPolicy) ProtoMessage() {}

func (x *AuditPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditPolicy.ProtoReflect.Descriptor instead.
func (*AuditPolicy) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{17}
}

func (x *AuditPolicy) GetTrackChanges() bool {
	if x != nil {
		return x.TrackChanges
	}
	return false
}

func (x *AuditPolicy) GetRetainDays() int32 {
	if x != nil {
		return x.RetainDays
	}
	return 0
}

func (x *AuditPolicy) GetRegulatoryFrameworks() []string {
	if x != nil {
		return x.RegulatoryFrameworks
	}
	return nil
}

type ListDomainsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Context       *pagination.TenantContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsRequest) Reset() {
	*x = ListDomainsRequest{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsRequest) ProtoMessage() {}

func (x *ListDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{18}
}

func (x *ListDomainsRequest) GetContext() *pagination.TenantContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ListDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsResponse) Reset() {
	*x = ListDomainsResponse{}
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsResponse) ProtoMessage() {}

func (x *ListDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_classregistry_proto_classregistry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return file_packages_classregistry_proto_classregistry_proto_rawDescGZIP(), []int{19}
}

func (x *ListDomainsResponse) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

var File_packages_classregistry_proto_classregistry_proto protoreflect.FileDescriptor

const file_packages_classregistry_proto_classregistry_proto_rawDesc = "" +
	"\n" +
	"0packages/classregistry/proto/classregistry.proto\x12\x19packages.classregistry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cpackages/proto/context.proto\"\xa4\a\n" +
	"\x0eAttributeValue\x12<\n" +
	"\x04kind\x18\x01 \x01(\x0e2(.packages.classregistry.v1.AttributeKindR\x04kind\x12#\n" +
	"\fstring_value\x18\n" +
	" \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\v \x01(\x03H\x00R\bintValue\x12%\n" +
	"\rdecimal_value\x18\f \x01(\tH\x00R\fdecimalValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\r \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"date_value\x18\x0e \x01(\tH\x00R\tdateValue\x12E\n" +
	"\x0ftimestamp_value\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12B\n" +
	"\x0eduration_value\x18\x10 \x01(\v2\x19.google.protobuf.DurationH\x00R\rdurationValue\x12H\n" +
	"\vmoney_value\x18\x11 \x01(\v2%.packages.classregistry.v1.MoneyValueH\x00R\n" +
	"moneyValue\x12R\n" +
	"\x0fgeo_point_value\x18\x12 \x01(\v2(.packages.classregistry.v1.GeoPointValueH\x00R\rgeoPointValue\x12K\n" +
	"\fstring_array\x18\x14 \x01(\v2&.packages.classregistry.v1.StringArrayH\x00R\vstringArray\x12B\n" +
	"\tint_array\x18\x15 \x01(\v2#.packages.classregistry.v1.IntArrayH\x00R\bintArray\x12N\n" +
	"\rdecimal_array\x18\x16 \x01(\v2'.packages.classregistry.v1.DecimalArrayH\x00R\fdecimalArray\x12O\n" +
	"\fobject_value\x18\x1e \x01(\v2*.packages.classregistry.v1.AttributeObjectH\x00R\vobjectValue\x12C\n" +
	"\n" +
	"file_value\x18\x1f \x01(\v2\".packages.classregistry.v1.FileRefH\x00R\tfileValueB\a\n" +
	"\x05value\"@\n" +
	"\n" +
	"MoneyValue\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"3\n" +
	"\rGeoPointValue\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\"%\n" +
	"\vStringArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\"\n" +
	"\bIntArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06values\"&\n" +
	"\fDecimalArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xc7\x01\n" +
	"\x0fAttributeObject\x12N\n" +
	"\x06fields\x18\x01 \x03(\v26.packages.classregistry.v1.AttributeObject.FieldsEntryR\x06fields\x1ad\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12?\n" +
	"\x05value\x18\x02 \x01(\v2).packages.classregistry.v1.AttributeValueR\x05value:\x028\x01\"\x82\x01\n" +
	"\aFileRef\x12\x19\n" +
	"\bblob_ref\x18\x01 \x01(\tR\ablobRef\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"n\n" +
	"\x12ListClassesRequest\x12@\n" +
	"\acontext\x18\x01 \x01(\v2&.packages.api.v1.context.TenantContextR\acontext\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"X\n" +
	"\x13ListClassesResponse\x12A\n" +
	"\aclasses\x18\x01 \x03(\v2'.packages.classregistry.v1.ClassSummaryR\aclasses\"\x9f\x01\n" +
	"\fClassSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"industries\x18\x04 \x03(\tR\n" +
	"industries\x12#\n" +
	"\rhas_processes\x18\x05 \x01(\bR\fhasProcesses\"\x87\x01\n" +
	"\x15GetClassSchemaRequest\x12@\n" +
	"\acontext\x18\x01 \x01(\v2&.packages.api.v1.context.TenantContextR\acontext\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\"Z\n" +
	"\x16GetClassSchemaResponse\x12@\n" +
	"\x05class\x18\x01 \x01(\v2*.packages.classregistry.v1.ClassDefinitionR\x05class\"\x82\a\n" +
	"\x0fClassDefinition\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"industries\x18\x05 \x03(\tR\n" +
	"industries\x12Z\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2:.packages.classregistry.v1.ClassDefinition.AttributesEntryR\n" +
	"attributes\x12+\n" +
	"\x11compliance_checks\x18\a \x03(\tR\x10complianceChecks\x12)\n" +
	"\x10capacity_metrics\x18\b \x03(\tR\x0fcapacityMetrics\x12\x1c\n" +
	"\tprocesses\x18\t \x03(\tR\tprocesses\x12p\n" +
	"\x12derived_attributes\x18\n" +
	" \x03(\v2A.packages.classregistry.v1.ClassDefinition.DerivedAttributesEntryR\x11derivedAttributes\x12a\n" +
	"\x11custom_extensions\x18\v \x03(\v24.packages.classregistry.v1.CustomExtensionDefinitionR\x10customExtensions\x12\x1a\n" +
	"\bworkflow\x18\f \x01(\tR\bworkflow\x12<\n" +
	"\x05audit\x18\r \x01(\v2&.packages.classregistry.v1.AuditPolicyR\x05audit\x1am\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\v2..packages.classregistry.v1.AttributeDefinitionR\x05value:\x028\x01\x1a{\n" +
	"\x16DerivedAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12K\n" +
	"\x05value\x18\x02 \x01(\v25.packages.classregistry.v1.DerivedAttributeDefinitionR\x05value:\x028\x01\"\xf6\x05\n" +
	"\x13AttributeDefinition\x12<\n" +
	"\x04kind\x18\x01 \x01(\x0e2(.packages.classregistry.v1.AttributeKindR\x04kind\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12N\n" +
	"\rdefault_value\x18\x03 \x01(\v2).packages.classregistry.v1.AttributeValueR\fdefaultValue\x12\x17\n" +
	"\ahas_min\x18\x04 \x01(\bR\x06hasMin\x12\x10\n" +
	"\x03min\x18\x05 \x01(\x01R\x03min\x12\x17\n" +
	"\ahas_max\x18\x06 \x01(\bR\x06hasMax\x12\x10\n" +
	"\x03max\x18\a \x01(\x01R\x03max\x12\x16\n" +
	"\x06values\x18\b \x03(\tR\x06values\x12\x16\n" +
	"\x06lookup\x18\t \x01(\tR\x06lookup\x12\x18\n" +
	"\apattern\x18\n" +
	" \x01(\tR\apattern\x12\x18\n" +
	"\astorage\x18\v \x01(\tR\astorage\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12)\n" +
	"\x10deprecated_since\x18\r \x01(\tR\x0fdeprecatedSince\x12e\n" +
	"\robject_schema\x18\x0e \x03(\v2@.packages.classregistry.v1.AttributeDefinition.ObjectSchemaEntryR\fobjectSchema\x12V\n" +
	"\x12array_element_kind\x18\x0f \x01(\x0e2(.packages.classregistry.v1.AttributeKindR\x10arrayElementKind\x1ao\n" +
	"\x11ObjectSchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\v2..packages.classregistry.v1.AttributeDefinitionR\x05value:\x028\x01\"}\n" +
	"\x1aDerivedAttributeDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aformula\x18\x02 \x01(\tR\aformula\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\tR\tdependsOn\"\x90\x01\n" +
	"\x19CustomExtensionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fservice_path\x18\x02 \x01(\tR\vservicePath\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x88\x01\n" +
	"\vAuditPolicy\x12#\n" +
	"\rtrack_changes\x18\x01 \x01(\bR\ftrackChanges\x12\x1f\n" +
	"\vretain_days\x18\x02 \x01(\x05R\n" +
	"retainDays\x123\n" +
	"\x15regulatory_frameworks\x18\x03 \x03(\tR\x14regulatoryFrameworks\"V\n" +
	"\x12ListDomainsRequest\x12@\n" +
	"\acontext\x18\x01 \x01(\v2&.packages.api.v1.context.TenantContextR\acontext\"/\n" +
	"\x13ListDomainsResponse\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains*\xef\x03\n" +
	"\rAttributeKind\x12\x1e\n" +
	"\x1aATTRIBUTE_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ATTRIBUTE_KIND_STRING\x10\x01\x12\x16\n" +
	"\x12ATTRIBUTE_KIND_INT\x10\x02\x12\x1a\n" +
	"\x16ATTRIBUTE_KIND_DECIMAL\x10\x03\x12\x17\n" +
	"\x13ATTRIBUTE_KIND_BOOL\x10\x04\x12\x17\n" +
	"\x13ATTRIBUTE_KIND_DATE\x10\x05\x12\x1c\n" +
	"\x18ATTRIBUTE_KIND_TIMESTAMP\x10\x06\x12\x1b\n" +
	"\x17ATTRIBUTE_KIND_DURATION\x10\a\x12\x18\n" +
	"\x14ATTRIBUTE_KIND_MONEY\x10\b\x12\x1c\n" +
	"\x18ATTRIBUTE_KIND_GEO_POINT\x10\t\x12\x1f\n" +
	"\x1bATTRIBUTE_KIND_STRING_ARRAY\x10\n" +
	"\x12\x1c\n" +
	"\x18ATTRIBUTE_KIND_INT_ARRAY\x10\v\x12 \n" +
	"\x1cATTRIBUTE_KIND_DECIMAL_ARRAY\x10\f\x12\x17\n" +
	"\x13ATTRIBUTE_KIND_ENUM\x10\r\x12\x1c\n" +
	"\x18ATTRIBUTE_KIND_REFERENCE\x10\x0e\x12\x19\n" +
	"\x15ATTRIBUTE_KIND_OBJECT\x10\x0f\x12\x17\n" +
	"\x13ATTRIBUTE_KIND_FILE\x10\x102\xe9\x02\n" +
	"\x14ClassRegistryService\x12l\n" +
	"\vListClasses\x12-.packages.classregistry.v1.ListClassesRequest\x1a..packages.classregistry.v1.ListClassesResponse\x12u\n" +
	"\x0eGetClassSchema\x120.packages.classregistry.v1.GetClassSchemaRequest\x1a1.packages.classregistry.v1.GetClassSchemaResponse\x12l\n" +
	"\vListDomains\x12-.packages.classregistry.v1.ListDomainsRequest\x1a..packages.classregistry.v1.ListDomainsResponseB?Z=p9e.in/samavaya/packages/classregistry/api/v1;classregistryv1b\x06proto3"

var (
	file_packages_classregistry_proto_classregistry_proto_rawDescOnce sync.Once
	file_packages_classregistry_proto_classregistry_proto_rawDescData []byte
)

func file_packages_classregistry_proto_classregistry_proto_rawDescGZIP() []byte {
	file_packages_classregistry_proto_classregistry_proto_rawDescOnce.Do(func() {
		file_packages_classregistry_proto_classregistry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_classregistry_proto_classregistry_proto_rawDesc), len(file_packages_classregistry_proto_classregistry_proto_rawDesc)))
	})
	return file_packages_classregistry_proto_classregistry_proto_rawDescData
}

var file_packages_classregistry_proto_classregistry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packages_classregistry_proto_classregistry_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_packages_classregistry_proto_classregistry_proto_goTypes = []any{
	(AttributeKind)(0),                 // 0: packages.classregistry.v1.AttributeKind
	(*AttributeValue)(nil),             // 1: packages.classregistry.v1.AttributeValue
	(*MoneyValue)(nil),                 // 2: packages.classregistry.v1.MoneyValue
	(*GeoPointValue)(nil),              // 3: packages.classregistry.v1.GeoPointValue
	(*StringArray)(nil),                // 4: packages.classregistry.v1.StringArray
	(*IntArray)(nil),                   // 5: packages.classregistry.v1.IntArray
	(*DecimalArray)(nil),               // 6: packages.classregistry.v1.DecimalArray
	(*AttributeObject)(nil),            // 7: packages.classregistry.v1.AttributeObject
	(*FileRef)(nil),                    // 8: packages.classregistry.v1.FileRef
	(*ListClassesRequest)(nil),         // 9: packages.classregistry.v1.ListClassesRequest
	(*ListClassesResponse)(nil),        // 10: packages.classregistry.v1.ListClassesResponse
	(*ClassSummary)(nil),               // 11: packages.classregistry.v1.ClassSummary
	(*GetClassSchemaRequest)(nil),      // 12: packages.classregistry.v1.GetClassSchemaRequest
	(*GetClassSchemaResponse)(nil),     // 13: packages.classregistry.v1.GetClassSchemaResponse
	(*ClassDefinition)(nil),            // 14: packages.classregistry.v1.ClassDefinition
	(*AttributeDefinition)(nil),        // 15: packages.classregistry.v1.AttributeDefinition
	(*DerivedAttributeDefinition)(nil), // 16: packages.classregistry.v1.DerivedAttributeDefinition
	(*CustomExtensionDefinition)(nil),  // 17: packages.classregistry.v1.CustomExtensionDefinition
	(*AuditPolicy)(nil),                // 18: packages.classregistry.v1.AuditPolicy
	(*ListDomainsRequest)(nil),         // 19: packages.classregistry.v1.ListDomainsRequest
	(*ListDomainsResponse)(nil),        // 20: packages.classregistry.v1.ListDomainsResponse
	nil,                                // 21: packages.classregistry.v1.AttributeObject.FieldsEntry
	nil,                                // 22: packages.classregistry.v1.ClassDefinition.AttributesEntry
	nil,                                // 23: packages.classregistry.v1.ClassDefinition.DerivedAttributesEntry
	nil,                                // 24: packages.classregistry.v1.AttributeDefinition.ObjectSchemaEntry
	(*timestamppb.Timestamp)(nil),      // 25: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 26: google.protobuf.Duration
	(*pagination.TenantContext)(nil),   // 27: packages.api.v1.context.TenantContext
}
var file_packages_classregistry_proto_classregistry_proto_depIdxs = []int32{
	0,  // 0: packages.classregistry.v1.AttributeValue.kind:type_name -> packages.classregistry.v1.AttributeKind
	25, // 1: packages.classregistry.v1.AttributeValue.timestamp_value:type_name -> google.protobuf.Timestamp
	26, // 2: packages.classregistry.v1.AttributeValue.duration_value:type_name -> google.protobuf.Duration
	2,  // 3: packages.classregistry.v1.AttributeValue.money_value:type_name -> packages.classregistry.v1.MoneyValue
	3,  // 4: packages.classregistry.v1.AttributeValue.geo_point_value:type_name -> packages.classregistry.v1.GeoPointValue
	4,  // 5: packages.classregistry.v1.AttributeValue.string_array:type_name -> packages.classregistry.v1.StringArray
	5,  // 6: packages.classregistry.v1.AttributeValue.int_array:type_name -> packages.classregistry.v1.IntArray
	6,  // 7: packages.classregistry.v1.AttributeValue.decimal_array:type_name -> packages.classregistry.v1.DecimalArray
	7,  // 8: packages.classregistry.v1.AttributeValue.object_value:type_name -> packages.classregistry.v1.AttributeObject
	8,  // 9: packages.classregistry.v1.AttributeValue.file_value:type_name -> packages.classregistry.v1.FileRef
	21, // 10: packages.classregistry.v1.AttributeObject.fields:type_name -> packages.classregistry.v1.AttributeObject.FieldsEntry
	27, // 11: packages.classregistry.v1.ListClassesRequest.context:type_name -> packages.api.v1.context.TenantContext
	11, // 12: packages.classregistry.v1.ListClassesResponse.classes:type_name -> packages.classregistry.v1.ClassSummary
	27, // 13: packages.classregistry.v1.GetClassSchemaRequest.context:type_name -> packages.api.v1.context.TenantContext
	14, // 14: packages.classregistry.v1.GetClassSchemaResponse.class:type_name -> packages.classregistry.v1.ClassDefinition
	22, // 15: packages.classregistry.v1.ClassDefinition.attributes:type_name -> packages.classregistry.v1.ClassDefinition.AttributesEntry
	23, // 16: packages.classregistry.v1.ClassDefinition.derived_attributes:type_name -> packages.classregistry.v1.ClassDefinition.DerivedAttributesEntry
	17, // 17: packages.classregistry.v1.ClassDefinition.custom_extensions:type_name -> packages.classregistry.v1.CustomExtensionDefinition
	18, // 18: packages.classregistry.v1.ClassDefinition.audit:type_name -> packages.classregistry.v1.AuditPolicy
	0,  // 19: packages.classregistry.v1.AttributeDefinition.kind:type_name -> packages.classregistry.v1.AttributeKind
	1,  // 20: packages.classregistry.v1.AttributeDefinition.default_value:type_name -> packages.classregistry.v1.AttributeValue
	24, // 21: packages.classregistry.v1.AttributeDefinition.object_schema:type_name -> packages.classregistry.v1.AttributeDefinition.ObjectSchemaEntry
	0,  // 22: packages.classregistry.v1.AttributeDefinition.array_element_kind:type_name -> packages.classregistry.v1.AttributeKind
	27, // 23: packages.classregistry.v1.ListDomainsRequest.context:type_name -> packages.api.v1.context.TenantContext
	1,  // 24: packages.classregistry.v1.AttributeObject.FieldsEntry.value:type_name -> packages.classregistry.v1.AttributeValue
	15, // 25: packages.classregistry.v1.ClassDefinition.AttributesEntry.value:type_name -> packages.classregistry.v1.AttributeDefinition
	16, // 26: packages.classregistry.v1.ClassDefinition.DerivedAttributesEntry.value:type_name -> packages.classregistry.v1.DerivedAttributeDefinition
	15, // 27: packages.classregistry.v1.AttributeDefinition.ObjectSchemaEntry.value:type_name -> packages.classregistry.v1.AttributeDefinition
	9,  // 28: packages.classregistry.v1.ClassRegistryService.ListClasses:input_type -> packages.classregistry.v1.ListClassesRequest
	12, // 29: packages.classregistry.v1.ClassRegistryService.GetClassSchema:input_type -> packages.classregistry.v1.GetClassSchemaRequest
	19, // 30: packages.classregistry.v1.ClassRegistryService.ListDomains:input_type -> packages.classregistry.v1.ListDomainsRequest
	10, // 31: packages.classregistry.v1.ClassRegistryService.ListClasses:output_type -> packages.classregistry.v1.ListClassesResponse
	13, // 32: packages.classregistry.v1.ClassRegistryService.GetClassSchema:output_type -> packages.classregistry.v1.GetClassSchemaResponse
	20, // 33: packages.classregistry.v1.ClassRegistryService.ListDomains:output_type -> packages.classregistry.v1.ListDomainsResponse
	31, // [31:34] is the sub-list for method output_type
	28, // [28:31] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_packages_classregistry_proto_classregistry_proto_init() }
func file_packages_classregistry_proto_classregistry_proto_init() {
	if File_packages_classregistry_proto_classregistry_proto != nil {
		return
	}
	file_packages_classregistry_proto_classregistry_proto_msgTypes[0].OneofWrappers = []any{
		(*AttributeValue_StringValue)(nil),
		(*AttributeValue_IntValue)(nil),
		(*AttributeValue_DecimalValue)(nil),
		(*AttributeValue_BoolValue)(nil),
		(*AttributeValue_DateValue)(nil),
		(*AttributeValue_TimestampValue)(nil),
		(*AttributeValue_DurationValue)(nil),
		(*AttributeValue_MoneyValue)(nil),
		(*AttributeValue_GeoPointValue)(nil),
		(*AttributeValue_StringArray)(nil),
		(*AttributeValue_IntArray)(nil),
		(*AttributeValue_DecimalArray)(nil),
		(*AttributeValue_ObjectValue)(nil),
		(*AttributeValue_FileValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_classregistry_proto_classregistry_proto_rawDesc), len(file_packages_classregistry_proto_classregistry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_classregistry_proto_classregistry_proto_goTypes,
		DependencyIndexes: file_packages_classregistry_proto_classregistry_proto_depIdxs,
		EnumInfos:         file_packages_classregistry_proto_classregistry_proto_enumTypes,
		MessageInfos:      file_packages_classregistry_proto_classregistry_proto_msgTypes,
	}.Build()
	File_packages_classregistry_proto_classregistry_proto = out.File
	file_packages_classregistry_proto_classregistry_proto_goTypes = nil
	file_packages_classregistry_proto_classregistry_proto_depIdxs = nil
}
