// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: p9e/space/earthobs/v1/eo_analytics.proto

package earthobsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ppusapati/space/api/p9e/space/earthobs/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AnalyticsServiceName is the fully-qualified name of the AnalyticsService service.
	AnalyticsServiceName = "p9e.space.earthobs.v1.AnalyticsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AnalyticsServiceRegisterModelProcedure is the fully-qualified name of the AnalyticsService's
	// RegisterModel RPC.
	AnalyticsServiceRegisterModelProcedure = "/p9e.space.earthobs.v1.AnalyticsService/RegisterModel"
	// AnalyticsServiceGetModelProcedure is the fully-qualified name of the AnalyticsService's GetModel
	// RPC.
	AnalyticsServiceGetModelProcedure = "/p9e.space.earthobs.v1.AnalyticsService/GetModel"
	// AnalyticsServiceListModelsProcedure is the fully-qualified name of the AnalyticsService's
	// ListModels RPC.
	AnalyticsServiceListModelsProcedure = "/p9e.space.earthobs.v1.AnalyticsService/ListModels"
	// AnalyticsServiceDeactivateModelProcedure is the fully-qualified name of the AnalyticsService's
	// DeactivateModel RPC.
	AnalyticsServiceDeactivateModelProcedure = "/p9e.space.earthobs.v1.AnalyticsService/DeactivateModel"
	// AnalyticsServiceSubmitInferenceJobProcedure is the fully-qualified name of the AnalyticsService's
	// SubmitInferenceJob RPC.
	AnalyticsServiceSubmitInferenceJobProcedure = "/p9e.space.earthobs.v1.AnalyticsService/SubmitInferenceJob"
	// AnalyticsServiceGetInferenceJobProcedure is the fully-qualified name of the AnalyticsService's
	// GetInferenceJob RPC.
	AnalyticsServiceGetInferenceJobProcedure = "/p9e.space.earthobs.v1.AnalyticsService/GetInferenceJob"
	// AnalyticsServiceListInferenceJobsProcedure is the fully-qualified name of the AnalyticsService's
	// ListInferenceJobs RPC.
	AnalyticsServiceListInferenceJobsProcedure = "/p9e.space.earthobs.v1.AnalyticsService/ListInferenceJobs"
	// AnalyticsServiceUpdateInferenceJobStatusProcedure is the fully-qualified name of the
	// AnalyticsService's UpdateInferenceJobStatus RPC.
	AnalyticsServiceUpdateInferenceJobStatusProcedure = "/p9e.space.earthobs.v1.AnalyticsService/UpdateInferenceJobStatus"
)

// AnalyticsServiceClient is a client for the p9e.space.earthobs.v1.AnalyticsService service.
type AnalyticsServiceClient interface {
	RegisterModel(context.Context, *connect.Request[v1.RegisterModelRequest]) (*connect.Response[v1.RegisterModelResponse], error)
	GetModel(context.Context, *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error)
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	DeactivateModel(context.Context, *connect.Request[v1.DeactivateModelRequest]) (*connect.Response[v1.DeactivateModelResponse], error)
	SubmitInferenceJob(context.Context, *connect.Request[v1.SubmitInferenceJobRequest]) (*connect.Response[v1.SubmitInferenceJobResponse], error)
	GetInferenceJob(context.Context, *connect.Request[v1.GetInferenceJobRequest]) (*connect.Response[v1.GetInferenceJobResponse], error)
	ListInferenceJobs(context.Context, *connect.Request[v1.ListInferenceJobsRequest]) (*connect.Response[v1.ListInferenceJobsResponse], error)
	UpdateInferenceJobStatus(context.Context, *connect.Request[v1.UpdateInferenceJobStatusRequest]) (*connect.Response[v1.UpdateInferenceJobStatusResponse], error)
}

// NewAnalyticsServiceClient constructs a client for the p9e.space.earthobs.v1.AnalyticsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnalyticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AnalyticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	analyticsServiceMethods := v1.File_p9e_space_earthobs_v1_eo_analytics_proto.Services().ByName("AnalyticsService").Methods()
	return &analyticsServiceClient{
		registerModel: connect.NewClient[v1.RegisterModelRequest, v1.RegisterModelResponse](
			httpClient,
			baseURL+AnalyticsServiceRegisterModelProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("RegisterModel")),
			connect.WithClientOptions(opts...),
		),
		getModel: connect.NewClient[v1.GetModelRequest, v1.GetModelResponse](
			httpClient,
			baseURL+AnalyticsServiceGetModelProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetModel")),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+AnalyticsServiceListModelsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
		deactivateModel: connect.NewClient[v1.DeactivateModelRequest, v1.DeactivateModelResponse](
			httpClient,
			baseURL+AnalyticsServiceDeactivateModelProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("DeactivateModel")),
			connect.WithClientOptions(opts...),
		),
		submitInferenceJob: connect.NewClient[v1.SubmitInferenceJobRequest, v1.SubmitInferenceJobResponse](
			httpClient,
			baseURL+AnalyticsServiceSubmitInferenceJobProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("SubmitInferenceJob")),
			connect.WithClientOptions(opts...),
		),
		getInferenceJob: connect.NewClient[v1.GetInferenceJobRequest, v1.GetInferenceJobResponse](
			httpClient,
			baseURL+AnalyticsServiceGetInferenceJobProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetInferenceJob")),
			connect.WithClientOptions(opts...),
		),
		listInferenceJobs: connect.NewClient[v1.ListInferenceJobsRequest, v1.ListInferenceJobsResponse](
			httpClient,
			baseURL+AnalyticsServiceListInferenceJobsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("ListInferenceJobs")),
			connect.WithClientOptions(opts...),
		),
		updateInferenceJobStatus: connect.NewClient[v1.UpdateInferenceJobStatusRequest, v1.UpdateInferenceJobStatusResponse](
			httpClient,
			baseURL+AnalyticsServiceUpdateInferenceJobStatusProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("UpdateInferenceJobStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// analyticsServiceClient implements AnalyticsServiceClient.
type analyticsServiceClient struct {
	registerModel            *connect.Client[v1.RegisterModelRequest, v1.RegisterModelResponse]
	getModel                 *connect.Client[v1.GetModelRequest, v1.GetModelResponse]
	listModels               *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
	deactivateModel          *connect.Client[v1.DeactivateModelRequest, v1.DeactivateModelResponse]
	submitInferenceJob       *connect.Client[v1.SubmitInferenceJobRequest, v1.SubmitInferenceJobResponse]
	getInferenceJob          *connect.Client[v1.GetInferenceJobRequest, v1.GetInferenceJobResponse]
	listInferenceJobs        *connect.Client[v1.ListInferenceJobsRequest, v1.ListInferenceJobsResponse]
	updateInferenceJobStatus *connect.Client[v1.UpdateInferenceJobStatusRequest, v1.UpdateInferenceJobStatusResponse]
}

// RegisterModel calls p9e.space.earthobs.v1.AnalyticsService.RegisterModel.
func (c *analyticsServiceClient) RegisterModel(ctx context.Context, req *connect.Request[v1.RegisterModelRequest]) (*connect.Response[v1.RegisterModelResponse], error) {
	return c.registerModel.CallUnary(ctx, req)
}

// GetModel calls p9e.space.earthobs.v1.AnalyticsService.GetModel.
func (c *analyticsServiceClient) GetModel(ctx context.Context, req *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error) {
	return c.getModel.CallUnary(ctx, req)
}

// ListModels calls p9e.space.earthobs.v1.AnalyticsService.ListModels.
func (c *analyticsServiceClient) ListModels(ctx context.Context, req *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// DeactivateModel calls p9e.space.earthobs.v1.AnalyticsService.DeactivateModel.
func (c *analyticsServiceClient) DeactivateModel(ctx context.Context, req *connect.Request[v1.DeactivateModelRequest]) (*connect.Response[v1.DeactivateModelResponse], error) {
	return c.deactivateModel.CallUnary(ctx, req)
}

// SubmitInferenceJob calls p9e.space.earthobs.v1.AnalyticsService.SubmitInferenceJob.
func (c *analyticsServiceClient) SubmitInferenceJob(ctx context.Context, req *connect.Request[v1.SubmitInferenceJobRequest]) (*connect.Response[v1.SubmitInferenceJobResponse], error) {
	return c.submitInferenceJob.CallUnary(ctx, req)
}

// GetInferenceJob calls p9e.space.earthobs.v1.AnalyticsService.GetInferenceJob.
func (c *analyticsServiceClient) GetInferenceJob(ctx context.Context, req *connect.Request[v1.GetInferenceJobRequest]) (*connect.Response[v1.GetInferenceJobResponse], error) {
	return c.getInferenceJob.CallUnary(ctx, req)
}

// ListInferenceJobs calls p9e.space.earthobs.v1.AnalyticsService.ListInferenceJobs.
func (c *analyticsServiceClient) ListInferenceJobs(ctx context.Context, req *connect.Request[v1.ListInferenceJobsRequest]) (*connect.Response[v1.ListInferenceJobsResponse], error) {
	return c.listInferenceJobs.CallUnary(ctx, req)
}

// UpdateInferenceJobStatus calls p9e.space.earthobs.v1.AnalyticsService.UpdateInferenceJobStatus.
func (c *analyticsServiceClient) UpdateInferenceJobStatus(ctx context.Context, req *connect.Request[v1.UpdateInferenceJobStatusRequest]) (*connect.Response[v1.UpdateInferenceJobStatusResponse], error) {
	return c.updateInferenceJobStatus.CallUnary(ctx, req)
}

// AnalyticsServiceHandler is an implementation of the p9e.space.earthobs.v1.AnalyticsService
// service.
type AnalyticsServiceHandler interface {
	RegisterModel(context.Context, *connect.Request[v1.RegisterModelRequest]) (*connect.Response[v1.RegisterModelResponse], error)
	GetModel(context.Context, *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error)
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	DeactivateModel(context.Context, *connect.Request[v1.DeactivateModelRequest]) (*connect.Response[v1.DeactivateModelResponse], error)
	SubmitInferenceJob(context.Context, *connect.Request[v1.SubmitInferenceJobRequest]) (*connect.Response[v1.SubmitInferenceJobResponse], error)
	GetInferenceJob(context.Context, *connect.Request[v1.GetInferenceJobRequest]) (*connect.Response[v1.GetInferenceJobResponse], error)
	ListInferenceJobs(context.Context, *connect.Request[v1.ListInferenceJobsRequest]) (*connect.Response[v1.ListInferenceJobsResponse], error)
	UpdateInferenceJobStatus(context.Context, *connect.Request[v1.UpdateInferenceJobStatusRequest]) (*connect.Response[v1.UpdateInferenceJobStatusResponse], error)
}

// NewAnalyticsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnalyticsServiceHandler(svc AnalyticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	analyticsServiceMethods := v1.File_p9e_space_earthobs_v1_eo_analytics_proto.Services().ByName("AnalyticsService").Methods()
	analyticsServiceRegisterModelHandler := connect.NewUnaryHandler(
		AnalyticsServiceRegisterModelProcedure,
		svc.RegisterModel,
		connect.WithSchema(analyticsServiceMethods.ByName("RegisterModel")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetModelHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetModelProcedure,
		svc.GetModel,
		connect.WithSchema(analyticsServiceMethods.ByName("GetModel")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceListModelsHandler := connect.NewUnaryHandler(
		AnalyticsServiceListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(analyticsServiceMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceDeactivateModelHandler := connect.NewUnaryHandler(
		AnalyticsServiceDeactivateModelProcedure,
		svc.DeactivateModel,
		connect.WithSchema(analyticsServiceMethods.ByName("DeactivateModel")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceSubmitInferenceJobHandler := connect.NewUnaryHandler(
		AnalyticsServiceSubmitInferenceJobProcedure,
		svc.SubmitInferenceJob,
		connect.WithSchema(analyticsServiceMethods.ByName("SubmitInferenceJob")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetInferenceJobHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetInferenceJobProcedure,
		svc.GetInferenceJob,
		connect.WithSchema(analyticsServiceMethods.ByName("GetInferenceJob")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceListInferenceJobsHandler := connect.NewUnaryHandler(
		AnalyticsServiceListInferenceJobsProcedure,
		svc.ListInferenceJobs,
		connect.WithSchema(analyticsServiceMethods.ByName("ListInferenceJobs")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceUpdateInferenceJobStatusHandler := connect.NewUnaryHandler(
		AnalyticsServiceUpdateInferenceJobStatusProcedure,
		svc.UpdateInferenceJobStatus,
		connect.WithSchema(analyticsServiceMethods.ByName("UpdateInferenceJobStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/p9e.space.earthobs.v1.AnalyticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnalyticsServiceRegisterModelProcedure:
			analyticsServiceRegisterModelHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetModelProcedure:
			analyticsServiceGetModelHandler.ServeHTTP(w, r)
		case AnalyticsServiceListModelsProcedure:
			analyticsServiceListModelsHandler.ServeHTTP(w, r)
		case AnalyticsServiceDeactivateModelProcedure:
			analyticsServiceDeactivateModelHandler.ServeHTTP(w, r)
		case AnalyticsServiceSubmitInferenceJobProcedure:
			analyticsServiceSubmitInferenceJobHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetInferenceJobProcedure:
			analyticsServiceGetInferenceJobHandler.ServeHTTP(w, r)
		case AnalyticsServiceListInferenceJobsProcedure:
			analyticsServiceListInferenceJobsHandler.ServeHTTP(w, r)
		case AnalyticsServiceUpdateInferenceJobStatusProcedure:
			analyticsServiceUpdateInferenceJobStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnalyticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAnalyticsServiceHandler struct{}

func (UnimplementedAnalyticsServiceHandler) RegisterModel(context.Context, *connect.Request[v1.RegisterModelRequest]) (*connect.Response[v1.RegisterModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.earthobs.v1.AnalyticsService.RegisterModel is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetModel(context.Context, *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.earthobs.v1.AnalyticsService.GetModel is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.earthobs.v1.AnalyticsService.ListModels is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) DeactivateModel(context.Context, *connect.Request[v1.DeactivateModelRequest]) (*connect.Response[v1.DeactivateModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.earthobs.v1.AnalyticsService.DeactivateModel is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) SubmitInferenceJob(context.Context, *connect.Request[v1.SubmitInferenceJobRequest]) (*connect.Response[v1.SubmitInferenceJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.earthobs.v1.AnalyticsService.SubmitInferenceJob is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetInferenceJob(context.Context, *connect.Request[v1.GetInferenceJobRequest]) (*connect.Response[v1.GetInferenceJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.earthobs.v1.AnalyticsService.GetInferenceJob is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) ListInferenceJobs(context.Context, *connect.Request[v1.ListInferenceJobsRequest]) (*connect.Response[v1.ListInferenceJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.earthobs.v1.AnalyticsService.ListInferenceJobs is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) UpdateInferenceJobStatus(context.Context, *connect.Request[v1.UpdateInferenceJobStatusRequest]) (*connect.Response[v1.UpdateInferenceJobStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.earthobs.v1.AnalyticsService.UpdateInferenceJobStatus is not implemented"))
}
