// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gs_scheduler.proto

package gsschedulerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	fields "p9e.in/samavaya/packages/api/v1/fields"
	pagination "p9e.in/samavaya/packages/api/v1/pagination"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingStatus int32

const (
	BookingStatus_BOOKING_STATUS_UNSPECIFIED BookingStatus = 0
	BookingStatus_BOOKING_STATUS_REQUESTED   BookingStatus = 1
	BookingStatus_BOOKING_STATUS_APPROVED    BookingStatus = 2
	BookingStatus_BOOKING_STATUS_SCHEDULED   BookingStatus = 3
	BookingStatus_BOOKING_STATUS_ACTIVE      BookingStatus = 4
	BookingStatus_BOOKING_STATUS_COMPLETED   BookingStatus = 5
	BookingStatus_BOOKING_STATUS_FAILED      BookingStatus = 6
	BookingStatus_BOOKING_STATUS_CANCELED    BookingStatus = 7
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_REQUESTED",
		2: "BOOKING_STATUS_APPROVED",
		3: "BOOKING_STATUS_SCHEDULED",
		4: "BOOKING_STATUS_ACTIVE",
		5: "BOOKING_STATUS_COMPLETED",
		6: "BOOKING_STATUS_FAILED",
		7: "BOOKING_STATUS_CANCELED",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_REQUESTED":   1,
		"BOOKING_STATUS_APPROVED":    2,
		"BOOKING_STATUS_SCHEDULED":   3,
		"BOOKING_STATUS_ACTIVE":      4,
		"BOOKING_STATUS_COMPLETED":   5,
		"BOOKING_STATUS_FAILED":      6,
		"BOOKING_STATUS_CANCELED":    7,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gs_scheduler_proto_enumTypes[0].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_gs_scheduler_proto_enumTypes[0]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{0}
}

type ContactPass struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	StationId       string                 `protobuf:"bytes,3,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	SatelliteId     string                 `protobuf:"bytes,4,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	AosTime         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=aos_time,json=aosTime,proto3" json:"aos_time,omitempty"` // acquisition of signal
	TcaTime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=tca_time,json=tcaTime,proto3" json:"tca_time,omitempty"` // time of closest approach
	LosTime         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=los_time,json=losTime,proto3" json:"los_time,omitempty"` // loss of signal
	MaxElevationDeg float64                `protobuf:"fixed64,8,opt,name=max_elevation_deg,json=maxElevationDeg,proto3" json:"max_elevation_deg,omitempty"`
	AosAzimuthDeg   float64                `protobuf:"fixed64,9,opt,name=aos_azimuth_deg,json=aosAzimuthDeg,proto3" json:"aos_azimuth_deg,omitempty"`
	LosAzimuthDeg   float64                `protobuf:"fixed64,10,opt,name=los_azimuth_deg,json=losAzimuthDeg,proto3" json:"los_azimuth_deg,omitempty"`
	Source          string                 `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"` // "predicted" | "measured"
	Fields          *fields.Fields         `protobuf:"bytes,12,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContactPass) Reset() {
	*x = ContactPass{}
	mi := &file_gs_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactPass) ProtoMessage() {}

func (x *ContactPass) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactPass.ProtoReflect.Descriptor instead.
func (*ContactPass) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ContactPass) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContactPass) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ContactPass) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *ContactPass) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *ContactPass) GetAosTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AosTime
	}
	return nil
}

func (x *ContactPass) GetTcaTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TcaTime
	}
	return nil
}

func (x *ContactPass) GetLosTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LosTime
	}
	return nil
}

func (x *ContactPass) GetMaxElevationDeg() float64 {
	if x != nil {
		return x.MaxElevationDeg
	}
	return 0
}

func (x *ContactPass) GetAosAzimuthDeg() float64 {
	if x != nil {
		return x.AosAzimuthDeg
	}
	return 0
}

func (x *ContactPass) GetLosAzimuthDeg() float64 {
	if x != nil {
		return x.LosAzimuthDeg
	}
	return 0
}

func (x *ContactPass) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContactPass) GetFields() *fields.Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PassId        string                 `protobuf:"bytes,3,opt,name=pass_id,json=passId,proto3" json:"pass_id,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"` // 0..100, higher wins
	Status        BookingStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=p9e.space.gsscheduler.v1.BookingStatus" json:"status,omitempty"`
	Purpose       string                 `protobuf:"bytes,6,opt,name=purpose,proto3" json:"purpose,omitempty"` // free-form, e.g. "downlink", "uplink", "tracking"
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Fields        *fields.Fields         `protobuf:"bytes,11,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_gs_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Booking) GetPassId() string {
	if x != nil {
		return x.PassId
	}
	return ""
}

func (x *Booking) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Booking) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *Booking) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *Booking) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Booking) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Booking) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Booking) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Booking) GetFields() *fields.Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type InsertContactPassRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	StationId       string                 `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	SatelliteId     string                 `protobuf:"bytes,3,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	AosTime         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=aos_time,json=aosTime,proto3" json:"aos_time,omitempty"`
	TcaTime         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=tca_time,json=tcaTime,proto3" json:"tca_time,omitempty"`
	LosTime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=los_time,json=losTime,proto3" json:"los_time,omitempty"`
	MaxElevationDeg float64                `protobuf:"fixed64,7,opt,name=max_elevation_deg,json=maxElevationDeg,proto3" json:"max_elevation_deg,omitempty"`
	AosAzimuthDeg   float64                `protobuf:"fixed64,8,opt,name=aos_azimuth_deg,json=aosAzimuthDeg,proto3" json:"aos_azimuth_deg,omitempty"`
	LosAzimuthDeg   float64                `protobuf:"fixed64,9,opt,name=los_azimuth_deg,json=losAzimuthDeg,proto3" json:"los_azimuth_deg,omitempty"`
	Source          string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InsertContactPassRequest) Reset() {
	*x = InsertContactPassRequest{}
	mi := &file_gs_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertContactPassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertContactPassRequest) ProtoMessage() {}

func (x *InsertContactPassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertContactPassRequest.ProtoReflect.Descriptor instead.
func (*InsertContactPassRequest) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *InsertContactPassRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InsertContactPassRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *InsertContactPassRequest) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *InsertContactPassRequest) GetAosTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AosTime
	}
	return nil
}

func (x *InsertContactPassRequest) GetTcaTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TcaTime
	}
	return nil
}

func (x *InsertContactPassRequest) GetLosTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LosTime
	}
	return nil
}

func (x *InsertContactPassRequest) GetMaxElevationDeg() float64 {
	if x != nil {
		return x.MaxElevationDeg
	}
	return 0
}

func (x *InsertContactPassRequest) GetAosAzimuthDeg() float64 {
	if x != nil {
		return x.AosAzimuthDeg
	}
	return 0
}

func (x *InsertContactPassRequest) GetLosAzimuthDeg() float64 {
	if x != nil {
		return x.LosAzimuthDeg
	}
	return 0
}

func (x *InsertContactPassRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type InsertContactPassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pass          *ContactPass           `protobuf:"bytes,1,opt,name=pass,proto3" json:"pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertContactPassResponse) Reset() {
	*x = InsertContactPassResponse{}
	mi := &file_gs_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertContactPassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertContactPassResponse) ProtoMessage() {}

func (x *InsertContactPassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertContactPassResponse.ProtoReflect.Descriptor instead.
func (*InsertContactPassResponse) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *InsertContactPassResponse) GetPass() *ContactPass {
	if x != nil {
		return x.Pass
	}
	return nil
}

type GetContactPassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactPassRequest) Reset() {
	*x = GetContactPassRequest{}
	mi := &file_gs_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactPassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactPassRequest) ProtoMessage() {}

func (x *GetContactPassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactPassRequest.ProtoReflect.Descriptor instead.
func (*GetContactPassRequest) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *GetContactPassRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetContactPassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pass          *ContactPass           `protobuf:"bytes,1,opt,name=pass,proto3" json:"pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactPassResponse) Reset() {
	*x = GetContactPassResponse{}
	mi := &file_gs_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactPassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactPassResponse) ProtoMessage() {}

func (x *GetContactPassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactPassResponse.ProtoReflect.Descriptor instead.
func (*GetContactPassResponse) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *GetContactPassResponse) GetPass() *ContactPass {
	if x != nil {
		return x.Pass
	}
	return nil
}

type ListContactPassesRequest struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	TenantId        string                        `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	StationId       string                        `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	SatelliteId     string                        `protobuf:"bytes,3,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	AosStart        *timestamppb.Timestamp        `protobuf:"bytes,4,opt,name=aos_start,json=aosStart,proto3" json:"aos_start,omitempty"`
	AosEnd          *timestamppb.Timestamp        `protobuf:"bytes,5,opt,name=aos_end,json=aosEnd,proto3" json:"aos_end,omitempty"`
	MinElevationDeg float64                       `protobuf:"fixed64,6,opt,name=min_elevation_deg,json=minElevationDeg,proto3" json:"min_elevation_deg,omitempty"`
	Page            *pagination.PaginationRequest `protobuf:"bytes,7,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListContactPassesRequest) Reset() {
	*x = ListContactPassesRequest{}
	mi := &file_gs_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactPassesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactPassesRequest) ProtoMessage() {}

func (x *ListContactPassesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactPassesRequest.ProtoReflect.Descriptor instead.
func (*ListContactPassesRequest) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *ListContactPassesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListContactPassesRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *ListContactPassesRequest) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *ListContactPassesRequest) GetAosStart() *timestamppb.Timestamp {
	if x != nil {
		return x.AosStart
	}
	return nil
}

func (x *ListContactPassesRequest) GetAosEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.AosEnd
	}
	return nil
}

func (x *ListContactPassesRequest) GetMinElevationDeg() float64 {
	if x != nil {
		return x.MinElevationDeg
	}
	return 0
}

func (x *ListContactPassesRequest) GetPage() *pagination.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListContactPassesResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Passes        []*ContactPass                 `protobuf:"bytes,1,rep,name=passes,proto3" json:"passes,omitempty"`
	Page          *pagination.PaginationResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactPassesResponse) Reset() {
	*x = ListContactPassesResponse{}
	mi := &file_gs_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactPassesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactPassesResponse) ProtoMessage() {}

func (x *ListContactPassesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactPassesResponse.ProtoReflect.Descriptor instead.
func (*ListContactPassesResponse) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *ListContactPassesResponse) GetPasses() []*ContactPass {
	if x != nil {
		return x.Passes
	}
	return nil
}

func (x *ListContactPassesResponse) GetPage() *pagination.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type RequestBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PassId        string                 `protobuf:"bytes,2,opt,name=pass_id,json=passId,proto3" json:"pass_id,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Purpose       string                 `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBookingRequest) Reset() {
	*x = RequestBookingRequest{}
	mi := &file_gs_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBookingRequest) ProtoMessage() {}

func (x *RequestBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBookingRequest.ProtoReflect.Descriptor instead.
func (*RequestBookingRequest) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *RequestBookingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RequestBookingRequest) GetPassId() string {
	if x != nil {
		return x.PassId
	}
	return ""
}

func (x *RequestBookingRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RequestBookingRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *RequestBookingRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type RequestBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBookingResponse) Reset() {
	*x = RequestBookingResponse{}
	mi := &file_gs_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBookingResponse) ProtoMessage() {}

func (x *RequestBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBookingResponse.ProtoReflect.Descriptor instead.
func (*RequestBookingResponse) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *RequestBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_gs_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *GetBookingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingResponse) Reset() {
	*x = GetBookingResponse{}
	mi := &file_gs_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingResponse) ProtoMessage() {}

func (x *GetBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingResponse.ProtoReflect.Descriptor instead.
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *GetBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type ListBookingsRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	TenantId      string                        `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        *BookingStatus                `protobuf:"varint,2,opt,name=status,proto3,enum=p9e.space.gsscheduler.v1.BookingStatus,oneof" json:"status,omitempty"`
	Page          *pagination.PaginationRequest `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsRequest) Reset() {
	*x = ListBookingsRequest{}
	mi := &file_gs_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsRequest) ProtoMessage() {}

func (x *ListBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListBookingsRequest) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *ListBookingsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListBookingsRequest) GetStatus() BookingStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *ListBookingsRequest) GetPage() *pagination.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListBookingsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Bookings      []*Booking                     `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Page          *pagination.PaginationResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsResponse) Reset() {
	*x = ListBookingsResponse{}
	mi := &file_gs_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsResponse) ProtoMessage() {}

func (x *ListBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListBookingsResponse) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *ListBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *ListBookingsResponse) GetPage() *pagination.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdateBookingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        BookingStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=p9e.space.gsscheduler.v1.BookingStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingStatusRequest) Reset() {
	*x = UpdateBookingStatusRequest{}
	mi := &file_gs_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingStatusRequest) ProtoMessage() {}

func (x *UpdateBookingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingStatusRequest) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateBookingStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBookingStatusRequest) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *UpdateBookingStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateBookingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingStatusResponse) Reset() {
	*x = UpdateBookingStatusResponse{}
	mi := &file_gs_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingStatusResponse) ProtoMessage() {}

func (x *UpdateBookingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookingStatusResponse) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateBookingStatusResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_gs_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{16}
}

func (x *CancelBookingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelBookingRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_gs_scheduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_scheduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_gs_scheduler_proto_rawDescGZIP(), []int{17}
}

func (x *CancelBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

var File_gs_scheduler_proto protoreflect.FileDescriptor

const file_gs_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x12gs_scheduler.proto\x12\x18p9e.space.gsscheduler.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\ffields.proto\x1a\x10pagination.proto\"\xed\x03\n" +
	"\vContactPass\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x03 \x01(\tR\tstationId\x12!\n" +
	"\fsatellite_id\x18\x04 \x01(\tR\vsatelliteId\x125\n" +
	"\baos_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aaosTime\x125\n" +
	"\btca_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\atcaTime\x125\n" +
	"\blos_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\alosTime\x12*\n" +
	"\x11max_elevation_deg\x18\b \x01(\x01R\x0fmaxElevationDeg\x12&\n" +
	"\x0faos_azimuth_deg\x18\t \x01(\x01R\raosAzimuthDeg\x12&\n" +
	"\x0flos_azimuth_deg\x18\n" +
	" \x01(\x01R\rlosAzimuthDeg\x12\x16\n" +
	"\x06source\x18\v \x01(\tR\x06source\x126\n" +
	"\x06fields\x18\f \x01(\v2\x1e.packages.api.v1.fields.FieldsR\x06fields\"\xb7\x03\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\apass_id\x18\x03 \x01(\tR\x06passId\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12?\n" +
	"\x06status\x18\x05 \x01(\x0e2'.p9e.space.gsscheduler.v1.BookingStatusR\x06status\x12\x18\n" +
	"\apurpose\x18\x06 \x01(\tR\apurpose\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12=\n" +
	"\fscheduled_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x126\n" +
	"\x06fields\x18\v \x01(\v2\x1e.packages.api.v1.fields.FieldsR\x06fields\"\xa6\x04\n" +
	"\x18InsertContactPassRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12'\n" +
	"\n" +
	"station_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\tstationId\x12+\n" +
	"\fsatellite_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\vsatelliteId\x125\n" +
	"\baos_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aaosTime\x125\n" +
	"\btca_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\atcaTime\x125\n" +
	"\blos_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\alosTime\x12C\n" +
	"\x11max_elevation_deg\x18\a \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x00\x00\x00R\x0fmaxElevationDeg\x12?\n" +
	"\x0faos_azimuth_deg\x18\b \x01(\x01B\x17\xbaH\x14\x12\x12\x11\x00\x00\x00\x00\x00\x80v@)\x00\x00\x00\x00\x00\x00\x00\x00R\raosAzimuthDeg\x12?\n" +
	"\x0flos_azimuth_deg\x18\t \x01(\x01B\x17\xbaH\x14\x12\x12\x11\x00\x00\x00\x00\x00\x80v@)\x00\x00\x00\x00\x00\x00\x00\x00R\rlosAzimuthDeg\x12!\n" +
	"\x06source\x18\n" +
	" \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 R\x06source\"V\n" +
	"\x19InsertContactPassResponse\x129\n" +
	"\x04pass\x18\x01 \x01(\v2%.p9e.space.gsscheduler.v1.ContactPassR\x04pass\"1\n" +
	"\x15GetContactPassRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\"S\n" +
	"\x16GetContactPassResponse\x129\n" +
	"\x04pass\x18\x01 \x01(\v2%.p9e.space.gsscheduler.v1.ContactPassR\x04pass\"\xe0\x02\n" +
	"\x18ListContactPassesRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\tR\tstationId\x12!\n" +
	"\fsatellite_id\x18\x03 \x01(\tR\vsatelliteId\x127\n" +
	"\taos_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\baosStart\x123\n" +
	"\aaos_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06aosEnd\x12*\n" +
	"\x11min_elevation_deg\x18\x06 \x01(\x01R\x0fminElevationDeg\x12A\n" +
	"\x04page\x18\a \x01(\v2-.packages.api.v1.pagination.PaginationRequestR\x04page\"\x9e\x01\n" +
	"\x19ListContactPassesResponse\x12=\n" +
	"\x06passes\x18\x01 \x03(\v2%.p9e.space.gsscheduler.v1.ContactPassR\x06passes\x12B\n" +
	"\x04page\x18\x02 \x01(\v2..packages.api.v1.pagination.PaginationResponseR\x04page\"\xc3\x01\n" +
	"\x15RequestBookingRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12!\n" +
	"\apass_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x06passId\x12%\n" +
	"\bpriority\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\bpriority\x12#\n" +
	"\apurpose\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\apurpose\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"U\n" +
	"\x16RequestBookingResponse\x12;\n" +
	"\abooking\x18\x01 \x01(\v2!.p9e.space.gsscheduler.v1.BookingR\abooking\"-\n" +
	"\x11GetBookingRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\"Q\n" +
	"\x12GetBookingResponse\x12;\n" +
	"\abooking\x18\x01 \x01(\v2!.p9e.space.gsscheduler.v1.BookingR\abooking\"\xd0\x01\n" +
	"\x13ListBookingsRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12D\n" +
	"\x06status\x18\x02 \x01(\x0e2'.p9e.space.gsscheduler.v1.BookingStatusH\x00R\x06status\x88\x01\x01\x12A\n" +
	"\x04page\x18\x03 \x01(\v2-.packages.api.v1.pagination.PaginationRequestR\x04pageB\t\n" +
	"\a_status\"\x99\x01\n" +
	"\x14ListBookingsResponse\x12=\n" +
	"\bbookings\x18\x01 \x03(\v2!.p9e.space.gsscheduler.v1.BookingR\bbookings\x12B\n" +
	"\x04page\x18\x02 \x01(\v2..packages.api.v1.pagination.PaginationResponseR\x04page\"\xa8\x01\n" +
	"\x1aUpdateBookingStatusRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\x12K\n" +
	"\x06status\x18\x02 \x01(\x0e2'.p9e.space.gsscheduler.v1.BookingStatusB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"Z\n" +
	"\x1bUpdateBookingStatusResponse\x12;\n" +
	"\abooking\x18\x01 \x01(\v2!.p9e.space.gsscheduler.v1.BookingR\abooking\"H\n" +
	"\x14CancelBookingRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"T\n" +
	"\x15CancelBookingResponse\x12;\n" +
	"\abooking\x18\x01 \x01(\v2!.p9e.space.gsscheduler.v1.BookingR\abooking*\xf9\x01\n" +
	"\rBookingStatus\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18BOOKING_STATUS_REQUESTED\x10\x01\x12\x1b\n" +
	"\x17BOOKING_STATUS_APPROVED\x10\x02\x12\x1c\n" +
	"\x18BOOKING_STATUS_SCHEDULED\x10\x03\x12\x19\n" +
	"\x15BOOKING_STATUS_ACTIVE\x10\x04\x12\x1c\n" +
	"\x18BOOKING_STATUS_COMPLETED\x10\x05\x12\x19\n" +
	"\x15BOOKING_STATUS_FAILED\x10\x06\x12\x1b\n" +
	"\x17BOOKING_STATUS_CANCELED\x10\a2\xc7\a\n" +
	"\x10SchedulerService\x12|\n" +
	"\x11InsertContactPass\x122.p9e.space.gsscheduler.v1.InsertContactPassRequest\x1a3.p9e.space.gsscheduler.v1.InsertContactPassResponse\x12s\n" +
	"\x0eGetContactPass\x12/.p9e.space.gsscheduler.v1.GetContactPassRequest\x1a0.p9e.space.gsscheduler.v1.GetContactPassResponse\x12|\n" +
	"\x11ListContactPasses\x122.p9e.space.gsscheduler.v1.ListContactPassesRequest\x1a3.p9e.space.gsscheduler.v1.ListContactPassesResponse\x12s\n" +
	"\x0eRequestBooking\x12/.p9e.space.gsscheduler.v1.RequestBookingRequest\x1a0.p9e.space.gsscheduler.v1.RequestBookingResponse\x12g\n" +
	"\n" +
	"GetBooking\x12+.p9e.space.gsscheduler.v1.GetBookingRequest\x1a,.p9e.space.gsscheduler.v1.GetBookingResponse\x12m\n" +
	"\fListBookings\x12-.p9e.space.gsscheduler.v1.ListBookingsRequest\x1a..p9e.space.gsscheduler.v1.ListBookingsResponse\x12\x82\x01\n" +
	"\x13UpdateBookingStatus\x124.p9e.space.gsscheduler.v1.UpdateBookingStatusRequest\x1a5.p9e.space.gsscheduler.v1.UpdateBookingStatusResponse\x12p\n" +
	"\rCancelBooking\x12..p9e.space.gsscheduler.v1.CancelBookingRequest\x1a/.p9e.space.gsscheduler.v1.CancelBookingResponseB\xf7\x01\n" +
	"\x1ccom.p9e.space.gsscheduler.v1B\x10GsSchedulerProtoP\x01ZBgithub.com/ppusapati/space/services/gs-scheduler/api;gsschedulerv1\xa2\x02\x03PSG\xaa\x02\x18P9e.Space.Gsscheduler.V1\xca\x02\x18P9e\\Space\\Gsscheduler\\V1\xe2\x02$P9e\\Space\\Gsscheduler\\V1\\GPBMetadata\xea\x02\x1bP9e::Space::Gsscheduler::V1b\x06proto3"

var (
	file_gs_scheduler_proto_rawDescOnce sync.Once
	file_gs_scheduler_proto_rawDescData []byte
)

func file_gs_scheduler_proto_rawDescGZIP() []byte {
	file_gs_scheduler_proto_rawDescOnce.Do(func() {
		file_gs_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gs_scheduler_proto_rawDesc), len(file_gs_scheduler_proto_rawDesc)))
	})
	return file_gs_scheduler_proto_rawDescData
}

var file_gs_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gs_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_gs_scheduler_proto_goTypes = []any{
	(BookingStatus)(0),                    // 0: p9e.space.gsscheduler.v1.BookingStatus
	(*ContactPass)(nil),                   // 1: p9e.space.gsscheduler.v1.ContactPass
	(*Booking)(nil),                       // 2: p9e.space.gsscheduler.v1.Booking
	(*InsertContactPassRequest)(nil),      // 3: p9e.space.gsscheduler.v1.InsertContactPassRequest
	(*InsertContactPassResponse)(nil),     // 4: p9e.space.gsscheduler.v1.InsertContactPassResponse
	(*GetContactPassRequest)(nil),         // 5: p9e.space.gsscheduler.v1.GetContactPassRequest
	(*GetContactPassResponse)(nil),        // 6: p9e.space.gsscheduler.v1.GetContactPassResponse
	(*ListContactPassesRequest)(nil),      // 7: p9e.space.gsscheduler.v1.ListContactPassesRequest
	(*ListContactPassesResponse)(nil),     // 8: p9e.space.gsscheduler.v1.ListContactPassesResponse
	(*RequestBookingRequest)(nil),         // 9: p9e.space.gsscheduler.v1.RequestBookingRequest
	(*RequestBookingResponse)(nil),        // 10: p9e.space.gsscheduler.v1.RequestBookingResponse
	(*GetBookingRequest)(nil),             // 11: p9e.space.gsscheduler.v1.GetBookingRequest
	(*GetBookingResponse)(nil),            // 12: p9e.space.gsscheduler.v1.GetBookingResponse
	(*ListBookingsRequest)(nil),           // 13: p9e.space.gsscheduler.v1.ListBookingsRequest
	(*ListBookingsResponse)(nil),          // 14: p9e.space.gsscheduler.v1.ListBookingsResponse
	(*UpdateBookingStatusRequest)(nil),    // 15: p9e.space.gsscheduler.v1.UpdateBookingStatusRequest
	(*UpdateBookingStatusResponse)(nil),   // 16: p9e.space.gsscheduler.v1.UpdateBookingStatusResponse
	(*CancelBookingRequest)(nil),          // 17: p9e.space.gsscheduler.v1.CancelBookingRequest
	(*CancelBookingResponse)(nil),         // 18: p9e.space.gsscheduler.v1.CancelBookingResponse
	(*timestamppb.Timestamp)(nil),         // 19: google.protobuf.Timestamp
	(*fields.Fields)(nil),                 // 20: packages.api.v1.fields.Fields
	(*pagination.PaginationRequest)(nil),  // 21: packages.api.v1.pagination.PaginationRequest
	(*pagination.PaginationResponse)(nil), // 22: packages.api.v1.pagination.PaginationResponse
}
var file_gs_scheduler_proto_depIdxs = []int32{
	19, // 0: p9e.space.gsscheduler.v1.ContactPass.aos_time:type_name -> google.protobuf.Timestamp
	19, // 1: p9e.space.gsscheduler.v1.ContactPass.tca_time:type_name -> google.protobuf.Timestamp
	19, // 2: p9e.space.gsscheduler.v1.ContactPass.los_time:type_name -> google.protobuf.Timestamp
	20, // 3: p9e.space.gsscheduler.v1.ContactPass.fields:type_name -> packages.api.v1.fields.Fields
	0,  // 4: p9e.space.gsscheduler.v1.Booking.status:type_name -> p9e.space.gsscheduler.v1.BookingStatus
	19, // 5: p9e.space.gsscheduler.v1.Booking.scheduled_at:type_name -> google.protobuf.Timestamp
	19, // 6: p9e.space.gsscheduler.v1.Booking.completed_at:type_name -> google.protobuf.Timestamp
	20, // 7: p9e.space.gsscheduler.v1.Booking.fields:type_name -> packages.api.v1.fields.Fields
	19, // 8: p9e.space.gsscheduler.v1.InsertContactPassRequest.aos_time:type_name -> google.protobuf.Timestamp
	19, // 9: p9e.space.gsscheduler.v1.InsertContactPassRequest.tca_time:type_name -> google.protobuf.Timestamp
	19, // 10: p9e.space.gsscheduler.v1.InsertContactPassRequest.los_time:type_name -> google.protobuf.Timestamp
	1,  // 11: p9e.space.gsscheduler.v1.InsertContactPassResponse.pass:type_name -> p9e.space.gsscheduler.v1.ContactPass
	1,  // 12: p9e.space.gsscheduler.v1.GetContactPassResponse.pass:type_name -> p9e.space.gsscheduler.v1.ContactPass
	19, // 13: p9e.space.gsscheduler.v1.ListContactPassesRequest.aos_start:type_name -> google.protobuf.Timestamp
	19, // 14: p9e.space.gsscheduler.v1.ListContactPassesRequest.aos_end:type_name -> google.protobuf.Timestamp
	21, // 15: p9e.space.gsscheduler.v1.ListContactPassesRequest.page:type_name -> packages.api.v1.pagination.PaginationRequest
	1,  // 16: p9e.space.gsscheduler.v1.ListContactPassesResponse.passes:type_name -> p9e.space.gsscheduler.v1.ContactPass
	22, // 17: p9e.space.gsscheduler.v1.ListContactPassesResponse.page:type_name -> packages.api.v1.pagination.PaginationResponse
	2,  // 18: p9e.space.gsscheduler.v1.RequestBookingResponse.booking:type_name -> p9e.space.gsscheduler.v1.Booking
	2,  // 19: p9e.space.gsscheduler.v1.GetBookingResponse.booking:type_name -> p9e.space.gsscheduler.v1.Booking
	0,  // 20: p9e.space.gsscheduler.v1.ListBookingsRequest.status:type_name -> p9e.space.gsscheduler.v1.BookingStatus
	21, // 21: p9e.space.gsscheduler.v1.ListBookingsRequest.page:type_name -> packages.api.v1.pagination.PaginationRequest
	2,  // 22: p9e.space.gsscheduler.v1.ListBookingsResponse.bookings:type_name -> p9e.space.gsscheduler.v1.Booking
	22, // 23: p9e.space.gsscheduler.v1.ListBookingsResponse.page:type_name -> packages.api.v1.pagination.PaginationResponse
	0,  // 24: p9e.space.gsscheduler.v1.UpdateBookingStatusRequest.status:type_name -> p9e.space.gsscheduler.v1.BookingStatus
	2,  // 25: p9e.space.gsscheduler.v1.UpdateBookingStatusResponse.booking:type_name -> p9e.space.gsscheduler.v1.Booking
	2,  // 26: p9e.space.gsscheduler.v1.CancelBookingResponse.booking:type_name -> p9e.space.gsscheduler.v1.Booking
	3,  // 27: p9e.space.gsscheduler.v1.SchedulerService.InsertContactPass:input_type -> p9e.space.gsscheduler.v1.InsertContactPassRequest
	5,  // 28: p9e.space.gsscheduler.v1.SchedulerService.GetContactPass:input_type -> p9e.space.gsscheduler.v1.GetContactPassRequest
	7,  // 29: p9e.space.gsscheduler.v1.SchedulerService.ListContactPasses:input_type -> p9e.space.gsscheduler.v1.ListContactPassesRequest
	9,  // 30: p9e.space.gsscheduler.v1.SchedulerService.RequestBooking:input_type -> p9e.space.gsscheduler.v1.RequestBookingRequest
	11, // 31: p9e.space.gsscheduler.v1.SchedulerService.GetBooking:input_type -> p9e.space.gsscheduler.v1.GetBookingRequest
	13, // 32: p9e.space.gsscheduler.v1.SchedulerService.ListBookings:input_type -> p9e.space.gsscheduler.v1.ListBookingsRequest
	15, // 33: p9e.space.gsscheduler.v1.SchedulerService.UpdateBookingStatus:input_type -> p9e.space.gsscheduler.v1.UpdateBookingStatusRequest
	17, // 34: p9e.space.gsscheduler.v1.SchedulerService.CancelBooking:input_type -> p9e.space.gsscheduler.v1.CancelBookingRequest
	4,  // 35: p9e.space.gsscheduler.v1.SchedulerService.InsertContactPass:output_type -> p9e.space.gsscheduler.v1.InsertContactPassResponse
	6,  // 36: p9e.space.gsscheduler.v1.SchedulerService.GetContactPass:output_type -> p9e.space.gsscheduler.v1.GetContactPassResponse
	8,  // 37: p9e.space.gsscheduler.v1.SchedulerService.ListContactPasses:output_type -> p9e.space.gsscheduler.v1.ListContactPassesResponse
	10, // 38: p9e.space.gsscheduler.v1.SchedulerService.RequestBooking:output_type -> p9e.space.gsscheduler.v1.RequestBookingResponse
	12, // 39: p9e.space.gsscheduler.v1.SchedulerService.GetBooking:output_type -> p9e.space.gsscheduler.v1.GetBookingResponse
	14, // 40: p9e.space.gsscheduler.v1.SchedulerService.ListBookings:output_type -> p9e.space.gsscheduler.v1.ListBookingsResponse
	16, // 41: p9e.space.gsscheduler.v1.SchedulerService.UpdateBookingStatus:output_type -> p9e.space.gsscheduler.v1.UpdateBookingStatusResponse
	18, // 42: p9e.space.gsscheduler.v1.SchedulerService.CancelBooking:output_type -> p9e.space.gsscheduler.v1.CancelBookingResponse
	35, // [35:43] is the sub-list for method output_type
	27, // [27:35] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_gs_scheduler_proto_init() }
func file_gs_scheduler_proto_init() {
	if File_gs_scheduler_proto != nil {
		return
	}
	file_gs_scheduler_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gs_scheduler_proto_rawDesc), len(file_gs_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gs_scheduler_proto_goTypes,
		DependencyIndexes: file_gs_scheduler_proto_depIdxs,
		EnumInfos:         file_gs_scheduler_proto_enumTypes,
		MessageInfos:      file_gs_scheduler_proto_msgTypes,
	}.Build()
	File_gs_scheduler_proto = out.File
	file_gs_scheduler_proto_goTypes = nil
	file_gs_scheduler_proto_depIdxs = nil
}
