// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: p9e/space/earthobs/v1/eo_analytics.proto

package earthobsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/ppusapati/space/api/p9e/space/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferenceTask int32

const (
	InferenceTask_INFERENCE_TASK_UNSPECIFIED    InferenceTask = 0
	InferenceTask_INFERENCE_TASK_DETECTION      InferenceTask = 1 // YOLO / Faster R-CNN
	InferenceTask_INFERENCE_TASK_SEGMENTATION   InferenceTask = 2 // U-Net / DeepLabV3+
	InferenceTask_INFERENCE_TASK_CLASSIFICATION InferenceTask = 3 // ViT / ResNet
)

// Enum value maps for InferenceTask.
var (
	InferenceTask_name = map[int32]string{
		0: "INFERENCE_TASK_UNSPECIFIED",
		1: "INFERENCE_TASK_DETECTION",
		2: "INFERENCE_TASK_SEGMENTATION",
		3: "INFERENCE_TASK_CLASSIFICATION",
	}
	InferenceTask_value = map[string]int32{
		"INFERENCE_TASK_UNSPECIFIED":    0,
		"INFERENCE_TASK_DETECTION":      1,
		"INFERENCE_TASK_SEGMENTATION":   2,
		"INFERENCE_TASK_CLASSIFICATION": 3,
	}
)

func (x InferenceTask) Enum() *InferenceTask {
	p := new(InferenceTask)
	*p = x
	return p
}

func (x InferenceTask) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InferenceTask) Descriptor() protoreflect.EnumDescriptor {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_enumTypes[0].Descriptor()
}

func (InferenceTask) Type() protoreflect.EnumType {
	return &file_p9e_space_earthobs_v1_eo_analytics_proto_enumTypes[0]
}

func (x InferenceTask) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InferenceTask.Descriptor instead.
func (InferenceTask) EnumDescriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{0}
}

type InferenceJobStatus int32

const (
	InferenceJobStatus_INFERENCE_JOB_STATUS_UNSPECIFIED InferenceJobStatus = 0
	InferenceJobStatus_INFERENCE_JOB_STATUS_PENDING     InferenceJobStatus = 1
	InferenceJobStatus_INFERENCE_JOB_STATUS_RUNNING     InferenceJobStatus = 2
	InferenceJobStatus_INFERENCE_JOB_STATUS_SUCCEEDED   InferenceJobStatus = 3
	InferenceJobStatus_INFERENCE_JOB_STATUS_FAILED      InferenceJobStatus = 4
)

// Enum value maps for InferenceJobStatus.
var (
	InferenceJobStatus_name = map[int32]string{
		0: "INFERENCE_JOB_STATUS_UNSPECIFIED",
		1: "INFERENCE_JOB_STATUS_PENDING",
		2: "INFERENCE_JOB_STATUS_RUNNING",
		3: "INFERENCE_JOB_STATUS_SUCCEEDED",
		4: "INFERENCE_JOB_STATUS_FAILED",
	}
	InferenceJobStatus_value = map[string]int32{
		"INFERENCE_JOB_STATUS_UNSPECIFIED": 0,
		"INFERENCE_JOB_STATUS_PENDING":     1,
		"INFERENCE_JOB_STATUS_RUNNING":     2,
		"INFERENCE_JOB_STATUS_SUCCEEDED":   3,
		"INFERENCE_JOB_STATUS_FAILED":      4,
	}
)

func (x InferenceJobStatus) Enum() *InferenceJobStatus {
	p := new(InferenceJobStatus)
	*p = x
	return p
}

func (x InferenceJobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InferenceJobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_enumTypes[1].Descriptor()
}

func (InferenceJobStatus) Type() protoreflect.EnumType {
	return &file_p9e_space_earthobs_v1_eo_analytics_proto_enumTypes[1]
}

func (x InferenceJobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InferenceJobStatus.Descriptor instead.
func (InferenceJobStatus) EnumDescriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{1}
}

type Model struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId    string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`       // unique per tenant (e.g. "yolov8-port")
	Version     string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"` // semver / commit
	Task        InferenceTask          `protobuf:"varint,5,opt,name=task,proto3,enum=p9e.space.earthobs.v1.InferenceTask" json:"task,omitempty"`
	Framework   string                 `protobuf:"bytes,6,opt,name=framework,proto3" json:"framework,omitempty"`                        // "onnx", "pytorch", "tensorflow"
	ArtefactUri string                 `protobuf:"bytes,7,opt,name=artefact_uri,json=artefactUri,proto3" json:"artefact_uri,omitempty"` // s3:// path to the model file
	// Free-form metadata (label schema, input shapes, training metrics).
	MetadataJson  string          `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Active        bool            `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	Audit         *v1.AuditFields `protobuf:"bytes,10,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Model) GetTask() InferenceTask {
	if x != nil {
		return x.Task
	}
	return InferenceTask_INFERENCE_TASK_UNSPECIFIED
}

func (x *Model) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *Model) GetArtefactUri() string {
	if x != nil {
		return x.ArtefactUri
	}
	return ""
}

func (x *Model) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *Model) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Model) GetAudit() *v1.AuditFields {
	if x != nil {
		return x.Audit
	}
	return nil
}

type InferenceJob struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelId  string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ItemId   string                 `protobuf:"bytes,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Status   InferenceJobStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=p9e.space.earthobs.v1.InferenceJobStatus" json:"status,omitempty"`
	// s3:// uri of the result blob (JSON for detections, NPY for masks).
	OutputUri     string                 `protobuf:"bytes,6,opt,name=output_uri,json=outputUri,proto3" json:"output_uri,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Audit         *v1.AuditFields        `protobuf:"bytes,10,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceJob) Reset() {
	*x = InferenceJob{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceJob) ProtoMessage() {}

func (x *InferenceJob) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceJob.ProtoReflect.Descriptor instead.
func (*InferenceJob) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InferenceJob) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InferenceJob) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *InferenceJob) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InferenceJob) GetStatus() InferenceJobStatus {
	if x != nil {
		return x.Status
	}
	return InferenceJobStatus_INFERENCE_JOB_STATUS_UNSPECIFIED
}

func (x *InferenceJob) GetOutputUri() string {
	if x != nil {
		return x.OutputUri
	}
	return ""
}

func (x *InferenceJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InferenceJob) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *InferenceJob) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *InferenceJob) GetAudit() *v1.AuditFields {
	if x != nil {
		return x.Audit
	}
	return nil
}

type RegisterModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Task          InferenceTask          `protobuf:"varint,4,opt,name=task,proto3,enum=p9e.space.earthobs.v1.InferenceTask" json:"task,omitempty"`
	Framework     string                 `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	ArtefactUri   string                 `protobuf:"bytes,6,opt,name=artefact_uri,json=artefactUri,proto3" json:"artefact_uri,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,7,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModelRequest) Reset() {
	*x = RegisterModelRequest{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelRequest) ProtoMessage() {}

func (x *RegisterModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelRequest.ProtoReflect.Descriptor instead.
func (*RegisterModelRequest) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterModelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterModelRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterModelRequest) GetTask() InferenceTask {
	if x != nil {
		return x.Task
	}
	return InferenceTask_INFERENCE_TASK_UNSPECIFIED
}

func (x *RegisterModelRequest) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *RegisterModelRequest) GetArtefactUri() string {
	if x != nil {
		return x.ArtefactUri
	}
	return ""
}

func (x *RegisterModelRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type RegisterModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModelResponse) Reset() {
	*x = RegisterModelResponse{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelResponse) ProtoMessage() {}

func (x *RegisterModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelResponse.ProtoReflect.Descriptor instead.
func (*RegisterModelResponse) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResponse.ProtoReflect.Descriptor instead.
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Task          *InferenceTask         `protobuf:"varint,2,opt,name=task,proto3,enum=p9e.space.earthobs.v1.InferenceTask,oneof" json:"task,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *ListModelsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListModelsRequest) GetTask() InferenceTask {
	if x != nil && x.Task != nil {
		return *x.Task
	}
	return InferenceTask_INFERENCE_TASK_UNSPECIFIED
}

func (x *ListModelsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type DeactivateModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateModelRequest) Reset() {
	*x = DeactivateModelRequest{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateModelRequest) ProtoMessage() {}

func (x *DeactivateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateModelRequest.ProtoReflect.Descriptor instead.
func (*DeactivateModelRequest) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *DeactivateModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeactivateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateModelResponse) Reset() {
	*x = DeactivateModelResponse{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateModelResponse) ProtoMessage() {}

func (x *DeactivateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateModelResponse.ProtoReflect.Descriptor instead.
func (*DeactivateModelResponse) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *DeactivateModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type SubmitInferenceJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitInferenceJobRequest) Reset() {
	*x = SubmitInferenceJobRequest{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitInferenceJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInferenceJobRequest) ProtoMessage() {}

func (x *SubmitInferenceJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInferenceJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitInferenceJobRequest) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitInferenceJobRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubmitInferenceJobRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SubmitInferenceJobRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type SubmitInferenceJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *InferenceJob          `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitInferenceJobResponse) Reset() {
	*x = SubmitInferenceJobResponse{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitInferenceJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInferenceJobResponse) ProtoMessage() {}

func (x *SubmitInferenceJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInferenceJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitInferenceJobResponse) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitInferenceJobResponse) GetJob() *InferenceJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetInferenceJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceJobRequest) Reset() {
	*x = GetInferenceJobRequest{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceJobRequest) ProtoMessage() {}

func (x *GetInferenceJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceJobRequest.ProtoReflect.Descriptor instead.
func (*GetInferenceJobRequest) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *GetInferenceJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInferenceJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *InferenceJob          `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceJobResponse) Reset() {
	*x = GetInferenceJobResponse{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceJobResponse) ProtoMessage() {}

func (x *GetInferenceJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceJobResponse.ProtoReflect.Descriptor instead.
func (*GetInferenceJobResponse) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *GetInferenceJobResponse) GetJob() *InferenceJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListInferenceJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        *InferenceJobStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=p9e.space.earthobs.v1.InferenceJobStatus,oneof" json:"status,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInferenceJobsRequest) Reset() {
	*x = ListInferenceJobsRequest{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInferenceJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInferenceJobsRequest) ProtoMessage() {}

func (x *ListInferenceJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInferenceJobsRequest.ProtoReflect.Descriptor instead.
func (*ListInferenceJobsRequest) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *ListInferenceJobsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListInferenceJobsRequest) GetStatus() InferenceJobStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return InferenceJobStatus_INFERENCE_JOB_STATUS_UNSPECIFIED
}

func (x *ListInferenceJobsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListInferenceJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*InferenceJob        `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInferenceJobsResponse) Reset() {
	*x = ListInferenceJobsResponse{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInferenceJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInferenceJobsResponse) ProtoMessage() {}

func (x *ListInferenceJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInferenceJobsResponse.ProtoReflect.Descriptor instead.
func (*ListInferenceJobsResponse) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *ListInferenceJobsResponse) GetJobs() []*InferenceJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListInferenceJobsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdateInferenceJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        InferenceJobStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=p9e.space.earthobs.v1.InferenceJobStatus" json:"status,omitempty"`
	OutputUri     string                 `protobuf:"bytes,3,opt,name=output_uri,json=outputUri,proto3" json:"output_uri,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInferenceJobStatusRequest) Reset() {
	*x = UpdateInferenceJobStatusRequest{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInferenceJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInferenceJobStatusRequest) ProtoMessage() {}

func (x *UpdateInferenceJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInferenceJobStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateInferenceJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateInferenceJobStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInferenceJobStatusRequest) GetStatus() InferenceJobStatus {
	if x != nil {
		return x.Status
	}
	return InferenceJobStatus_INFERENCE_JOB_STATUS_UNSPECIFIED
}

func (x *UpdateInferenceJobStatusRequest) GetOutputUri() string {
	if x != nil {
		return x.OutputUri
	}
	return ""
}

func (x *UpdateInferenceJobStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateInferenceJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *InferenceJob          `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInferenceJobStatusResponse) Reset() {
	*x = UpdateInferenceJobStatusResponse{}
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInferenceJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInferenceJobStatusResponse) ProtoMessage() {}

func (x *UpdateInferenceJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInferenceJobStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateInferenceJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateInferenceJobStatusResponse) GetJob() *InferenceJob {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_p9e_space_earthobs_v1_eo_analytics_proto protoreflect.FileDescriptor

const file_p9e_space_earthobs_v1_eo_analytics_proto_rawDesc = "" +
	"\n" +
	"(p9e/space/earthobs/v1/eo_analytics.proto\x12\x15p9e.space.earthobs.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a p9e/space/common/v1/common.proto\"\xd2\x02\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x128\n" +
	"\x04task\x18\x05 \x01(\x0e2$.p9e.space.earthobs.v1.InferenceTaskR\x04task\x12\x1c\n" +
	"\tframework\x18\x06 \x01(\tR\tframework\x12!\n" +
	"\fartefact_uri\x18\a \x01(\tR\vartefactUri\x12#\n" +
	"\rmetadata_json\x18\b \x01(\tR\fmetadataJson\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x126\n" +
	"\x05audit\x18\n" +
	" \x01(\v2 .p9e.space.common.v1.AuditFieldsR\x05audit\"\xa6\x03\n" +
	"\fInferenceJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\tR\x06itemId\x12A\n" +
	"\x06status\x18\x05 \x01(\x0e2).p9e.space.earthobs.v1.InferenceJobStatusR\x06status\x12\x1d\n" +
	"\n" +
	"output_uri\x18\x06 \x01(\tR\toutputUri\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x126\n" +
	"\x05audit\x18\n" +
	" \x01(\v2 .p9e.space.common.v1.AuditFieldsR\x05audit\"\xc5\x02\n" +
	"\x14RegisterModelRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btenantId\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01R\x04name\x12#\n" +
	"\aversion\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\aversion\x12D\n" +
	"\x04task\x18\x04 \x01(\x0e2$.p9e.space.earthobs.v1.InferenceTaskB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04task\x12'\n" +
	"\tframework\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\tframework\x12-\n" +
	"\fartefact_uri\x18\x06 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xe8\aR\vartefactUri\x12#\n" +
	"\rmetadata_json\x18\a \x01(\tR\fmetadataJson\"K\n" +
	"\x15RegisterModelResponse\x122\n" +
	"\x05model\x18\x01 \x01(\v2\x1c.p9e.space.earthobs.v1.ModelR\x05model\"+\n" +
	"\x0fGetModelRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"F\n" +
	"\x10GetModelResponse\x122\n" +
	"\x05model\x18\x01 \x01(\v2\x1c.p9e.space.earthobs.v1.ModelR\x05model\"\xb8\x01\n" +
	"\x11ListModelsRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btenantId\x12=\n" +
	"\x04task\x18\x02 \x01(\x0e2$.p9e.space.earthobs.v1.InferenceTaskH\x00R\x04task\x88\x01\x01\x124\n" +
	"\x04page\x18\x03 \x01(\v2 .p9e.space.common.v1.PageRequestR\x04pageB\a\n" +
	"\x05_task\"\x81\x01\n" +
	"\x12ListModelsResponse\x124\n" +
	"\x06models\x18\x01 \x03(\v2\x1c.p9e.space.earthobs.v1.ModelR\x06models\x125\n" +
	"\x04page\x18\x02 \x01(\v2!.p9e.space.common.v1.PageResponseR\x04page\"2\n" +
	"\x16DeactivateModelRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"M\n" +
	"\x17DeactivateModelResponse\x122\n" +
	"\x05model\x18\x01 \x01(\v2\x1c.p9e.space.earthobs.v1.ModelR\x05model\"\x8a\x01\n" +
	"\x19SubmitInferenceJobRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btenantId\x12#\n" +
	"\bmodel_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\amodelId\x12!\n" +
	"\aitem_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06itemId\"S\n" +
	"\x1aSubmitInferenceJobResponse\x125\n" +
	"\x03job\x18\x01 \x01(\v2#.p9e.space.earthobs.v1.InferenceJobR\x03job\"2\n" +
	"\x16GetInferenceJobRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"P\n" +
	"\x17GetInferenceJobResponse\x125\n" +
	"\x03job\x18\x01 \x01(\v2#.p9e.space.earthobs.v1.InferenceJobR\x03job\"\xca\x01\n" +
	"\x18ListInferenceJobsRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btenantId\x12F\n" +
	"\x06status\x18\x02 \x01(\x0e2).p9e.space.earthobs.v1.InferenceJobStatusH\x00R\x06status\x88\x01\x01\x124\n" +
	"\x04page\x18\x03 \x01(\v2 .p9e.space.common.v1.PageRequestR\x04pageB\t\n" +
	"\a_status\"\x8b\x01\n" +
	"\x19ListInferenceJobsResponse\x127\n" +
	"\x04jobs\x18\x01 \x03(\v2#.p9e.space.earthobs.v1.InferenceJobR\x04jobs\x125\n" +
	"\x04page\x18\x02 \x01(\v2!.p9e.space.common.v1.PageResponseR\x04page\"\xce\x01\n" +
	"\x1fUpdateInferenceJobStatusRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12M\n" +
	"\x06status\x18\x02 \x01(\x0e2).p9e.space.earthobs.v1.InferenceJobStatusB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06status\x12\x1d\n" +
	"\n" +
	"output_uri\x18\x03 \x01(\tR\toutputUri\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"Y\n" +
	" UpdateInferenceJobStatusResponse\x125\n" +
	"\x03job\x18\x01 \x01(\v2#.p9e.space.earthobs.v1.InferenceJobR\x03job*\x91\x01\n" +
	"\rInferenceTask\x12\x1e\n" +
	"\x1aINFERENCE_TASK_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18INFERENCE_TASK_DETECTION\x10\x01\x12\x1f\n" +
	"\x1bINFERENCE_TASK_SEGMENTATION\x10\x02\x12!\n" +
	"\x1dINFERENCE_TASK_CLASSIFICATION\x10\x03*\xc3\x01\n" +
	"\x12InferenceJobStatus\x12$\n" +
	" INFERENCE_JOB_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cINFERENCE_JOB_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cINFERENCE_JOB_STATUS_RUNNING\x10\x02\x12\"\n" +
	"\x1eINFERENCE_JOB_STATUS_SUCCEEDED\x10\x03\x12\x1f\n" +
	"\x1bINFERENCE_JOB_STATUS_FAILED\x10\x042\xa3\a\n" +
	"\x10AnalyticsService\x12j\n" +
	"\rRegisterModel\x12+.p9e.space.earthobs.v1.RegisterModelRequest\x1a,.p9e.space.earthobs.v1.RegisterModelResponse\x12[\n" +
	"\bGetModel\x12&.p9e.space.earthobs.v1.GetModelRequest\x1a'.p9e.space.earthobs.v1.GetModelResponse\x12a\n" +
	"\n" +
	"ListModels\x12(.p9e.space.earthobs.v1.ListModelsRequest\x1a).p9e.space.earthobs.v1.ListModelsResponse\x12p\n" +
	"\x0fDeactivateModel\x12-.p9e.space.earthobs.v1.DeactivateModelRequest\x1a..p9e.space.earthobs.v1.DeactivateModelResponse\x12y\n" +
	"\x12SubmitInferenceJob\x120.p9e.space.earthobs.v1.SubmitInferenceJobRequest\x1a1.p9e.space.earthobs.v1.SubmitInferenceJobResponse\x12p\n" +
	"\x0fGetInferenceJob\x12-.p9e.space.earthobs.v1.GetInferenceJobRequest\x1a..p9e.space.earthobs.v1.GetInferenceJobResponse\x12v\n" +
	"\x11ListInferenceJobs\x12/.p9e.space.earthobs.v1.ListInferenceJobsRequest\x1a0.p9e.space.earthobs.v1.ListInferenceJobsResponse\x12\x8b\x01\n" +
	"\x18UpdateInferenceJobStatus\x126.p9e.space.earthobs.v1.UpdateInferenceJobStatusRequest\x1a7.p9e.space.earthobs.v1.UpdateInferenceJobStatusResponseB\xe5\x01\n" +
	"\x19com.p9e.space.earthobs.v1B\x10EoAnalyticsProtoP\x01Z?github.com/ppusapati/space/api/p9e/space/earthobs/v1;earthobsv1\xa2\x02\x03PSE\xaa\x02\x15P9e.Space.Earthobs.V1\xca\x02\x15P9e\\Space\\Earthobs\\V1\xe2\x02!P9e\\Space\\Earthobs\\V1\\GPBMetadata\xea\x02\x18P9e::Space::Earthobs::V1b\x06proto3"

var (
	file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescOnce sync.Once
	file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescData []byte
)

func file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescGZIP() []byte {
	file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescOnce.Do(func() {
		file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p9e_space_earthobs_v1_eo_analytics_proto_rawDesc), len(file_p9e_space_earthobs_v1_eo_analytics_proto_rawDesc)))
	})
	return file_p9e_space_earthobs_v1_eo_analytics_proto_rawDescData
}

var file_p9e_space_earthobs_v1_eo_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_p9e_space_earthobs_v1_eo_analytics_proto_goTypes = []any{
	(InferenceTask)(0),                       // 0: p9e.space.earthobs.v1.InferenceTask
	(InferenceJobStatus)(0),                  // 1: p9e.space.earthobs.v1.InferenceJobStatus
	(*Model)(nil),                            // 2: p9e.space.earthobs.v1.Model
	(*InferenceJob)(nil),                     // 3: p9e.space.earthobs.v1.InferenceJob
	(*RegisterModelRequest)(nil),             // 4: p9e.space.earthobs.v1.RegisterModelRequest
	(*RegisterModelResponse)(nil),            // 5: p9e.space.earthobs.v1.RegisterModelResponse
	(*GetModelRequest)(nil),                  // 6: p9e.space.earthobs.v1.GetModelRequest
	(*GetModelResponse)(nil),                 // 7: p9e.space.earthobs.v1.GetModelResponse
	(*ListModelsRequest)(nil),                // 8: p9e.space.earthobs.v1.ListModelsRequest
	(*ListModelsResponse)(nil),               // 9: p9e.space.earthobs.v1.ListModelsResponse
	(*DeactivateModelRequest)(nil),           // 10: p9e.space.earthobs.v1.DeactivateModelRequest
	(*DeactivateModelResponse)(nil),          // 11: p9e.space.earthobs.v1.DeactivateModelResponse
	(*SubmitInferenceJobRequest)(nil),        // 12: p9e.space.earthobs.v1.SubmitInferenceJobRequest
	(*SubmitInferenceJobResponse)(nil),       // 13: p9e.space.earthobs.v1.SubmitInferenceJobResponse
	(*GetInferenceJobRequest)(nil),           // 14: p9e.space.earthobs.v1.GetInferenceJobRequest
	(*GetInferenceJobResponse)(nil),          // 15: p9e.space.earthobs.v1.GetInferenceJobResponse
	(*ListInferenceJobsRequest)(nil),         // 16: p9e.space.earthobs.v1.ListInferenceJobsRequest
	(*ListInferenceJobsResponse)(nil),        // 17: p9e.space.earthobs.v1.ListInferenceJobsResponse
	(*UpdateInferenceJobStatusRequest)(nil),  // 18: p9e.space.earthobs.v1.UpdateInferenceJobStatusRequest
	(*UpdateInferenceJobStatusResponse)(nil), // 19: p9e.space.earthobs.v1.UpdateInferenceJobStatusResponse
	(*v1.AuditFields)(nil),                   // 20: p9e.space.common.v1.AuditFields
	(*timestamppb.Timestamp)(nil),            // 21: google.protobuf.Timestamp
	(*v1.PageRequest)(nil),                   // 22: p9e.space.common.v1.PageRequest
	(*v1.PageResponse)(nil),                  // 23: p9e.space.common.v1.PageResponse
}
var file_p9e_space_earthobs_v1_eo_analytics_proto_depIdxs = []int32{
	0,  // 0: p9e.space.earthobs.v1.Model.task:type_name -> p9e.space.earthobs.v1.InferenceTask
	20, // 1: p9e.space.earthobs.v1.Model.audit:type_name -> p9e.space.common.v1.AuditFields
	1,  // 2: p9e.space.earthobs.v1.InferenceJob.status:type_name -> p9e.space.earthobs.v1.InferenceJobStatus
	21, // 3: p9e.space.earthobs.v1.InferenceJob.started_at:type_name -> google.protobuf.Timestamp
	21, // 4: p9e.space.earthobs.v1.InferenceJob.finished_at:type_name -> google.protobuf.Timestamp
	20, // 5: p9e.space.earthobs.v1.InferenceJob.audit:type_name -> p9e.space.common.v1.AuditFields
	0,  // 6: p9e.space.earthobs.v1.RegisterModelRequest.task:type_name -> p9e.space.earthobs.v1.InferenceTask
	2,  // 7: p9e.space.earthobs.v1.RegisterModelResponse.model:type_name -> p9e.space.earthobs.v1.Model
	2,  // 8: p9e.space.earthobs.v1.GetModelResponse.model:type_name -> p9e.space.earthobs.v1.Model
	0,  // 9: p9e.space.earthobs.v1.ListModelsRequest.task:type_name -> p9e.space.earthobs.v1.InferenceTask
	22, // 10: p9e.space.earthobs.v1.ListModelsRequest.page:type_name -> p9e.space.common.v1.PageRequest
	2,  // 11: p9e.space.earthobs.v1.ListModelsResponse.models:type_name -> p9e.space.earthobs.v1.Model
	23, // 12: p9e.space.earthobs.v1.ListModelsResponse.page:type_name -> p9e.space.common.v1.PageResponse
	2,  // 13: p9e.space.earthobs.v1.DeactivateModelResponse.model:type_name -> p9e.space.earthobs.v1.Model
	3,  // 14: p9e.space.earthobs.v1.SubmitInferenceJobResponse.job:type_name -> p9e.space.earthobs.v1.InferenceJob
	3,  // 15: p9e.space.earthobs.v1.GetInferenceJobResponse.job:type_name -> p9e.space.earthobs.v1.InferenceJob
	1,  // 16: p9e.space.earthobs.v1.ListInferenceJobsRequest.status:type_name -> p9e.space.earthobs.v1.InferenceJobStatus
	22, // 17: p9e.space.earthobs.v1.ListInferenceJobsRequest.page:type_name -> p9e.space.common.v1.PageRequest
	3,  // 18: p9e.space.earthobs.v1.ListInferenceJobsResponse.jobs:type_name -> p9e.space.earthobs.v1.InferenceJob
	23, // 19: p9e.space.earthobs.v1.ListInferenceJobsResponse.page:type_name -> p9e.space.common.v1.PageResponse
	1,  // 20: p9e.space.earthobs.v1.UpdateInferenceJobStatusRequest.status:type_name -> p9e.space.earthobs.v1.InferenceJobStatus
	3,  // 21: p9e.space.earthobs.v1.UpdateInferenceJobStatusResponse.job:type_name -> p9e.space.earthobs.v1.InferenceJob
	4,  // 22: p9e.space.earthobs.v1.AnalyticsService.RegisterModel:input_type -> p9e.space.earthobs.v1.RegisterModelRequest
	6,  // 23: p9e.space.earthobs.v1.AnalyticsService.GetModel:input_type -> p9e.space.earthobs.v1.GetModelRequest
	8,  // 24: p9e.space.earthobs.v1.AnalyticsService.ListModels:input_type -> p9e.space.earthobs.v1.ListModelsRequest
	10, // 25: p9e.space.earthobs.v1.AnalyticsService.DeactivateModel:input_type -> p9e.space.earthobs.v1.DeactivateModelRequest
	12, // 26: p9e.space.earthobs.v1.AnalyticsService.SubmitInferenceJob:input_type -> p9e.space.earthobs.v1.SubmitInferenceJobRequest
	14, // 27: p9e.space.earthobs.v1.AnalyticsService.GetInferenceJob:input_type -> p9e.space.earthobs.v1.GetInferenceJobRequest
	16, // 28: p9e.space.earthobs.v1.AnalyticsService.ListInferenceJobs:input_type -> p9e.space.earthobs.v1.ListInferenceJobsRequest
	18, // 29: p9e.space.earthobs.v1.AnalyticsService.UpdateInferenceJobStatus:input_type -> p9e.space.earthobs.v1.UpdateInferenceJobStatusRequest
	5,  // 30: p9e.space.earthobs.v1.AnalyticsService.RegisterModel:output_type -> p9e.space.earthobs.v1.RegisterModelResponse
	7,  // 31: p9e.space.earthobs.v1.AnalyticsService.GetModel:output_type -> p9e.space.earthobs.v1.GetModelResponse
	9,  // 32: p9e.space.earthobs.v1.AnalyticsService.ListModels:output_type -> p9e.space.earthobs.v1.ListModelsResponse
	11, // 33: p9e.space.earthobs.v1.AnalyticsService.DeactivateModel:output_type -> p9e.space.earthobs.v1.DeactivateModelResponse
	13, // 34: p9e.space.earthobs.v1.AnalyticsService.SubmitInferenceJob:output_type -> p9e.space.earthobs.v1.SubmitInferenceJobResponse
	15, // 35: p9e.space.earthobs.v1.AnalyticsService.GetInferenceJob:output_type -> p9e.space.earthobs.v1.GetInferenceJobResponse
	17, // 36: p9e.space.earthobs.v1.AnalyticsService.ListInferenceJobs:output_type -> p9e.space.earthobs.v1.ListInferenceJobsResponse
	19, // 37: p9e.space.earthobs.v1.AnalyticsService.UpdateInferenceJobStatus:output_type -> p9e.space.earthobs.v1.UpdateInferenceJobStatusResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_p9e_space_earthobs_v1_eo_analytics_proto_init() }
func file_p9e_space_earthobs_v1_eo_analytics_proto_init() {
	if File_p9e_space_earthobs_v1_eo_analytics_proto != nil {
		return
	}
	file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[6].OneofWrappers = []any{}
	file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p9e_space_earthobs_v1_eo_analytics_proto_rawDesc), len(file_p9e_space_earthobs_v1_eo_analytics_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_p9e_space_earthobs_v1_eo_analytics_proto_goTypes,
		DependencyIndexes: file_p9e_space_earthobs_v1_eo_analytics_proto_depIdxs,
		EnumInfos:         file_p9e_space_earthobs_v1_eo_analytics_proto_enumTypes,
		MessageInfos:      file_p9e_space_earthobs_v1_eo_analytics_proto_msgTypes,
	}.Build()
	File_p9e_space_earthobs_v1_eo_analytics_proto = out.File
	file_p9e_space_earthobs_v1_eo_analytics_proto_goTypes = nil
	file_p9e_space_earthobs_v1_eo_analytics_proto_depIdxs = nil
}
