// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gs_ingest.proto

package gsingestv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	fields "p9e.in/samavaya/packages/api/v1/fields"
	pagination "p9e.in/samavaya/packages/api/v1/pagination"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestStatus int32

const (
	IngestStatus_INGEST_STATUS_UNSPECIFIED IngestStatus = 0
	IngestStatus_INGEST_STATUS_QUEUED      IngestStatus = 1
	IngestStatus_INGEST_STATUS_ACTIVE      IngestStatus = 2
	IngestStatus_INGEST_STATUS_COMPLETED   IngestStatus = 3
	IngestStatus_INGEST_STATUS_FAILED      IngestStatus = 4
	IngestStatus_INGEST_STATUS_CANCELED    IngestStatus = 5
)

// Enum value maps for IngestStatus.
var (
	IngestStatus_name = map[int32]string{
		0: "INGEST_STATUS_UNSPECIFIED",
		1: "INGEST_STATUS_QUEUED",
		2: "INGEST_STATUS_ACTIVE",
		3: "INGEST_STATUS_COMPLETED",
		4: "INGEST_STATUS_FAILED",
		5: "INGEST_STATUS_CANCELED",
	}
	IngestStatus_value = map[string]int32{
		"INGEST_STATUS_UNSPECIFIED": 0,
		"INGEST_STATUS_QUEUED":      1,
		"INGEST_STATUS_ACTIVE":      2,
		"INGEST_STATUS_COMPLETED":   3,
		"INGEST_STATUS_FAILED":      4,
		"INGEST_STATUS_CANCELED":    5,
	}
)

func (x IngestStatus) Enum() *IngestStatus {
	p := new(IngestStatus)
	*p = x
	return p
}

func (x IngestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gs_ingest_proto_enumTypes[0].Descriptor()
}

func (IngestStatus) Type() protoreflect.EnumType {
	return &file_gs_ingest_proto_enumTypes[0]
}

func (x IngestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestStatus.Descriptor instead.
func (IngestStatus) EnumDescriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{0}
}

type IngestSession struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BookingId      string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	PassId         string                 `protobuf:"bytes,4,opt,name=pass_id,json=passId,proto3" json:"pass_id,omitempty"`
	StationId      string                 `protobuf:"bytes,5,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	SatelliteId    string                 `protobuf:"bytes,6,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	Status         IngestStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=p9e.space.gsingest.v1.IngestStatus" json:"status,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	FramesReceived uint64                 `protobuf:"varint,10,opt,name=frames_received,json=framesReceived,proto3" json:"frames_received,omitempty"`
	BytesReceived  uint64                 `protobuf:"varint,11,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Fields         *fields.Fields         `protobuf:"bytes,13,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestSession) Reset() {
	*x = IngestSession{}
	mi := &file_gs_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSession) ProtoMessage() {}

func (x *IngestSession) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSession.ProtoReflect.Descriptor instead.
func (*IngestSession) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestSession) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IngestSession) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *IngestSession) GetPassId() string {
	if x != nil {
		return x.PassId
	}
	return ""
}

func (x *IngestSession) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *IngestSession) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *IngestSession) GetStatus() IngestStatus {
	if x != nil {
		return x.Status
	}
	return IngestStatus_INGEST_STATUS_UNSPECIFIED
}

func (x *IngestSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *IngestSession) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *IngestSession) GetFramesReceived() uint64 {
	if x != nil {
		return x.FramesReceived
	}
	return 0
}

func (x *IngestSession) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *IngestSession) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *IngestSession) GetFields() *fields.Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DownlinkFrame struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Apid             uint32                 `protobuf:"varint,4,opt,name=apid,proto3" json:"apid,omitempty"`
	VirtualChannel   uint32                 `protobuf:"varint,5,opt,name=virtual_channel,json=virtualChannel,proto3" json:"virtual_channel,omitempty"`
	SequenceCount    uint64                 `protobuf:"varint,6,opt,name=sequence_count,json=sequenceCount,proto3" json:"sequence_count,omitempty"`
	GroundTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ground_time,json=groundTime,proto3" json:"ground_time,omitempty"`
	PayloadSizeBytes uint64                 `protobuf:"varint,8,opt,name=payload_size_bytes,json=payloadSizeBytes,proto3" json:"payload_size_bytes,omitempty"`
	PayloadSha256    string                 `protobuf:"bytes,9,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"` // 64-char hex
	PayloadUri       string                 `protobuf:"bytes,10,opt,name=payload_uri,json=payloadUri,proto3" json:"payload_uri,omitempty"`         // s3:// URI of raw bytes
	FrameType        string                 `protobuf:"bytes,11,opt,name=frame_type,json=frameType,proto3" json:"frame_type,omitempty"`            // "TM"|"AOS"|"VCID"|"FILE"|...
	Fields           *fields.Fields         `protobuf:"bytes,12,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DownlinkFrame) Reset() {
	*x = DownlinkFrame{}
	mi := &file_gs_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkFrame) ProtoMessage() {}

func (x *DownlinkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkFrame.ProtoReflect.Descriptor instead.
func (*DownlinkFrame) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *DownlinkFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownlinkFrame) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DownlinkFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DownlinkFrame) GetApid() uint32 {
	if x != nil {
		return x.Apid
	}
	return 0
}

func (x *DownlinkFrame) GetVirtualChannel() uint32 {
	if x != nil {
		return x.VirtualChannel
	}
	return 0
}

func (x *DownlinkFrame) GetSequenceCount() uint64 {
	if x != nil {
		return x.SequenceCount
	}
	return 0
}

func (x *DownlinkFrame) GetGroundTime() *timestamppb.Timestamp {
	if x != nil {
		return x.GroundTime
	}
	return nil
}

func (x *DownlinkFrame) GetPayloadSizeBytes() uint64 {
	if x != nil {
		return x.PayloadSizeBytes
	}
	return 0
}

func (x *DownlinkFrame) GetPayloadSha256() string {
	if x != nil {
		return x.PayloadSha256
	}
	return ""
}

func (x *DownlinkFrame) GetPayloadUri() string {
	if x != nil {
		return x.PayloadUri
	}
	return ""
}

func (x *DownlinkFrame) GetFrameType() string {
	if x != nil {
		return x.FrameType
	}
	return ""
}

func (x *DownlinkFrame) GetFields() *fields.Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type StartIngestSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	PassId        string                 `protobuf:"bytes,3,opt,name=pass_id,json=passId,proto3" json:"pass_id,omitempty"`
	StationId     string                 `protobuf:"bytes,4,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	SatelliteId   string                 `protobuf:"bytes,5,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartIngestSessionRequest) Reset() {
	*x = StartIngestSessionRequest{}
	mi := &file_gs_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartIngestSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartIngestSessionRequest) ProtoMessage() {}

func (x *StartIngestSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartIngestSessionRequest.ProtoReflect.Descriptor instead.
func (*StartIngestSessionRequest) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *StartIngestSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StartIngestSessionRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *StartIngestSessionRequest) GetPassId() string {
	if x != nil {
		return x.PassId
	}
	return ""
}

func (x *StartIngestSessionRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *StartIngestSessionRequest) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

type StartIngestSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *IngestSession         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartIngestSessionResponse) Reset() {
	*x = StartIngestSessionResponse{}
	mi := &file_gs_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartIngestSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartIngestSessionResponse) ProtoMessage() {}

func (x *StartIngestSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartIngestSessionResponse.ProtoReflect.Descriptor instead.
func (*StartIngestSessionResponse) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *StartIngestSessionResponse) GetSession() *IngestSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetIngestSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIngestSessionRequest) Reset() {
	*x = GetIngestSessionRequest{}
	mi := &file_gs_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngestSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngestSessionRequest) ProtoMessage() {}

func (x *GetIngestSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngestSessionRequest.ProtoReflect.Descriptor instead.
func (*GetIngestSessionRequest) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *GetIngestSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIngestSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *IngestSession         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIngestSessionResponse) Reset() {
	*x = GetIngestSessionResponse{}
	mi := &file_gs_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngestSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngestSessionResponse) ProtoMessage() {}

func (x *GetIngestSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngestSessionResponse.ProtoReflect.Descriptor instead.
func (*GetIngestSessionResponse) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *GetIngestSessionResponse) GetSession() *IngestSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListIngestSessionsRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	TenantId      string                        `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	StationId     string                        `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	SatelliteId   string                        `protobuf:"bytes,3,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	Status        *IngestStatus                 `protobuf:"varint,4,opt,name=status,proto3,enum=p9e.space.gsingest.v1.IngestStatus,oneof" json:"status,omitempty"`
	Page          *pagination.PaginationRequest `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIngestSessionsRequest) Reset() {
	*x = ListIngestSessionsRequest{}
	mi := &file_gs_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIngestSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIngestSessionsRequest) ProtoMessage() {}

func (x *ListIngestSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIngestSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListIngestSessionsRequest) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{6}
}

func (x *ListIngestSessionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListIngestSessionsRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *ListIngestSessionsRequest) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *ListIngestSessionsRequest) GetStatus() IngestStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return IngestStatus_INGEST_STATUS_UNSPECIFIED
}

func (x *ListIngestSessionsRequest) GetPage() *pagination.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListIngestSessionsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Sessions      []*IngestSession               `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Page          *pagination.PaginationResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIngestSessionsResponse) Reset() {
	*x = ListIngestSessionsResponse{}
	mi := &file_gs_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIngestSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIngestSessionsResponse) ProtoMessage() {}

func (x *ListIngestSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIngestSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListIngestSessionsResponse) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{7}
}

func (x *ListIngestSessionsResponse) GetSessions() []*IngestSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListIngestSessionsResponse) GetPage() *pagination.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdateIngestStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        IngestStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=p9e.space.gsingest.v1.IngestStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIngestStatusRequest) Reset() {
	*x = UpdateIngestStatusRequest{}
	mi := &file_gs_ingest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIngestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIngestStatusRequest) ProtoMessage() {}

func (x *UpdateIngestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIngestStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateIngestStatusRequest) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateIngestStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateIngestStatusRequest) GetStatus() IngestStatus {
	if x != nil {
		return x.Status
	}
	return IngestStatus_INGEST_STATUS_UNSPECIFIED
}

func (x *UpdateIngestStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateIngestStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *IngestSession         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIngestStatusResponse) Reset() {
	*x = UpdateIngestStatusResponse{}
	mi := &file_gs_ingest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIngestStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIngestStatusResponse) ProtoMessage() {}

func (x *UpdateIngestStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIngestStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateIngestStatusResponse) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateIngestStatusResponse) GetSession() *IngestSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type RecordDownlinkFrameRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Apid             uint32                 `protobuf:"varint,3,opt,name=apid,proto3" json:"apid,omitempty"`
	VirtualChannel   uint32                 `protobuf:"varint,4,opt,name=virtual_channel,json=virtualChannel,proto3" json:"virtual_channel,omitempty"`
	SequenceCount    uint64                 `protobuf:"varint,5,opt,name=sequence_count,json=sequenceCount,proto3" json:"sequence_count,omitempty"`
	GroundTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ground_time,json=groundTime,proto3" json:"ground_time,omitempty"`
	PayloadSizeBytes uint64                 `protobuf:"varint,7,opt,name=payload_size_bytes,json=payloadSizeBytes,proto3" json:"payload_size_bytes,omitempty"`
	PayloadSha256    string                 `protobuf:"bytes,8,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	PayloadUri       string                 `protobuf:"bytes,9,opt,name=payload_uri,json=payloadUri,proto3" json:"payload_uri,omitempty"`
	FrameType        string                 `protobuf:"bytes,10,opt,name=frame_type,json=frameType,proto3" json:"frame_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecordDownlinkFrameRequest) Reset() {
	*x = RecordDownlinkFrameRequest{}
	mi := &file_gs_ingest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordDownlinkFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDownlinkFrameRequest) ProtoMessage() {}

func (x *RecordDownlinkFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDownlinkFrameRequest.ProtoReflect.Descriptor instead.
func (*RecordDownlinkFrameRequest) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{10}
}

func (x *RecordDownlinkFrameRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RecordDownlinkFrameRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecordDownlinkFrameRequest) GetApid() uint32 {
	if x != nil {
		return x.Apid
	}
	return 0
}

func (x *RecordDownlinkFrameRequest) GetVirtualChannel() uint32 {
	if x != nil {
		return x.VirtualChannel
	}
	return 0
}

func (x *RecordDownlinkFrameRequest) GetSequenceCount() uint64 {
	if x != nil {
		return x.SequenceCount
	}
	return 0
}

func (x *RecordDownlinkFrameRequest) GetGroundTime() *timestamppb.Timestamp {
	if x != nil {
		return x.GroundTime
	}
	return nil
}

func (x *RecordDownlinkFrameRequest) GetPayloadSizeBytes() uint64 {
	if x != nil {
		return x.PayloadSizeBytes
	}
	return 0
}

func (x *RecordDownlinkFrameRequest) GetPayloadSha256() string {
	if x != nil {
		return x.PayloadSha256
	}
	return ""
}

func (x *RecordDownlinkFrameRequest) GetPayloadUri() string {
	if x != nil {
		return x.PayloadUri
	}
	return ""
}

func (x *RecordDownlinkFrameRequest) GetFrameType() string {
	if x != nil {
		return x.FrameType
	}
	return ""
}

type RecordDownlinkFrameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         *DownlinkFrame         `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordDownlinkFrameResponse) Reset() {
	*x = RecordDownlinkFrameResponse{}
	mi := &file_gs_ingest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordDownlinkFrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDownlinkFrameResponse) ProtoMessage() {}

func (x *RecordDownlinkFrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDownlinkFrameResponse.ProtoReflect.Descriptor instead.
func (*RecordDownlinkFrameResponse) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{11}
}

func (x *RecordDownlinkFrameResponse) GetFrame() *DownlinkFrame {
	if x != nil {
		return x.Frame
	}
	return nil
}

type GetDownlinkFrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownlinkFrameRequest) Reset() {
	*x = GetDownlinkFrameRequest{}
	mi := &file_gs_ingest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownlinkFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownlinkFrameRequest) ProtoMessage() {}

func (x *GetDownlinkFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownlinkFrameRequest.ProtoReflect.Descriptor instead.
func (*GetDownlinkFrameRequest) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{12}
}

func (x *GetDownlinkFrameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDownlinkFrameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         *DownlinkFrame         `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownlinkFrameResponse) Reset() {
	*x = GetDownlinkFrameResponse{}
	mi := &file_gs_ingest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownlinkFrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownlinkFrameResponse) ProtoMessage() {}

func (x *GetDownlinkFrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownlinkFrameResponse.ProtoReflect.Descriptor instead.
func (*GetDownlinkFrameResponse) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{13}
}

func (x *GetDownlinkFrameResponse) GetFrame() *DownlinkFrame {
	if x != nil {
		return x.Frame
	}
	return nil
}

type ListDownlinkFramesRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	TenantId      string                        `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                        `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FrameType     string                        `protobuf:"bytes,3,opt,name=frame_type,json=frameType,proto3" json:"frame_type,omitempty"`
	TimeStart     *timestamppb.Timestamp        `protobuf:"bytes,4,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       *timestamppb.Timestamp        `protobuf:"bytes,5,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	Page          *pagination.PaginationRequest `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDownlinkFramesRequest) Reset() {
	*x = ListDownlinkFramesRequest{}
	mi := &file_gs_ingest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDownlinkFramesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDownlinkFramesRequest) ProtoMessage() {}

func (x *ListDownlinkFramesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDownlinkFramesRequest.ProtoReflect.Descriptor instead.
func (*ListDownlinkFramesRequest) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{14}
}

func (x *ListDownlinkFramesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListDownlinkFramesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListDownlinkFramesRequest) GetFrameType() string {
	if x != nil {
		return x.FrameType
	}
	return ""
}

func (x *ListDownlinkFramesRequest) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *ListDownlinkFramesRequest) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

func (x *ListDownlinkFramesRequest) GetPage() *pagination.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListDownlinkFramesResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Frames        []*DownlinkFrame               `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	Page          *pagination.PaginationResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDownlinkFramesResponse) Reset() {
	*x = ListDownlinkFramesResponse{}
	mi := &file_gs_ingest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDownlinkFramesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDownlinkFramesResponse) ProtoMessage() {}

func (x *ListDownlinkFramesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gs_ingest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDownlinkFramesResponse.ProtoReflect.Descriptor instead.
func (*ListDownlinkFramesResponse) Descriptor() ([]byte, []int) {
	return file_gs_ingest_proto_rawDescGZIP(), []int{15}
}

func (x *ListDownlinkFramesResponse) GetFrames() []*DownlinkFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *ListDownlinkFramesResponse) GetPage() *pagination.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_gs_ingest_proto protoreflect.FileDescriptor

const file_gs_ingest_proto_rawDesc = "" +
	"\n" +
	"\x0fgs_ingest.proto\x12\x15p9e.space.gsingest.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\ffields.proto\x1a\x10pagination.proto\"\x9a\x04\n" +
	"\rIngestSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\x12\x17\n" +
	"\apass_id\x18\x04 \x01(\tR\x06passId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x05 \x01(\tR\tstationId\x12!\n" +
	"\fsatellite_id\x18\x06 \x01(\tR\vsatelliteId\x12;\n" +
	"\x06status\x18\a \x01(\x0e2#.p9e.space.gsingest.v1.IngestStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12'\n" +
	"\x0fframes_received\x18\n" +
	" \x01(\x04R\x0eframesReceived\x12%\n" +
	"\x0ebytes_received\x18\v \x01(\x04R\rbytesReceived\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\x126\n" +
	"\x06fields\x18\r \x01(\v2\x1e.packages.api.v1.fields.FieldsR\x06fields\"\xc9\x03\n" +
	"\rDownlinkFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04apid\x18\x04 \x01(\rR\x04apid\x12'\n" +
	"\x0fvirtual_channel\x18\x05 \x01(\rR\x0evirtualChannel\x12%\n" +
	"\x0esequence_count\x18\x06 \x01(\x04R\rsequenceCount\x12;\n" +
	"\vground_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"groundTime\x12,\n" +
	"\x12payload_size_bytes\x18\b \x01(\x04R\x10payloadSizeBytes\x12%\n" +
	"\x0epayload_sha256\x18\t \x01(\tR\rpayloadSha256\x12\x1f\n" +
	"\vpayload_uri\x18\n" +
	" \x01(\tR\n" +
	"payloadUri\x12\x1d\n" +
	"\n" +
	"frame_type\x18\v \x01(\tR\tframeType\x126\n" +
	"\x06fields\x18\f \x01(\v2\x1e.packages.api.v1.fields.FieldsR\x06fields\"\xe4\x01\n" +
	"\x19StartIngestSessionRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12'\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\tbookingId\x12!\n" +
	"\apass_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x06passId\x12'\n" +
	"\n" +
	"station_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\tstationId\x12+\n" +
	"\fsatellite_id\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\vsatelliteId\"\\\n" +
	"\x1aStartIngestSessionResponse\x12>\n" +
	"\asession\x18\x01 \x01(\v2$.p9e.space.gsingest.v1.IngestSessionR\asession\"3\n" +
	"\x17GetIngestSessionRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\"Z\n" +
	"\x18GetIngestSessionResponse\x12>\n" +
	"\asession\x18\x01 \x01(\v2$.p9e.space.gsingest.v1.IngestSessionR\asession\"\x94\x02\n" +
	"\x19ListIngestSessionsRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\tR\tstationId\x12!\n" +
	"\fsatellite_id\x18\x03 \x01(\tR\vsatelliteId\x12@\n" +
	"\x06status\x18\x04 \x01(\x0e2#.p9e.space.gsingest.v1.IngestStatusH\x00R\x06status\x88\x01\x01\x12A\n" +
	"\x04page\x18\x05 \x01(\v2-.packages.api.v1.pagination.PaginationRequestR\x04pageB\t\n" +
	"\a_status\"\xa2\x01\n" +
	"\x1aListIngestSessionsResponse\x12@\n" +
	"\bsessions\x18\x01 \x03(\v2$.p9e.space.gsingest.v1.IngestSessionR\bsessions\x12B\n" +
	"\x04page\x18\x02 \x01(\v2..packages.api.v1.pagination.PaginationResponseR\x04page\"\xa3\x01\n" +
	"\x19UpdateIngestStatusRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\x12G\n" +
	"\x06status\x18\x02 \x01(\x0e2#.p9e.space.gsingest.v1.IngestStatusB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\\\n" +
	"\x1aUpdateIngestStatusResponse\x12>\n" +
	"\asession\x18\x01 \x01(\v2$.p9e.space.gsingest.v1.IngestSessionR\asession\"\xcc\x03\n" +
	"\x1aRecordDownlinkFrameRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12'\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\tsessionId\x12\x12\n" +
	"\x04apid\x18\x03 \x01(\rR\x04apid\x12'\n" +
	"\x0fvirtual_channel\x18\x04 \x01(\rR\x0evirtualChannel\x12%\n" +
	"\x0esequence_count\x18\x05 \x01(\x04R\rsequenceCount\x12;\n" +
	"\vground_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"groundTime\x125\n" +
	"\x12payload_size_bytes\x18\a \x01(\x04B\a\xbaH\x042\x02 \x00R\x10payloadSizeBytes\x12/\n" +
	"\x0epayload_sha256\x18\b \x01(\tB\b\xbaH\x05r\x03\x98\x01@R\rpayloadSha256\x12+\n" +
	"\vpayload_uri\x18\t \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\bR\n" +
	"payloadUri\x12(\n" +
	"\n" +
	"frame_type\x18\n" +
	" \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 R\tframeType\"Y\n" +
	"\x1bRecordDownlinkFrameResponse\x12:\n" +
	"\x05frame\x18\x01 \x01(\v2$.p9e.space.gsingest.v1.DownlinkFrameR\x05frame\"3\n" +
	"\x17GetDownlinkFrameRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\x02id\"V\n" +
	"\x18GetDownlinkFrameResponse\x12:\n" +
	"\x05frame\x18\x01 \x01(\v2$.p9e.space.gsingest.v1.DownlinkFrameR\x05frame\"\xb5\x02\n" +
	"\x19ListDownlinkFramesRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x1aR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"frame_type\x18\x03 \x01(\tR\tframeType\x129\n" +
	"\n" +
	"time_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\x12A\n" +
	"\x04page\x18\x06 \x01(\v2-.packages.api.v1.pagination.PaginationRequestR\x04page\"\x9e\x01\n" +
	"\x1aListDownlinkFramesResponse\x12<\n" +
	"\x06frames\x18\x01 \x03(\v2$.p9e.space.gsingest.v1.DownlinkFrameR\x06frames\x12B\n" +
	"\x04page\x18\x02 \x01(\v2..packages.api.v1.pagination.PaginationResponseR\x04page*\xb4\x01\n" +
	"\fIngestStatus\x12\x1d\n" +
	"\x19INGEST_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INGEST_STATUS_QUEUED\x10\x01\x12\x18\n" +
	"\x14INGEST_STATUS_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17INGEST_STATUS_COMPLETED\x10\x03\x12\x18\n" +
	"\x14INGEST_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16INGEST_STATUS_CANCELED\x10\x052\xe3\x06\n" +
	"\rIngestService\x12y\n" +
	"\x12StartIngestSession\x120.p9e.space.gsingest.v1.StartIngestSessionRequest\x1a1.p9e.space.gsingest.v1.StartIngestSessionResponse\x12s\n" +
	"\x10GetIngestSession\x12..p9e.space.gsingest.v1.GetIngestSessionRequest\x1a/.p9e.space.gsingest.v1.GetIngestSessionResponse\x12y\n" +
	"\x12ListIngestSessions\x120.p9e.space.gsingest.v1.ListIngestSessionsRequest\x1a1.p9e.space.gsingest.v1.ListIngestSessionsResponse\x12y\n" +
	"\x12UpdateIngestStatus\x120.p9e.space.gsingest.v1.UpdateIngestStatusRequest\x1a1.p9e.space.gsingest.v1.UpdateIngestStatusResponse\x12|\n" +
	"\x13RecordDownlinkFrame\x121.p9e.space.gsingest.v1.RecordDownlinkFrameRequest\x1a2.p9e.space.gsingest.v1.RecordDownlinkFrameResponse\x12s\n" +
	"\x10GetDownlinkFrame\x12..p9e.space.gsingest.v1.GetDownlinkFrameRequest\x1a/.p9e.space.gsingest.v1.GetDownlinkFrameResponse\x12y\n" +
	"\x12ListDownlinkFrames\x120.p9e.space.gsingest.v1.ListDownlinkFramesRequest\x1a1.p9e.space.gsingest.v1.ListDownlinkFramesResponseB\xdf\x01\n" +
	"\x19com.p9e.space.gsingest.v1B\rGsIngestProtoP\x01Z<github.com/ppusapati/space/services/gs-ingest/api;gsingestv1\xa2\x02\x03PSG\xaa\x02\x15P9e.Space.Gsingest.V1\xca\x02\x15P9e\\Space\\Gsingest\\V1\xe2\x02!P9e\\Space\\Gsingest\\V1\\GPBMetadata\xea\x02\x18P9e::Space::Gsingest::V1b\x06proto3"

var (
	file_gs_ingest_proto_rawDescOnce sync.Once
	file_gs_ingest_proto_rawDescData []byte
)

func file_gs_ingest_proto_rawDescGZIP() []byte {
	file_gs_ingest_proto_rawDescOnce.Do(func() {
		file_gs_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gs_ingest_proto_rawDesc), len(file_gs_ingest_proto_rawDesc)))
	})
	return file_gs_ingest_proto_rawDescData
}

var file_gs_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gs_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gs_ingest_proto_goTypes = []any{
	(IngestStatus)(0),                     // 0: p9e.space.gsingest.v1.IngestStatus
	(*IngestSession)(nil),                 // 1: p9e.space.gsingest.v1.IngestSession
	(*DownlinkFrame)(nil),                 // 2: p9e.space.gsingest.v1.DownlinkFrame
	(*StartIngestSessionRequest)(nil),     // 3: p9e.space.gsingest.v1.StartIngestSessionRequest
	(*StartIngestSessionResponse)(nil),    // 4: p9e.space.gsingest.v1.StartIngestSessionResponse
	(*GetIngestSessionRequest)(nil),       // 5: p9e.space.gsingest.v1.GetIngestSessionRequest
	(*GetIngestSessionResponse)(nil),      // 6: p9e.space.gsingest.v1.GetIngestSessionResponse
	(*ListIngestSessionsRequest)(nil),     // 7: p9e.space.gsingest.v1.ListIngestSessionsRequest
	(*ListIngestSessionsResponse)(nil),    // 8: p9e.space.gsingest.v1.ListIngestSessionsResponse
	(*UpdateIngestStatusRequest)(nil),     // 9: p9e.space.gsingest.v1.UpdateIngestStatusRequest
	(*UpdateIngestStatusResponse)(nil),    // 10: p9e.space.gsingest.v1.UpdateIngestStatusResponse
	(*RecordDownlinkFrameRequest)(nil),    // 11: p9e.space.gsingest.v1.RecordDownlinkFrameRequest
	(*RecordDownlinkFrameResponse)(nil),   // 12: p9e.space.gsingest.v1.RecordDownlinkFrameResponse
	(*GetDownlinkFrameRequest)(nil),       // 13: p9e.space.gsingest.v1.GetDownlinkFrameRequest
	(*GetDownlinkFrameResponse)(nil),      // 14: p9e.space.gsingest.v1.GetDownlinkFrameResponse
	(*ListDownlinkFramesRequest)(nil),     // 15: p9e.space.gsingest.v1.ListDownlinkFramesRequest
	(*ListDownlinkFramesResponse)(nil),    // 16: p9e.space.gsingest.v1.ListDownlinkFramesResponse
	(*timestamppb.Timestamp)(nil),         // 17: google.protobuf.Timestamp
	(*fields.Fields)(nil),                 // 18: packages.api.v1.fields.Fields
	(*pagination.PaginationRequest)(nil),  // 19: packages.api.v1.pagination.PaginationRequest
	(*pagination.PaginationResponse)(nil), // 20: packages.api.v1.pagination.PaginationResponse
}
var file_gs_ingest_proto_depIdxs = []int32{
	0,  // 0: p9e.space.gsingest.v1.IngestSession.status:type_name -> p9e.space.gsingest.v1.IngestStatus
	17, // 1: p9e.space.gsingest.v1.IngestSession.started_at:type_name -> google.protobuf.Timestamp
	17, // 2: p9e.space.gsingest.v1.IngestSession.completed_at:type_name -> google.protobuf.Timestamp
	18, // 3: p9e.space.gsingest.v1.IngestSession.fields:type_name -> packages.api.v1.fields.Fields
	17, // 4: p9e.space.gsingest.v1.DownlinkFrame.ground_time:type_name -> google.protobuf.Timestamp
	18, // 5: p9e.space.gsingest.v1.DownlinkFrame.fields:type_name -> packages.api.v1.fields.Fields
	1,  // 6: p9e.space.gsingest.v1.StartIngestSessionResponse.session:type_name -> p9e.space.gsingest.v1.IngestSession
	1,  // 7: p9e.space.gsingest.v1.GetIngestSessionResponse.session:type_name -> p9e.space.gsingest.v1.IngestSession
	0,  // 8: p9e.space.gsingest.v1.ListIngestSessionsRequest.status:type_name -> p9e.space.gsingest.v1.IngestStatus
	19, // 9: p9e.space.gsingest.v1.ListIngestSessionsRequest.page:type_name -> packages.api.v1.pagination.PaginationRequest
	1,  // 10: p9e.space.gsingest.v1.ListIngestSessionsResponse.sessions:type_name -> p9e.space.gsingest.v1.IngestSession
	20, // 11: p9e.space.gsingest.v1.ListIngestSessionsResponse.page:type_name -> packages.api.v1.pagination.PaginationResponse
	0,  // 12: p9e.space.gsingest.v1.UpdateIngestStatusRequest.status:type_name -> p9e.space.gsingest.v1.IngestStatus
	1,  // 13: p9e.space.gsingest.v1.UpdateIngestStatusResponse.session:type_name -> p9e.space.gsingest.v1.IngestSession
	17, // 14: p9e.space.gsingest.v1.RecordDownlinkFrameRequest.ground_time:type_name -> google.protobuf.Timestamp
	2,  // 15: p9e.space.gsingest.v1.RecordDownlinkFrameResponse.frame:type_name -> p9e.space.gsingest.v1.DownlinkFrame
	2,  // 16: p9e.space.gsingest.v1.GetDownlinkFrameResponse.frame:type_name -> p9e.space.gsingest.v1.DownlinkFrame
	17, // 17: p9e.space.gsingest.v1.ListDownlinkFramesRequest.time_start:type_name -> google.protobuf.Timestamp
	17, // 18: p9e.space.gsingest.v1.ListDownlinkFramesRequest.time_end:type_name -> google.protobuf.Timestamp
	19, // 19: p9e.space.gsingest.v1.ListDownlinkFramesRequest.page:type_name -> packages.api.v1.pagination.PaginationRequest
	2,  // 20: p9e.space.gsingest.v1.ListDownlinkFramesResponse.frames:type_name -> p9e.space.gsingest.v1.DownlinkFrame
	20, // 21: p9e.space.gsingest.v1.ListDownlinkFramesResponse.page:type_name -> packages.api.v1.pagination.PaginationResponse
	3,  // 22: p9e.space.gsingest.v1.IngestService.StartIngestSession:input_type -> p9e.space.gsingest.v1.StartIngestSessionRequest
	5,  // 23: p9e.space.gsingest.v1.IngestService.GetIngestSession:input_type -> p9e.space.gsingest.v1.GetIngestSessionRequest
	7,  // 24: p9e.space.gsingest.v1.IngestService.ListIngestSessions:input_type -> p9e.space.gsingest.v1.ListIngestSessionsRequest
	9,  // 25: p9e.space.gsingest.v1.IngestService.UpdateIngestStatus:input_type -> p9e.space.gsingest.v1.UpdateIngestStatusRequest
	11, // 26: p9e.space.gsingest.v1.IngestService.RecordDownlinkFrame:input_type -> p9e.space.gsingest.v1.RecordDownlinkFrameRequest
	13, // 27: p9e.space.gsingest.v1.IngestService.GetDownlinkFrame:input_type -> p9e.space.gsingest.v1.GetDownlinkFrameRequest
	15, // 28: p9e.space.gsingest.v1.IngestService.ListDownlinkFrames:input_type -> p9e.space.gsingest.v1.ListDownlinkFramesRequest
	4,  // 29: p9e.space.gsingest.v1.IngestService.StartIngestSession:output_type -> p9e.space.gsingest.v1.StartIngestSessionResponse
	6,  // 30: p9e.space.gsingest.v1.IngestService.GetIngestSession:output_type -> p9e.space.gsingest.v1.GetIngestSessionResponse
	8,  // 31: p9e.space.gsingest.v1.IngestService.ListIngestSessions:output_type -> p9e.space.gsingest.v1.ListIngestSessionsResponse
	10, // 32: p9e.space.gsingest.v1.IngestService.UpdateIngestStatus:output_type -> p9e.space.gsingest.v1.UpdateIngestStatusResponse
	12, // 33: p9e.space.gsingest.v1.IngestService.RecordDownlinkFrame:output_type -> p9e.space.gsingest.v1.RecordDownlinkFrameResponse
	14, // 34: p9e.space.gsingest.v1.IngestService.GetDownlinkFrame:output_type -> p9e.space.gsingest.v1.GetDownlinkFrameResponse
	16, // 35: p9e.space.gsingest.v1.IngestService.ListDownlinkFrames:output_type -> p9e.space.gsingest.v1.ListDownlinkFramesResponse
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_gs_ingest_proto_init() }
func file_gs_ingest_proto_init() {
	if File_gs_ingest_proto != nil {
		return
	}
	file_gs_ingest_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gs_ingest_proto_rawDesc), len(file_gs_ingest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gs_ingest_proto_goTypes,
		DependencyIndexes: file_gs_ingest_proto_depIdxs,
		EnumInfos:         file_gs_ingest_proto_enumTypes,
		MessageInfos:      file_gs_ingest_proto_msgTypes,
	}.Build()
	File_gs_ingest_proto = out.File
	file_gs_ingest_proto_goTypes = nil
	file_gs_ingest_proto_depIdxs = nil
}
