// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sat_mission.proto

package satmissionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/ppusapati/space/services/sat-mission/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MissionServiceName is the fully-qualified name of the MissionService service.
	MissionServiceName = "p9e.space.satmission.v1.MissionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MissionServiceRegisterSatelliteProcedure is the fully-qualified name of the MissionService's
	// RegisterSatellite RPC.
	MissionServiceRegisterSatelliteProcedure = "/p9e.space.satmission.v1.MissionService/RegisterSatellite"
	// MissionServiceGetSatelliteProcedure is the fully-qualified name of the MissionService's
	// GetSatellite RPC.
	MissionServiceGetSatelliteProcedure = "/p9e.space.satmission.v1.MissionService/GetSatellite"
	// MissionServiceListSatellitesProcedure is the fully-qualified name of the MissionService's
	// ListSatellites RPC.
	MissionServiceListSatellitesProcedure = "/p9e.space.satmission.v1.MissionService/ListSatellites"
	// MissionServiceUpdateTLEProcedure is the fully-qualified name of the MissionService's UpdateTLE
	// RPC.
	MissionServiceUpdateTLEProcedure = "/p9e.space.satmission.v1.MissionService/UpdateTLE"
	// MissionServiceUpdateOrbitalStateProcedure is the fully-qualified name of the MissionService's
	// UpdateOrbitalState RPC.
	MissionServiceUpdateOrbitalStateProcedure = "/p9e.space.satmission.v1.MissionService/UpdateOrbitalState"
	// MissionServiceSetModeProcedure is the fully-qualified name of the MissionService's SetMode RPC.
	MissionServiceSetModeProcedure = "/p9e.space.satmission.v1.MissionService/SetMode"
)

// MissionServiceClient is a client for the p9e.space.satmission.v1.MissionService service.
type MissionServiceClient interface {
	RegisterSatellite(context.Context, *connect.Request[api.RegisterSatelliteRequest]) (*connect.Response[api.RegisterSatelliteResponse], error)
	GetSatellite(context.Context, *connect.Request[api.GetSatelliteRequest]) (*connect.Response[api.GetSatelliteResponse], error)
	ListSatellites(context.Context, *connect.Request[api.ListSatellitesRequest]) (*connect.Response[api.ListSatellitesResponse], error)
	UpdateTLE(context.Context, *connect.Request[api.UpdateTLERequest]) (*connect.Response[api.UpdateTLEResponse], error)
	UpdateOrbitalState(context.Context, *connect.Request[api.UpdateOrbitalStateRequest]) (*connect.Response[api.UpdateOrbitalStateResponse], error)
	SetMode(context.Context, *connect.Request[api.SetModeRequest]) (*connect.Response[api.SetModeResponse], error)
}

// NewMissionServiceClient constructs a client for the p9e.space.satmission.v1.MissionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMissionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MissionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	missionServiceMethods := api.File_sat_mission_proto.Services().ByName("MissionService").Methods()
	return &missionServiceClient{
		registerSatellite: connect.NewClient[api.RegisterSatelliteRequest, api.RegisterSatelliteResponse](
			httpClient,
			baseURL+MissionServiceRegisterSatelliteProcedure,
			connect.WithSchema(missionServiceMethods.ByName("RegisterSatellite")),
			connect.WithClientOptions(opts...),
		),
		getSatellite: connect.NewClient[api.GetSatelliteRequest, api.GetSatelliteResponse](
			httpClient,
			baseURL+MissionServiceGetSatelliteProcedure,
			connect.WithSchema(missionServiceMethods.ByName("GetSatellite")),
			connect.WithClientOptions(opts...),
		),
		listSatellites: connect.NewClient[api.ListSatellitesRequest, api.ListSatellitesResponse](
			httpClient,
			baseURL+MissionServiceListSatellitesProcedure,
			connect.WithSchema(missionServiceMethods.ByName("ListSatellites")),
			connect.WithClientOptions(opts...),
		),
		updateTLE: connect.NewClient[api.UpdateTLERequest, api.UpdateTLEResponse](
			httpClient,
			baseURL+MissionServiceUpdateTLEProcedure,
			connect.WithSchema(missionServiceMethods.ByName("UpdateTLE")),
			connect.WithClientOptions(opts...),
		),
		updateOrbitalState: connect.NewClient[api.UpdateOrbitalStateRequest, api.UpdateOrbitalStateResponse](
			httpClient,
			baseURL+MissionServiceUpdateOrbitalStateProcedure,
			connect.WithSchema(missionServiceMethods.ByName("UpdateOrbitalState")),
			connect.WithClientOptions(opts...),
		),
		setMode: connect.NewClient[api.SetModeRequest, api.SetModeResponse](
			httpClient,
			baseURL+MissionServiceSetModeProcedure,
			connect.WithSchema(missionServiceMethods.ByName("SetMode")),
			connect.WithClientOptions(opts...),
		),
	}
}

// missionServiceClient implements MissionServiceClient.
type missionServiceClient struct {
	registerSatellite  *connect.Client[api.RegisterSatelliteRequest, api.RegisterSatelliteResponse]
	getSatellite       *connect.Client[api.GetSatelliteRequest, api.GetSatelliteResponse]
	listSatellites     *connect.Client[api.ListSatellitesRequest, api.ListSatellitesResponse]
	updateTLE          *connect.Client[api.UpdateTLERequest, api.UpdateTLEResponse]
	updateOrbitalState *connect.Client[api.UpdateOrbitalStateRequest, api.UpdateOrbitalStateResponse]
	setMode            *connect.Client[api.SetModeRequest, api.SetModeResponse]
}

// RegisterSatellite calls p9e.space.satmission.v1.MissionService.RegisterSatellite.
func (c *missionServiceClient) RegisterSatellite(ctx context.Context, req *connect.Request[api.RegisterSatelliteRequest]) (*connect.Response[api.RegisterSatelliteResponse], error) {
	return c.registerSatellite.CallUnary(ctx, req)
}

// GetSatellite calls p9e.space.satmission.v1.MissionService.GetSatellite.
func (c *missionServiceClient) GetSatellite(ctx context.Context, req *connect.Request[api.GetSatelliteRequest]) (*connect.Response[api.GetSatelliteResponse], error) {
	return c.getSatellite.CallUnary(ctx, req)
}

// ListSatellites calls p9e.space.satmission.v1.MissionService.ListSatellites.
func (c *missionServiceClient) ListSatellites(ctx context.Context, req *connect.Request[api.ListSatellitesRequest]) (*connect.Response[api.ListSatellitesResponse], error) {
	return c.listSatellites.CallUnary(ctx, req)
}

// UpdateTLE calls p9e.space.satmission.v1.MissionService.UpdateTLE.
func (c *missionServiceClient) UpdateTLE(ctx context.Context, req *connect.Request[api.UpdateTLERequest]) (*connect.Response[api.UpdateTLEResponse], error) {
	return c.updateTLE.CallUnary(ctx, req)
}

// UpdateOrbitalState calls p9e.space.satmission.v1.MissionService.UpdateOrbitalState.
func (c *missionServiceClient) UpdateOrbitalState(ctx context.Context, req *connect.Request[api.UpdateOrbitalStateRequest]) (*connect.Response[api.UpdateOrbitalStateResponse], error) {
	return c.updateOrbitalState.CallUnary(ctx, req)
}

// SetMode calls p9e.space.satmission.v1.MissionService.SetMode.
func (c *missionServiceClient) SetMode(ctx context.Context, req *connect.Request[api.SetModeRequest]) (*connect.Response[api.SetModeResponse], error) {
	return c.setMode.CallUnary(ctx, req)
}

// MissionServiceHandler is an implementation of the p9e.space.satmission.v1.MissionService service.
type MissionServiceHandler interface {
	RegisterSatellite(context.Context, *connect.Request[api.RegisterSatelliteRequest]) (*connect.Response[api.RegisterSatelliteResponse], error)
	GetSatellite(context.Context, *connect.Request[api.GetSatelliteRequest]) (*connect.Response[api.GetSatelliteResponse], error)
	ListSatellites(context.Context, *connect.Request[api.ListSatellitesRequest]) (*connect.Response[api.ListSatellitesResponse], error)
	UpdateTLE(context.Context, *connect.Request[api.UpdateTLERequest]) (*connect.Response[api.UpdateTLEResponse], error)
	UpdateOrbitalState(context.Context, *connect.Request[api.UpdateOrbitalStateRequest]) (*connect.Response[api.UpdateOrbitalStateResponse], error)
	SetMode(context.Context, *connect.Request[api.SetModeRequest]) (*connect.Response[api.SetModeResponse], error)
}

// NewMissionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMissionServiceHandler(svc MissionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	missionServiceMethods := api.File_sat_mission_proto.Services().ByName("MissionService").Methods()
	missionServiceRegisterSatelliteHandler := connect.NewUnaryHandler(
		MissionServiceRegisterSatelliteProcedure,
		svc.RegisterSatellite,
		connect.WithSchema(missionServiceMethods.ByName("RegisterSatellite")),
		connect.WithHandlerOptions(opts...),
	)
	missionServiceGetSatelliteHandler := connect.NewUnaryHandler(
		MissionServiceGetSatelliteProcedure,
		svc.GetSatellite,
		connect.WithSchema(missionServiceMethods.ByName("GetSatellite")),
		connect.WithHandlerOptions(opts...),
	)
	missionServiceListSatellitesHandler := connect.NewUnaryHandler(
		MissionServiceListSatellitesProcedure,
		svc.ListSatellites,
		connect.WithSchema(missionServiceMethods.ByName("ListSatellites")),
		connect.WithHandlerOptions(opts...),
	)
	missionServiceUpdateTLEHandler := connect.NewUnaryHandler(
		MissionServiceUpdateTLEProcedure,
		svc.UpdateTLE,
		connect.WithSchema(missionServiceMethods.ByName("UpdateTLE")),
		connect.WithHandlerOptions(opts...),
	)
	missionServiceUpdateOrbitalStateHandler := connect.NewUnaryHandler(
		MissionServiceUpdateOrbitalStateProcedure,
		svc.UpdateOrbitalState,
		connect.WithSchema(missionServiceMethods.ByName("UpdateOrbitalState")),
		connect.WithHandlerOptions(opts...),
	)
	missionServiceSetModeHandler := connect.NewUnaryHandler(
		MissionServiceSetModeProcedure,
		svc.SetMode,
		connect.WithSchema(missionServiceMethods.ByName("SetMode")),
		connect.WithHandlerOptions(opts...),
	)
	return "/p9e.space.satmission.v1.MissionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MissionServiceRegisterSatelliteProcedure:
			missionServiceRegisterSatelliteHandler.ServeHTTP(w, r)
		case MissionServiceGetSatelliteProcedure:
			missionServiceGetSatelliteHandler.ServeHTTP(w, r)
		case MissionServiceListSatellitesProcedure:
			missionServiceListSatellitesHandler.ServeHTTP(w, r)
		case MissionServiceUpdateTLEProcedure:
			missionServiceUpdateTLEHandler.ServeHTTP(w, r)
		case MissionServiceUpdateOrbitalStateProcedure:
			missionServiceUpdateOrbitalStateHandler.ServeHTTP(w, r)
		case MissionServiceSetModeProcedure:
			missionServiceSetModeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMissionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMissionServiceHandler struct{}

func (UnimplementedMissionServiceHandler) RegisterSatellite(context.Context, *connect.Request[api.RegisterSatelliteRequest]) (*connect.Response[api.RegisterSatelliteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satmission.v1.MissionService.RegisterSatellite is not implemented"))
}

func (UnimplementedMissionServiceHandler) GetSatellite(context.Context, *connect.Request[api.GetSatelliteRequest]) (*connect.Response[api.GetSatelliteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satmission.v1.MissionService.GetSatellite is not implemented"))
}

func (UnimplementedMissionServiceHandler) ListSatellites(context.Context, *connect.Request[api.ListSatellitesRequest]) (*connect.Response[api.ListSatellitesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satmission.v1.MissionService.ListSatellites is not implemented"))
}

func (UnimplementedMissionServiceHandler) UpdateTLE(context.Context, *connect.Request[api.UpdateTLERequest]) (*connect.Response[api.UpdateTLEResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satmission.v1.MissionService.UpdateTLE is not implemented"))
}

func (UnimplementedMissionServiceHandler) UpdateOrbitalState(context.Context, *connect.Request[api.UpdateOrbitalStateRequest]) (*connect.Response[api.UpdateOrbitalStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satmission.v1.MissionService.UpdateOrbitalState is not implemented"))
}

func (UnimplementedMissionServiceHandler) SetMode(context.Context, *connect.Request[api.SetModeRequest]) (*connect.Response[api.SetModeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satmission.v1.MissionService.SetMode is not implemented"))
}
