// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: p9e/space/satsubsys/v1/sat_telemetry.proto

package satsubsysv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ppusapati/space/api/p9e/space/satsubsys/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TelemetryServiceName is the fully-qualified name of the TelemetryService service.
	TelemetryServiceName = "p9e.space.satsubsys.v1.TelemetryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TelemetryServiceDefineChannelProcedure is the fully-qualified name of the TelemetryService's
	// DefineChannel RPC.
	TelemetryServiceDefineChannelProcedure = "/p9e.space.satsubsys.v1.TelemetryService/DefineChannel"
	// TelemetryServiceGetChannelProcedure is the fully-qualified name of the TelemetryService's
	// GetChannel RPC.
	TelemetryServiceGetChannelProcedure = "/p9e.space.satsubsys.v1.TelemetryService/GetChannel"
	// TelemetryServiceListChannelsProcedure is the fully-qualified name of the TelemetryService's
	// ListChannels RPC.
	TelemetryServiceListChannelsProcedure = "/p9e.space.satsubsys.v1.TelemetryService/ListChannels"
	// TelemetryServiceDeprecateChannelProcedure is the fully-qualified name of the TelemetryService's
	// DeprecateChannel RPC.
	TelemetryServiceDeprecateChannelProcedure = "/p9e.space.satsubsys.v1.TelemetryService/DeprecateChannel"
	// TelemetryServiceIngestTelemetryFrameProcedure is the fully-qualified name of the
	// TelemetryService's IngestTelemetryFrame RPC.
	TelemetryServiceIngestTelemetryFrameProcedure = "/p9e.space.satsubsys.v1.TelemetryService/IngestTelemetryFrame"
	// TelemetryServiceGetFrameProcedure is the fully-qualified name of the TelemetryService's GetFrame
	// RPC.
	TelemetryServiceGetFrameProcedure = "/p9e.space.satsubsys.v1.TelemetryService/GetFrame"
	// TelemetryServiceListFramesProcedure is the fully-qualified name of the TelemetryService's
	// ListFrames RPC.
	TelemetryServiceListFramesProcedure = "/p9e.space.satsubsys.v1.TelemetryService/ListFrames"
	// TelemetryServiceQuerySamplesProcedure is the fully-qualified name of the TelemetryService's
	// QuerySamples RPC.
	TelemetryServiceQuerySamplesProcedure = "/p9e.space.satsubsys.v1.TelemetryService/QuerySamples"
)

// TelemetryServiceClient is a client for the p9e.space.satsubsys.v1.TelemetryService service.
type TelemetryServiceClient interface {
	DefineChannel(context.Context, *connect.Request[v1.DefineChannelRequest]) (*connect.Response[v1.DefineChannelResponse], error)
	GetChannel(context.Context, *connect.Request[v1.GetChannelRequest]) (*connect.Response[v1.GetChannelResponse], error)
	ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error)
	DeprecateChannel(context.Context, *connect.Request[v1.DeprecateChannelRequest]) (*connect.Response[v1.DeprecateChannelResponse], error)
	IngestTelemetryFrame(context.Context, *connect.Request[v1.IngestTelemetryFrameRequest]) (*connect.Response[v1.IngestTelemetryFrameResponse], error)
	GetFrame(context.Context, *connect.Request[v1.GetFrameRequest]) (*connect.Response[v1.GetFrameResponse], error)
	ListFrames(context.Context, *connect.Request[v1.ListFramesRequest]) (*connect.Response[v1.ListFramesResponse], error)
	QuerySamples(context.Context, *connect.Request[v1.QuerySamplesRequest]) (*connect.Response[v1.QuerySamplesResponse], error)
}

// NewTelemetryServiceClient constructs a client for the p9e.space.satsubsys.v1.TelemetryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTelemetryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TelemetryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	telemetryServiceMethods := v1.File_p9e_space_satsubsys_v1_sat_telemetry_proto.Services().ByName("TelemetryService").Methods()
	return &telemetryServiceClient{
		defineChannel: connect.NewClient[v1.DefineChannelRequest, v1.DefineChannelResponse](
			httpClient,
			baseURL+TelemetryServiceDefineChannelProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("DefineChannel")),
			connect.WithClientOptions(opts...),
		),
		getChannel: connect.NewClient[v1.GetChannelRequest, v1.GetChannelResponse](
			httpClient,
			baseURL+TelemetryServiceGetChannelProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("GetChannel")),
			connect.WithClientOptions(opts...),
		),
		listChannels: connect.NewClient[v1.ListChannelsRequest, v1.ListChannelsResponse](
			httpClient,
			baseURL+TelemetryServiceListChannelsProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("ListChannels")),
			connect.WithClientOptions(opts...),
		),
		deprecateChannel: connect.NewClient[v1.DeprecateChannelRequest, v1.DeprecateChannelResponse](
			httpClient,
			baseURL+TelemetryServiceDeprecateChannelProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("DeprecateChannel")),
			connect.WithClientOptions(opts...),
		),
		ingestTelemetryFrame: connect.NewClient[v1.IngestTelemetryFrameRequest, v1.IngestTelemetryFrameResponse](
			httpClient,
			baseURL+TelemetryServiceIngestTelemetryFrameProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("IngestTelemetryFrame")),
			connect.WithClientOptions(opts...),
		),
		getFrame: connect.NewClient[v1.GetFrameRequest, v1.GetFrameResponse](
			httpClient,
			baseURL+TelemetryServiceGetFrameProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("GetFrame")),
			connect.WithClientOptions(opts...),
		),
		listFrames: connect.NewClient[v1.ListFramesRequest, v1.ListFramesResponse](
			httpClient,
			baseURL+TelemetryServiceListFramesProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("ListFrames")),
			connect.WithClientOptions(opts...),
		),
		querySamples: connect.NewClient[v1.QuerySamplesRequest, v1.QuerySamplesResponse](
			httpClient,
			baseURL+TelemetryServiceQuerySamplesProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("QuerySamples")),
			connect.WithClientOptions(opts...),
		),
	}
}

// telemetryServiceClient implements TelemetryServiceClient.
type telemetryServiceClient struct {
	defineChannel        *connect.Client[v1.DefineChannelRequest, v1.DefineChannelResponse]
	getChannel           *connect.Client[v1.GetChannelRequest, v1.GetChannelResponse]
	listChannels         *connect.Client[v1.ListChannelsRequest, v1.ListChannelsResponse]
	deprecateChannel     *connect.Client[v1.DeprecateChannelRequest, v1.DeprecateChannelResponse]
	ingestTelemetryFrame *connect.Client[v1.IngestTelemetryFrameRequest, v1.IngestTelemetryFrameResponse]
	getFrame             *connect.Client[v1.GetFrameRequest, v1.GetFrameResponse]
	listFrames           *connect.Client[v1.ListFramesRequest, v1.ListFramesResponse]
	querySamples         *connect.Client[v1.QuerySamplesRequest, v1.QuerySamplesResponse]
}

// DefineChannel calls p9e.space.satsubsys.v1.TelemetryService.DefineChannel.
func (c *telemetryServiceClient) DefineChannel(ctx context.Context, req *connect.Request[v1.DefineChannelRequest]) (*connect.Response[v1.DefineChannelResponse], error) {
	return c.defineChannel.CallUnary(ctx, req)
}

// GetChannel calls p9e.space.satsubsys.v1.TelemetryService.GetChannel.
func (c *telemetryServiceClient) GetChannel(ctx context.Context, req *connect.Request[v1.GetChannelRequest]) (*connect.Response[v1.GetChannelResponse], error) {
	return c.getChannel.CallUnary(ctx, req)
}

// ListChannels calls p9e.space.satsubsys.v1.TelemetryService.ListChannels.
func (c *telemetryServiceClient) ListChannels(ctx context.Context, req *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error) {
	return c.listChannels.CallUnary(ctx, req)
}

// DeprecateChannel calls p9e.space.satsubsys.v1.TelemetryService.DeprecateChannel.
func (c *telemetryServiceClient) DeprecateChannel(ctx context.Context, req *connect.Request[v1.DeprecateChannelRequest]) (*connect.Response[v1.DeprecateChannelResponse], error) {
	return c.deprecateChannel.CallUnary(ctx, req)
}

// IngestTelemetryFrame calls p9e.space.satsubsys.v1.TelemetryService.IngestTelemetryFrame.
func (c *telemetryServiceClient) IngestTelemetryFrame(ctx context.Context, req *connect.Request[v1.IngestTelemetryFrameRequest]) (*connect.Response[v1.IngestTelemetryFrameResponse], error) {
	return c.ingestTelemetryFrame.CallUnary(ctx, req)
}

// GetFrame calls p9e.space.satsubsys.v1.TelemetryService.GetFrame.
func (c *telemetryServiceClient) GetFrame(ctx context.Context, req *connect.Request[v1.GetFrameRequest]) (*connect.Response[v1.GetFrameResponse], error) {
	return c.getFrame.CallUnary(ctx, req)
}

// ListFrames calls p9e.space.satsubsys.v1.TelemetryService.ListFrames.
func (c *telemetryServiceClient) ListFrames(ctx context.Context, req *connect.Request[v1.ListFramesRequest]) (*connect.Response[v1.ListFramesResponse], error) {
	return c.listFrames.CallUnary(ctx, req)
}

// QuerySamples calls p9e.space.satsubsys.v1.TelemetryService.QuerySamples.
func (c *telemetryServiceClient) QuerySamples(ctx context.Context, req *connect.Request[v1.QuerySamplesRequest]) (*connect.Response[v1.QuerySamplesResponse], error) {
	return c.querySamples.CallUnary(ctx, req)
}

// TelemetryServiceHandler is an implementation of the p9e.space.satsubsys.v1.TelemetryService
// service.
type TelemetryServiceHandler interface {
	DefineChannel(context.Context, *connect.Request[v1.DefineChannelRequest]) (*connect.Response[v1.DefineChannelResponse], error)
	GetChannel(context.Context, *connect.Request[v1.GetChannelRequest]) (*connect.Response[v1.GetChannelResponse], error)
	ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error)
	DeprecateChannel(context.Context, *connect.Request[v1.DeprecateChannelRequest]) (*connect.Response[v1.DeprecateChannelResponse], error)
	IngestTelemetryFrame(context.Context, *connect.Request[v1.IngestTelemetryFrameRequest]) (*connect.Response[v1.IngestTelemetryFrameResponse], error)
	GetFrame(context.Context, *connect.Request[v1.GetFrameRequest]) (*connect.Response[v1.GetFrameResponse], error)
	ListFrames(context.Context, *connect.Request[v1.ListFramesRequest]) (*connect.Response[v1.ListFramesResponse], error)
	QuerySamples(context.Context, *connect.Request[v1.QuerySamplesRequest]) (*connect.Response[v1.QuerySamplesResponse], error)
}

// NewTelemetryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTelemetryServiceHandler(svc TelemetryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	telemetryServiceMethods := v1.File_p9e_space_satsubsys_v1_sat_telemetry_proto.Services().ByName("TelemetryService").Methods()
	telemetryServiceDefineChannelHandler := connect.NewUnaryHandler(
		TelemetryServiceDefineChannelProcedure,
		svc.DefineChannel,
		connect.WithSchema(telemetryServiceMethods.ByName("DefineChannel")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryServiceGetChannelHandler := connect.NewUnaryHandler(
		TelemetryServiceGetChannelProcedure,
		svc.GetChannel,
		connect.WithSchema(telemetryServiceMethods.ByName("GetChannel")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryServiceListChannelsHandler := connect.NewUnaryHandler(
		TelemetryServiceListChannelsProcedure,
		svc.ListChannels,
		connect.WithSchema(telemetryServiceMethods.ByName("ListChannels")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryServiceDeprecateChannelHandler := connect.NewUnaryHandler(
		TelemetryServiceDeprecateChannelProcedure,
		svc.DeprecateChannel,
		connect.WithSchema(telemetryServiceMethods.ByName("DeprecateChannel")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryServiceIngestTelemetryFrameHandler := connect.NewUnaryHandler(
		TelemetryServiceIngestTelemetryFrameProcedure,
		svc.IngestTelemetryFrame,
		connect.WithSchema(telemetryServiceMethods.ByName("IngestTelemetryFrame")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryServiceGetFrameHandler := connect.NewUnaryHandler(
		TelemetryServiceGetFrameProcedure,
		svc.GetFrame,
		connect.WithSchema(telemetryServiceMethods.ByName("GetFrame")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryServiceListFramesHandler := connect.NewUnaryHandler(
		TelemetryServiceListFramesProcedure,
		svc.ListFrames,
		connect.WithSchema(telemetryServiceMethods.ByName("ListFrames")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryServiceQuerySamplesHandler := connect.NewUnaryHandler(
		TelemetryServiceQuerySamplesProcedure,
		svc.QuerySamples,
		connect.WithSchema(telemetryServiceMethods.ByName("QuerySamples")),
		connect.WithHandlerOptions(opts...),
	)
	return "/p9e.space.satsubsys.v1.TelemetryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TelemetryServiceDefineChannelProcedure:
			telemetryServiceDefineChannelHandler.ServeHTTP(w, r)
		case TelemetryServiceGetChannelProcedure:
			telemetryServiceGetChannelHandler.ServeHTTP(w, r)
		case TelemetryServiceListChannelsProcedure:
			telemetryServiceListChannelsHandler.ServeHTTP(w, r)
		case TelemetryServiceDeprecateChannelProcedure:
			telemetryServiceDeprecateChannelHandler.ServeHTTP(w, r)
		case TelemetryServiceIngestTelemetryFrameProcedure:
			telemetryServiceIngestTelemetryFrameHandler.ServeHTTP(w, r)
		case TelemetryServiceGetFrameProcedure:
			telemetryServiceGetFrameHandler.ServeHTTP(w, r)
		case TelemetryServiceListFramesProcedure:
			telemetryServiceListFramesHandler.ServeHTTP(w, r)
		case TelemetryServiceQuerySamplesProcedure:
			telemetryServiceQuerySamplesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTelemetryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTelemetryServiceHandler struct{}

func (UnimplementedTelemetryServiceHandler) DefineChannel(context.Context, *connect.Request[v1.DefineChannelRequest]) (*connect.Response[v1.DefineChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satsubsys.v1.TelemetryService.DefineChannel is not implemented"))
}

func (UnimplementedTelemetryServiceHandler) GetChannel(context.Context, *connect.Request[v1.GetChannelRequest]) (*connect.Response[v1.GetChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satsubsys.v1.TelemetryService.GetChannel is not implemented"))
}

func (UnimplementedTelemetryServiceHandler) ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satsubsys.v1.TelemetryService.ListChannels is not implemented"))
}

func (UnimplementedTelemetryServiceHandler) DeprecateChannel(context.Context, *connect.Request[v1.DeprecateChannelRequest]) (*connect.Response[v1.DeprecateChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satsubsys.v1.TelemetryService.DeprecateChannel is not implemented"))
}

func (UnimplementedTelemetryServiceHandler) IngestTelemetryFrame(context.Context, *connect.Request[v1.IngestTelemetryFrameRequest]) (*connect.Response[v1.IngestTelemetryFrameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satsubsys.v1.TelemetryService.IngestTelemetryFrame is not implemented"))
}

func (UnimplementedTelemetryServiceHandler) GetFrame(context.Context, *connect.Request[v1.GetFrameRequest]) (*connect.Response[v1.GetFrameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satsubsys.v1.TelemetryService.GetFrame is not implemented"))
}

func (UnimplementedTelemetryServiceHandler) ListFrames(context.Context, *connect.Request[v1.ListFramesRequest]) (*connect.Response[v1.ListFramesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satsubsys.v1.TelemetryService.ListFrames is not implemented"))
}

func (UnimplementedTelemetryServiceHandler) QuerySamples(context.Context, *connect.Request[v1.QuerySamplesRequest]) (*connect.Response[v1.QuerySamplesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("p9e.space.satsubsys.v1.TelemetryService.QuerySamples is not implemented"))
}
